import HeytingLean.Core.Nucleus
import Mathlib.Tactic

/-!
# Premise Retrieval as Nucleus Selection

This module formalizes the connection between ATP premise retrieval and
CNCC nucleus operators. A `PremiseNucleus` is a closure operator on a
goal lattice whose focus lens is "goals for which this premise set suffices."

The `closureByFocus` construction (from CircuitNucleus.lean) is generalized
here to any type `G`, producing a `Core.Nucleus (G → Prop)` with the same
proof structure.

The retrieval gap and soundness definitions provide a formal specification
for retrieval quality: retrieval is sound iff its gap is empty.
-/

namespace HeytingLean.ATP

open HeytingLean.Core

/-- A proposition about goals in the proof search space. -/
abbrev GoalProp (G : Type*) := G → Prop

/-- Closure by a structural focus predicate, generalized from the CNCC's
`closureByFocus` (CircuitNucleus.lean:13-46). The nucleus enlarges a
property by adding every goal selected by the focus lens. -/
def closureByFocus {G : Type*} (focus : GoalProp G) : Nucleus (GoalProp G) where
  R := fun P g => P g ∨ focus g
  extensive := by
    intro P g hPg
    exact Or.inl hPg
  idempotent := by
    intro P
    funext g
    apply propext
    constructor
    · intro h
      rcases h with h | h
      · exact h
      · exact Or.inr h
    · intro h
      rcases h with h | h
      · exact Or.inl (Or.inl h)
      · exact Or.inr h
  meet_preserving := by
    intro P Q
    funext g
    apply propext
    constructor
    · intro h
      rcases h with ⟨hP, hQ⟩ | hF
      · exact ⟨Or.inl hP, Or.inl hQ⟩
      · exact ⟨Or.inr hF, Or.inr hF⟩
    · intro h
      rcases h with ⟨hP, hQ⟩
      rcases hP with hP | hF
      · rcases hQ with hQ | hF
        · exact Or.inl ⟨hP, hQ⟩
        · exact Or.inr hF
      · exact Or.inr hF

/-- A premise set selects a nucleus on the goal space.
The focus lens is the set of goals for which the premise set suffices. -/
structure PremiseNucleus (G : Type*) where
  /-- Name identifying the premise set (e.g., "mathlib_ring_theory"). -/
  tag : String
  /-- The set of goals this premise set can close. -/
  focus : GoalProp G

/-- Every premise nucleus is concretely the closure generated by its focus lens. -/
def PremiseNucleus.toNucleus {G : Type*} (R : PremiseNucleus G) : Nucleus (GoalProp G) :=
  closureByFocus R.focus

/-- Retrieval gap: goals where the nucleus says "these premises should work"
but the target property doesn't actually hold. -/
def retrievalGap {G : Type*} (R : PremiseNucleus G) (target : GoalProp G) : Set G :=
  { g | (R.toNucleus.R target) g ∧ ¬ target g }

/-- Retrieval is sound when the gap is empty:
no goal is accepted by the nucleus but rejected by the target property. -/
def RetrievalSound {G : Type*} (R : PremiseNucleus G) (target : GoalProp G) : Prop :=
  retrievalGap R target = ∅

/-- Two premise nuclei are independent when their closure operators commute. -/
def PremiseNucleus.independent {G : Type*} (R₁ R₂ : PremiseNucleus G) : Prop :=
  ∀ P : GoalProp G,
    R₁.toNucleus.R (R₂.toNucleus.R P) =
    R₂.toNucleus.R (R₁.toNucleus.R P)

/-- A trivial premise nucleus whose focus is empty (accepts no goals). -/
def PremiseNucleus.trivial (G : Type*) : PremiseNucleus G where
  tag := "trivial"
  focus := fun _ => False

/-- A universal premise nucleus whose focus is the full goal space. -/
def PremiseNucleus.universal (G : Type*) : PremiseNucleus G where
  tag := "universal"
  focus := fun _ => True

/-- The trivial nucleus has empty gap for any target.
Its closure adds nothing (focus = ∅), so R(P) = P for all P. -/
theorem trivial_gap_empty (G : Type*) (target : GoalProp G) :
    RetrievalSound (PremiseNucleus.trivial G) target := by
  simp [RetrievalSound, retrievalGap, PremiseNucleus.toNucleus, closureByFocus,
    PremiseNucleus.trivial]

/-- The universal nucleus is sound for any target that holds on all goals. -/
theorem universal_sound_of_total {G : Type*} (target : GoalProp G)
    (hTotal : ∀ g, target g) :
    RetrievalSound (PremiseNucleus.universal G) target := by
  simp only [RetrievalSound, retrievalGap, PremiseNucleus.toNucleus, closureByFocus,
    PremiseNucleus.universal]
  ext g
  simp [hTotal g]

/-- All closureByFocus premise nuclei are independent (commute).
This is the general form of `canonical_lenses_commute_algebraically`
(NucleusDecomposition.lean:29-52): closureByFocus R P g = P g ∨ focus g,
so double application in either order yields `P g ∨ focus₁ g ∨ focus₂ g`. -/
theorem closureByFocus_premise_nuclei_commute {G : Type*} (R₁ R₂ : PremiseNucleus G) :
    R₁.independent R₂ := by
  intro P
  funext g
  apply propext
  unfold PremiseNucleus.toNucleus closureByFocus
  simp
  tauto

end HeytingLean.ATP
