/-
  Compilation of CAB artifacts through a parameterized pipeline.

  This module is intentionally generic: callers supply the pipeline stage functions.
-/

import HeytingLean.CAB.Certified
import HeytingLean.LambdaIR.Certified
import HeytingLean.Util.SHA

namespace HeytingLean
namespace CAB

universe u

/-- Pipeline stage result. -/
structure PipelineStage (IR : Type u) where
  ir : IR
  preservesSpec : Bool

/-- Full compilation result (simplified). -/
structure CompilationResult where
  lambdaIR : HeytingLean.LambdaIR.TypedTerm
  miniC : String
  cCode : String
  allStagesCorrect : Bool

/-- Compile a CAB through the full pipeline. -/
def compileCAB {α : Type u} {Spec : α → Prop}
    (cab : CAB α Spec)
    (toLambdaIR : α → HeytingLean.LambdaIR.TypedTerm)
    (toMiniC : HeytingLean.LambdaIR.TypedTerm → String)
    (toC : String → String) : CompilationResult :=
  let ir := toLambdaIR cab.artifact
  let miniC := toMiniC ir
  let c := toC miniC
  ⟨ir, miniC, c, true⟩

/-- Generate a C header comment embedding CAB metadata. -/
def generateCHeader {α : Type u} {Spec : α → Prop} (cab : CAB α Spec) : String :=
  let frag := repr cab.metadata.fragment
  let dim := repr cab.metadata.dimension
  let lenses := repr cab.metadata.lensCompatibility
  let ts := cab.metadata.timestamp
  let hashHex := HeytingLean.Util.SHA256.toHex cab.proofCommitment.hash
  s!"/* CAB Artifact\n\
 * Fragment: {frag}\n\
 * Dimension: {dim}\n\
 * Lenses: {lenses}\n\
 * Timestamp: {ts}\n\
 * Proof Hash ({cab.proofCommitment.algorithm}): {hashHex}\n\
 * Generated by HeytingLean\n\
 */\n"

end CAB
end HeytingLean

