import Std
import Batteries.Lean.HashMap

/-!
# Knot theory: planar diagram (PD) encoding (toy, executable)

This module defines a small, executable representation of link diagrams intended as a
foundation for **state-sum** invariants such as the **Kauffman bracket**.

We use a PD-style encoding:
- A diagram consists of `n` crossings, each listing four arc labels.
- Each arc label must occur **exactly twice** across all crossings (it connects two half-edges).

This is intentionally minimal: it does not attempt planar embedding proofs or Reidemeister moves yet.
-/

namespace HeytingLean
namespace Topology
namespace Knot

open Std

/-- A single crossing in PD notation, with four incident arc labels. -/
structure Crossing where
  a : Nat
  b : Nat
  c : Nat
  d : Nat
deriving Repr, DecidableEq, Inhabited

namespace Crossing

def labels (x : Crossing) : Array Nat :=
  #[x.a, x.b, x.c, x.d]

def labelsList (x : Crossing) : List Nat :=
  x.labels.toList

end Crossing

/-- A (toy) link diagram encoding.

`freeLoops` counts disjoint circle components that do not contain crossings; this is useful
for state-sum normalisations (e.g. the Kauffman bracket's `⟨D ⊔ O⟩ = d · ⟨D⟩`). -/
structure PlanarDiagram where
  freeLoops : Nat := 0
  crossings : Array Crossing := #[]
deriving Repr, Inhabited

namespace PlanarDiagram

def numCrossings (d : PlanarDiagram) : Nat :=
  d.crossings.size

def numHalfEdges (d : PlanarDiagram) : Nat :=
  4 * d.numCrossings

/-- Validate local PD well-formedness.

Checks:
- each arc label appears exactly twice globally.
-/
def validate (d : PlanarDiagram) : Except String Unit := do
  let n := d.numCrossings
  let mut occ : Std.HashMap Nat Nat := {}
  for i in [0:n] do
    let c := d.crossings[i]!
    for pos in [0:4] do
      let lbl := c.labels[pos]!
      let k := match occ[lbl]? with
        | some v => v
        | none => 0
      occ := occ.insert lbl (k + 1)

  for (lbl, k) in occ.toList do
    if k != 2 then
      throw s!"arc label {lbl} occurs {k} times (expected 2)"

/-- Build the arc-adjacency involution for a PD diagram.

Returns an array `nbr` of length `4*n` such that:
`nbr[idx] = idx'` where `idx` and `idx'` are the two occurrences of the same arc label.

This is the key combinatorial ingredient for state-sum invariants: after choosing a smoothing
at each crossing, loop components are cycles in the 2-regular graph generated by arc-edges and
smoothing-edges.
-/
def buildArcNeighbor (d : PlanarDiagram) : Except String (Array Nat) := do
  validate d
  let n := d.numCrossings
  let m := 4 * n
  if m = 0 then
    return #[]

  let mut occs : Std.HashMap Nat (List Nat) := {}
  for i in [0:n] do
    let c := d.crossings[i]!
    for pos in [0:4] do
      let lbl := c.labels[pos]!
      let idx := 4 * i + pos
      let prev := match occs[lbl]? with
        | some xs => xs
        | none => []
      occs := occs.insert lbl (idx :: prev)

  let mut nbr : Array Nat := Array.replicate m 0
  for (lbl, xs) in occs.toList do
    match xs with
    | [i, j] =>
        nbr := nbr.set! i j
        nbr := nbr.set! j i
    | _ =>
        -- should be ruled out by `validate`, but keep this error for safety
        throw s!"arc label {lbl} does not have exactly two endpoints"
  return nbr

end PlanarDiagram

end Knot
end Topology
end HeytingLean
