import HeytingLean.LoF.Combinators.Category.CompletionHomotopy

/-!
# Completion2Cell — a non-thin completion calculus as a `Type` of 2-cells

`CompletionHomotopy` is a **Prop-valued** relation on labeled paths `LSteps` generated by completion
squares and closed under whiskering and equivalence closure.

For higher-dimensional rewriting it is useful to keep *explicit* 2-cell witnesses as data.  This
file introduces a conservative “free calculus” whose 2-cells are **generated** by completion squares
and closed under:

- reflexivity, symmetry, transitivity (vertical composition), and
- left/right whiskering (horizontal composition).

This gives a `Type` of 2-cells which forgets to the Prop relation `CompletionHomotopy`.

Note: this is a free construction; it does not quotient by coherence laws (so it is not yet a
strict/weak 2-category in Mathlib’s sense).
-/

namespace HeytingLean
namespace LoF
namespace Combinators
namespace Category

open HeytingLean.LoF
open HeytingLean.LoF.Comb

/-- A `Type`-valued completion calculus on labeled paths, generated by completion squares. -/
inductive Completion2Cell : {t u : Comb} → LSteps t u → LSteps t u → Type where
  | refl {t u : Comb} (p : LSteps t u) :
      Completion2Cell p p
  | symm {t u : Comb} {p q : LSteps t u} :
      Completion2Cell p q → Completion2Cell q p
  | trans {t u : Comb} {p q r : LSteps t u} :
      Completion2Cell p q → Completion2Cell q r → Completion2Cell p r
  | whisker_right {t u v : Comb} {p q : LSteps t u}
      (η : Completion2Cell p q) (r : LSteps u v) :
      Completion2Cell (LSteps.comp p r) (LSteps.comp q r)
  | whisker_left {s t u : Comb} (l : LSteps s t) {p q : LSteps t u}
      (η : Completion2Cell p q) :
      Completion2Cell (LSteps.comp l p) (LSteps.comp l q)
  | of_completion {t : Comb} (c : Completion t) :
      Completion2Cell (Completion.leftPath c) (Completion.rightPath c)

namespace Completion2Cell

/-- Forget data to the Prop-valued completion homotopy relation. -/
def toHomotopy : {t u : Comb} → {p q : LSteps t u} → Completion2Cell p q → CompletionHomotopy p q
  | _, _, _, _, .refl p => CompletionHomotopy.refl p
  | _, _, _, _, .symm η => CompletionHomotopy.symm (toHomotopy η)
  | _, _, _, _, .trans η θ => CompletionHomotopy.trans (toHomotopy η) (toHomotopy θ)
  | _, _, _, _, .whisker_right η r => CompletionHomotopy.whisker_right (toHomotopy η) r
  | _, _, _, _, .whisker_left l η => CompletionHomotopy.whisker_left l (toHomotopy η)
  | _, _, _, _, .of_completion c => CompletionHomotopy.of_completion c

end Completion2Cell

end Category
end Combinators
end LoF
end HeytingLean

