import HeytingLean.Quantum.OML.Sasaki
import HeytingLean.LoF.Bauer.DoubleNegation
import HeytingLean.Magma.Bridge.NucleusProjection

/-!
# Dimensional Ratchet: 0D ↔ 1D ↔ 2D ↔ 3D logic hierarchy (interface-first)

This module records a “dimensional ratchet” narrative as an explicit set of *typed transports*:

* **0D (Magmatic)**: inseparable pre-distinction domain before functional decomposition
* **1D (Heyting)**: constructive / distributive implication
* **2D (Orthomodular)**: quantum / non-distributive lattice with orthocomplement
* **3D (Boolean)**: classical / excluded middle

What is fully mechanized here (no placeholder proofs):

* The `D0_Magmatic → D1_Heyting` transport as nucleus application to a magmatic family.
* Sasaki projection/hook on an orthomodular lattice (`HeytingLean.Quantum.OML.Sasaki`).
* A clean idempotence lemma for Sasaki projection (as a projection operator).
* Bauer’s double-negation nucleus and Booleanization (`HeytingLean.LoF.Bauer.DoubleNegation`),
  giving an explicit Heyting → Boolean “classical core” transport.

What is **left as an explicit interface** (no axioms added, but not proved here):

* A general, nontrivial “OML → Heyting” transport that would justify calling the Sasaki
  projection a *Heytingification nucleus* in full generality.

This matches the repo’s overall approach: land the correct interfaces and theorems that are
already available, and isolate any deeper claims behind explicit hypotheses.
-/

namespace HeytingLean
namespace Topos
namespace DimensionalRatchet

open HeytingLean.Quantum
open HeytingLean.LoF

/-! ## Dimension tags -/

inductive LogicDimension where
  | D0_Magmatic
  | D1_Heyting
  | D2_Orthomodular
  | D3_Boolean
  deriving DecidableEq, Repr

/-! ## Magmatic → Heyting (0D / pre-distinction into fixed-point core) -/

namespace Magmatic

open HeytingLean.Magma
open HeytingLean.Magma.Bridge

variable {A : Type _} [MagmaticAtoms A] [u : MagmaticUniverse A] [PairEncoding A] [ProductEncoding A]

/-- The D0 → D1 transport is nucleus application to the lower family generated by a magma. -/
def toHeytingCore (N : MagmaticNucleus A) (x : Magma A) : Set (Magma A) :=
  N.nucleus.R (familyOf x)

theorem toHeytingCore_eq_family_iff (N : MagmaticNucleus A) (x : Magma A) :
    toHeytingCore N x = familyOf x ↔ x ∈ omega_R N := by
  rfl

end Magmatic

/-! ## Sasaki operations (2D / orthomodular layer) -/

namespace Sasaki

open HeytingLean.Quantum.OML

variable {α : Type _} [OrthocomplementedLattice α] [OrthomodularLattice α]

theorem proj_idempotent (a b : α) : a ▷ (a ▷ b) = a ▷ b := by
  -- `a ▷ b ≤ a`, so `a ▷ (a ▷ b) = a ▷ b` by the “below the projector” lemma.
  have hle : a ▷ b ≤ a := OML.sasakiProj_le_left (a := a) (b := b)
  exact OML.sasakiProj_id_of_le (a := a) (b := (a ▷ b)) hle

end Sasaki

/-! ## Heyting → Boolean (3D classical core via double negation) -/

namespace Bauer

open HeytingLean.LoF.Bauer

universe u

variable (α : Type u) [HeytingAlgebra α]

abbrev doubleNegNucleus := HeytingLean.LoF.Bauer.doubleNegNucleus α
abbrev ClassicalCore := HeytingLean.LoF.Bauer.ClassicalCore α

/-- The double-negation classical core carries a Boolean algebra structure. -/
def classicalCoreBoolean : BooleanAlgebra (ClassicalCore α) := by
  dsimp [ClassicalCore]
  infer_instance

end Bauer

/-! ## Interface: OML → Heyting transport (not proved here) -/

namespace Interface

open HeytingLean.Quantum.OML

/-- A placeholder *interface* for a nontrivial transport from an orthomodular lattice into a
Heyting algebra “constructive core”.

We keep this as data so downstream physics/topos developments can supply a concrete construction
without forcing this module to overclaim. -/
structure OMLToHeyting (β : Type _) [OrthocomplementedLattice β] [OrthomodularLattice β] where
  (H : Type _)
  [instHeyting : HeytingAlgebra H]

attribute [instance] OMLToHeyting.instHeyting

end Interface

end DimensionalRatchet
end Topos
end HeytingLean
