import HeytingLean.LoF.Combinators.Category.CompletionCells

/-!
# CompletionHomotopy — 2-cells generated by completion squares

`CompletionCells` provides (bounded-search) *data* of local squares in the multiway graph:

```
      t
    ↙   ↘
   u     v
    ↘   ↙
      w
```

where the top edges are one-step labeled reductions and the legs to `w` are labeled multi-step paths.

This file packages these squares as a **2-cell generator relation** on labeled paths `LSteps`,
closed under:

- reflexivity/symmetry/transitivity, and
- left/right whiskering (pre/post composition by a fixed path).

This is a minimal, “paper-shaped” notion of homotopy suitable as a growth point for higher-dimensional
rewriting (polygraph-style generation).
-/

namespace HeytingLean
namespace LoF
namespace Combinators
namespace Category

open HeytingLean.LoF
open HeytingLean.LoF.Comb

/-- A 2-cell relation on labeled paths generated by completion squares. -/
inductive CompletionHomotopy : {t u : Comb} → LSteps t u → LSteps t u → Prop where
  | refl {t u : Comb} (p : LSteps t u) :
      CompletionHomotopy p p
  | symm {t u : Comb} {p q : LSteps t u} :
      CompletionHomotopy p q → CompletionHomotopy q p
  | trans {t u : Comb} {p q r : LSteps t u} :
      CompletionHomotopy p q → CompletionHomotopy q r → CompletionHomotopy p r
  | whisker_right {t u v : Comb} {p q : LSteps t u}
      (h : CompletionHomotopy p q) (r : LSteps u v) :
      CompletionHomotopy (LSteps.comp p r) (LSteps.comp q r)
  | whisker_left {s t u : Comb} (l : LSteps s t) {p q : LSteps t u}
      (h : CompletionHomotopy p q) :
      CompletionHomotopy (LSteps.comp l p) (LSteps.comp l q)
  | of_completion {t : Comb} (c : Completion t) :
      CompletionHomotopy (Completion.leftPath c) (Completion.rightPath c)

namespace CompletionHomotopy

instance {t u : Comb} : Setoid (LSteps t u) where
  r := CompletionHomotopy
  iseqv :=
    ⟨CompletionHomotopy.refl, (fun h => CompletionHomotopy.symm h), (fun h1 h2 => CompletionHomotopy.trans h1 h2)⟩

end CompletionHomotopy

end Category
end Combinators
end LoF
end HeytingLean

