import HeytingLean.LoF.Combinators.Category.Completion2PathBicategory

/-!
# Completion3Cell — explicit 3-cells for completion 2-path coherence

`Completion2PathBicategory.lean` constructs a non-thin bicategory by quotienting explicit
completion 2-cells (`Completion2Path`) by a Prop-valued relation `Completion2PathRel`
generated by bicategory coherence axioms and closed under vertical composition and whiskering.

For the “higher cell” program we want these coherence steps as *data* rather than only as a
quotient relation.  This file reifies the generators of `Completion2PathRel` as a `Type` of
3-cells between parallel `Completion2Path`s.
-/

namespace HeytingLean
namespace LoF
namespace Combinators
namespace Category

open CategoryTheory

/-- Type-valued 3-cells witnessing coherence between parallel completion 2-paths.

This is a reification of the Prop-level relation `Completion2PathRel` used to build
`skyCompletion2PathQuotBicategory`, with additional reflexivity/symmetry/transitivity
constructors so 3-cells can be composed as explicit witness data. -/
inductive Completion3Cell :
    ∀ {a b : MWObj} {p q : a ⟶ b}, Completion2Path p q → Completion2Path p q → Type
  | refl {a b : MWObj} {p q : a ⟶ b} (η : Completion2Path p q) :
      Completion3Cell η η
  | symm {a b : MWObj} {p q : a ⟶ b} {η η' : Completion2Path p q} :
      Completion3Cell η η' → Completion3Cell η' η
  | trans {a b : MWObj} {p q : a ⟶ b} {η η' η'' : Completion2Path p q} :
      Completion3Cell η η' → Completion3Cell η' η'' → Completion3Cell η η''
  | vcomp_left {a b : MWObj} {p q r : a ⟶ b}
      (η₁ η₂ : Completion2Path p q) (θ : Completion2Path q r) :
      Completion3Cell η₁ η₂ →
        Completion3Cell (Completion2Path.vcomp η₁ θ) (Completion2Path.vcomp η₂ θ)
  | vcomp_right {a b : MWObj} {p q r : a ⟶ b}
      (η : Completion2Path p q) (θ₁ θ₂ : Completion2Path q r) :
      Completion3Cell θ₁ θ₂ →
        Completion3Cell (Completion2Path.vcomp η θ₁) (Completion2Path.vcomp η θ₂)
  | whisker_left {a b c : MWObj} (f : a ⟶ b) {g h : b ⟶ c}
      (η η' : Completion2Path g h) :
      Completion3Cell η η' →
        Completion3Cell (Completion2Path.whiskerLeft f η) (Completion2Path.whiskerLeft f η')
  | whisker_right {a b c : MWObj} {f g : a ⟶ b}
      (η η' : Completion2Path f g) (h : b ⟶ c) :
      Completion3Cell η η' →
        Completion3Cell (Completion2Path.whiskerRight η h) (Completion2Path.whiskerRight η' h)
  | whisker_left_id {a b c : MWObj} (f : a ⟶ b) (g : b ⟶ c) :
      Completion3Cell
        (Completion2Path.whiskerLeft f (Completion2Path.id g))
        (Completion2Path.id (f ≫ g))
  | whisker_left_comp {a b c : MWObj} (f : a ⟶ b) {g h i : b ⟶ c}
      (η : Completion2Path g h) (θ : Completion2Path h i) :
      Completion3Cell
        (Completion2Path.whiskerLeft f (Completion2Path.vcomp η θ))
        (Completion2Path.vcomp (Completion2Path.whiskerLeft f η) (Completion2Path.whiskerLeft f θ))
  | id_whisker_left {a b : MWObj} {f g : a ⟶ b} (η : Completion2Path f g) :
      Completion3Cell
        (Completion2Path.whiskerLeft (𝟙 a) η)
        (Completion2Path.vcomp (Completion2Path.id f)
          (Completion2Path.vcomp η (Completion2Path.id g)))
  | comp_whisker_left {a b c d : MWObj} (f : a ⟶ b) (g : b ⟶ c) {h h' : c ⟶ d}
      (η : Completion2Path h h') :
      Completion3Cell
        (Completion2Path.whiskerLeft (f ≫ g) η)
        (Completion2Path.vcomp (Completion2Path.eqToHom (LSteps.comp_assoc f g h))
          (Completion2Path.vcomp (Completion2Path.whiskerLeft f (Completion2Path.whiskerLeft g η))
            (Completion2Path.eqToHom (LSteps.comp_assoc f g h').symm)))
  | id_whisker_right {a b c : MWObj} (f : a ⟶ b) (g : b ⟶ c) :
      Completion3Cell
        (Completion2Path.whiskerRight (Completion2Path.id f) g)
        (Completion2Path.id (f ≫ g))
  | comp_whisker_right {a b c : MWObj} {f g h : a ⟶ b} (η : Completion2Path f g)
      (θ : Completion2Path g h) (i : b ⟶ c) :
      Completion3Cell
        (Completion2Path.whiskerRight (Completion2Path.vcomp η θ) i)
        (Completion2Path.vcomp (Completion2Path.whiskerRight η i) (Completion2Path.whiskerRight θ i))
  | whisker_right_id {a b : MWObj} {f g : a ⟶ b} (η : Completion2Path f g) :
      Completion3Cell
        (Completion2Path.whiskerRight η (𝟙 b))
        (Completion2Path.vcomp (Completion2Path.eqToHom (LSteps.comp_refl_right f))
          (Completion2Path.vcomp η (Completion2Path.eqToHom (LSteps.comp_refl_right g).symm)))
  | whisker_right_comp {a b c d : MWObj} {f f' : a ⟶ b} (η : Completion2Path f f')
      (g : b ⟶ c) (h : c ⟶ d) :
      Completion3Cell
        (Completion2Path.whiskerRight η (g ≫ h))
        (Completion2Path.vcomp (Completion2Path.eqToHom (LSteps.comp_assoc f g h).symm)
          (Completion2Path.vcomp (Completion2Path.whiskerRight (Completion2Path.whiskerRight η g) h)
            (Completion2Path.eqToHom (LSteps.comp_assoc f' g h))))
  | whisker_assoc {a b c d : MWObj} (f : a ⟶ b) {g g' : b ⟶ c} (η : Completion2Path g g')
      (h : c ⟶ d) :
      Completion3Cell
        (Completion2Path.whiskerRight (Completion2Path.whiskerLeft f η) h)
        (Completion2Path.vcomp (Completion2Path.eqToHom (LSteps.comp_assoc f g h))
          (Completion2Path.vcomp (Completion2Path.whiskerLeft f (Completion2Path.whiskerRight η h))
            (Completion2Path.eqToHom (LSteps.comp_assoc f g' h).symm)))
  | whisker_exchange {a b c : MWObj}
      {f g : a ⟶ b} {h i : b ⟶ c}
      (η : Completion2Path f g) (θ : Completion2Path h i) :
      Completion3Cell
        (Completion2Path.vcomp (Completion2Path.whiskerLeft f θ) (Completion2Path.whiskerRight η i))
        (Completion2Path.vcomp (Completion2Path.whiskerRight η h) (Completion2Path.whiskerLeft g θ))
  | pentagon {a b c d e : MWObj} (f : a ⟶ b) (g : b ⟶ c) (h : c ⟶ d) (i : d ⟶ e) :
      Completion3Cell
        (Completion2Path.vcomp
          (Completion2Path.whiskerRight (Completion2Path.eqToHom (LSteps.comp_assoc f g h)) i)
          (Completion2Path.vcomp (Completion2Path.eqToHom (LSteps.comp_assoc f (g ≫ h) i))
            (Completion2Path.whiskerLeft f (Completion2Path.eqToHom (LSteps.comp_assoc g h i)))))
        (Completion2Path.vcomp (Completion2Path.eqToHom (LSteps.comp_assoc (f ≫ g) h i))
          (Completion2Path.eqToHom (LSteps.comp_assoc f g (h ≫ i))))
  | triangle {a b c : MWObj} (f : a ⟶ b) (g : b ⟶ c) :
      Completion3Cell
        (Completion2Path.vcomp (Completion2Path.eqToHom (LSteps.comp_assoc f (𝟙 b) g))
          (Completion2Path.whiskerLeft f (Completion2Path.id g)))
        (Completion2Path.whiskerRight (Completion2Path.eqToHom (LSteps.comp_refl_right f)) g)

namespace Completion3Cell

/-- Reify a Prop-level coherence step into **existence** of an explicit 3-cell witness.

Because `Completion2PathRel` lives in `Prop` and has multiple constructors, Lean’s elimination
restriction prevents a definitional function `Completion2PathRel → Completion3Cell`.
This lemma is the strongest constructively available form (`Nonempty`). -/
theorem nonempty_ofRel {a b : MWObj} {p q : a ⟶ b} {η η' : Completion2Path p q} :
    Completion2PathRel (a := a) (b := b) (p := p) (q := q) η η' → Nonempty (Completion3Cell η η') := by
  intro h
  induction h with
  | vcomp_left η₁ η₂ θ hRel ih =>
      rcases ih with ⟨cell⟩
      exact ⟨Completion3Cell.vcomp_left (η₁ := η₁) (η₂ := η₂) (θ := θ) cell⟩
  | vcomp_right η θ₁ θ₂ hRel ih =>
      rcases ih with ⟨cell⟩
      exact ⟨Completion3Cell.vcomp_right (η := η) (θ₁ := θ₁) (θ₂ := θ₂) cell⟩
  | whisker_left f η₁ η₂ hRel ih =>
      rcases ih with ⟨cell⟩
      exact ⟨Completion3Cell.whisker_left (f := f) (η := η₁) (η' := η₂) cell⟩
  | whisker_right η₁ η₂ h hRel ih =>
      rcases ih with ⟨cell⟩
      exact ⟨Completion3Cell.whisker_right (η := η₁) (η' := η₂) (h := h) cell⟩
  | whisker_left_id f g =>
      exact ⟨Completion3Cell.whisker_left_id (f := f) (g := g)⟩
  | whisker_left_comp f η θ =>
      exact ⟨Completion3Cell.whisker_left_comp (f := f) (η := η) (θ := θ)⟩
  | id_whisker_left η =>
      exact ⟨Completion3Cell.id_whisker_left (η := η)⟩
  | comp_whisker_left f g η =>
      exact ⟨Completion3Cell.comp_whisker_left (f := f) (g := g) (η := η)⟩
  | id_whisker_right f g =>
      exact ⟨Completion3Cell.id_whisker_right (f := f) (g := g)⟩
  | comp_whisker_right η θ i =>
      exact ⟨Completion3Cell.comp_whisker_right (η := η) (θ := θ) (i := i)⟩
  | whisker_right_id η =>
      exact ⟨Completion3Cell.whisker_right_id (η := η)⟩
  | whisker_right_comp η g h =>
      exact ⟨Completion3Cell.whisker_right_comp (η := η) (g := g) (h := h)⟩
  | whisker_assoc f η h =>
      exact ⟨Completion3Cell.whisker_assoc (f := f) (η := η) (h := h)⟩
  | whisker_exchange η θ =>
      exact ⟨Completion3Cell.whisker_exchange (η := η) (θ := θ)⟩
  | pentagon f g h i =>
      exact ⟨Completion3Cell.pentagon (f := f) (g := g) (h := h) (i := i)⟩
  | triangle f g =>
      exact ⟨Completion3Cell.triangle (f := f) (g := g)⟩

end Completion3Cell

end Category
end Combinators
end LoF
end HeytingLean
