import Mathlib.CategoryTheory.Bicategory.Basic
import Mathlib.CategoryTheory.EqToHom
import HeytingLean.LoF.Combinators.Category.Completion2Path

/-!
# Completion2PathBicategory — a non-thin bicategory from completion generators

`Completion2Path` provides non-thin 2-cells between parallel labeled paths as paths in a
completion-rule generator quiver.

As raw generator paths, these 2-cells do not satisfy the bicategory exchange law strictly.
This file constructs a bicategory by quotienting the 2-cells by the exchange relation and
closing under vertical composition and whiskering.
-/

namespace HeytingLean
namespace LoF
namespace Combinators
namespace Category

open CategoryTheory

open HeytingLean.LoF
open HeytingLean.LoF.Comb

/-! ## The exchange congruence on `Completion2Path` -/

/-- A relation on `Completion2Path` generated by the bicategory exchange law and closed under
vertical composition and whiskering. -/
inductive Completion2PathRel :
    ∀ {a b : MWObj} {p q : a ⟶ b}, Completion2Path p q → Completion2Path p q → Prop
  | vcomp_left {a b : MWObj} {p q r : a ⟶ b}
      (η₁ η₂ : Completion2Path p q) (θ : Completion2Path q r) :
      Completion2PathRel η₁ η₂ →
        Completion2PathRel (Completion2Path.vcomp η₁ θ) (Completion2Path.vcomp η₂ θ)
  | vcomp_right {a b : MWObj} {p q r : a ⟶ b}
      (η : Completion2Path p q) (θ₁ θ₂ : Completion2Path q r) :
      Completion2PathRel θ₁ θ₂ →
        Completion2PathRel (Completion2Path.vcomp η θ₁) (Completion2Path.vcomp η θ₂)
  | whisker_left {a b c : MWObj} (f : a ⟶ b) {g h : b ⟶ c}
      (η η' : Completion2Path g h) :
      Completion2PathRel η η' →
        Completion2PathRel (Completion2Path.whiskerLeft f η) (Completion2Path.whiskerLeft f η')
  | whisker_right {a b c : MWObj} {f g : a ⟶ b}
      (η η' : Completion2Path f g) (h : b ⟶ c) :
      Completion2PathRel η η' →
        Completion2PathRel (Completion2Path.whiskerRight η h) (Completion2Path.whiskerRight η' h)
  | whisker_left_id {a b c : MWObj} (f : a ⟶ b) (g : b ⟶ c) :
      Completion2PathRel
        (Completion2Path.whiskerLeft f (Completion2Path.id g))
        (Completion2Path.id (f ≫ g))
  | whisker_left_comp {a b c : MWObj} (f : a ⟶ b) {g h i : b ⟶ c}
      (η : Completion2Path g h) (θ : Completion2Path h i) :
      Completion2PathRel
        (Completion2Path.whiskerLeft f (Completion2Path.vcomp η θ))
        (Completion2Path.vcomp (Completion2Path.whiskerLeft f η) (Completion2Path.whiskerLeft f θ))
  | id_whisker_left {a b : MWObj} {f g : a ⟶ b} (η : Completion2Path f g) :
      Completion2PathRel
        (Completion2Path.whiskerLeft (𝟙 a) η)
        (Completion2Path.vcomp (Completion2Path.id f) (Completion2Path.vcomp η (Completion2Path.id g)))
  | comp_whisker_left {a b c d : MWObj} (f : a ⟶ b) (g : b ⟶ c) {h h' : c ⟶ d}
      (η : Completion2Path h h') :
      Completion2PathRel
        (Completion2Path.whiskerLeft (f ≫ g) η)
        (Completion2Path.vcomp (Completion2Path.eqToHom (LSteps.comp_assoc f g h))
          (Completion2Path.vcomp (Completion2Path.whiskerLeft f (Completion2Path.whiskerLeft g η))
            (Completion2Path.eqToHom (LSteps.comp_assoc f g h').symm)))
  | id_whisker_right {a b c : MWObj} (f : a ⟶ b) (g : b ⟶ c) :
      Completion2PathRel
        (Completion2Path.whiskerRight (Completion2Path.id f) g)
        (Completion2Path.id (f ≫ g))
  | comp_whisker_right {a b c : MWObj} {f g h : a ⟶ b} (η : Completion2Path f g)
      (θ : Completion2Path g h) (i : b ⟶ c) :
      Completion2PathRel
        (Completion2Path.whiskerRight (Completion2Path.vcomp η θ) i)
        (Completion2Path.vcomp (Completion2Path.whiskerRight η i) (Completion2Path.whiskerRight θ i))
  | whisker_right_id {a b : MWObj} {f g : a ⟶ b} (η : Completion2Path f g) :
      Completion2PathRel
        (Completion2Path.whiskerRight η (𝟙 b))
        (Completion2Path.vcomp (Completion2Path.eqToHom (LSteps.comp_refl_right f))
          (Completion2Path.vcomp η (Completion2Path.eqToHom (LSteps.comp_refl_right g).symm)))
  | whisker_right_comp {a b c d : MWObj} {f f' : a ⟶ b} (η : Completion2Path f f')
      (g : b ⟶ c) (h : c ⟶ d) :
      Completion2PathRel
        (Completion2Path.whiskerRight η (g ≫ h))
        (Completion2Path.vcomp (Completion2Path.eqToHom (LSteps.comp_assoc f g h).symm)
          (Completion2Path.vcomp (Completion2Path.whiskerRight (Completion2Path.whiskerRight η g) h)
            (Completion2Path.eqToHom (LSteps.comp_assoc f' g h))))
  | whisker_assoc {a b c d : MWObj} (f : a ⟶ b) {g g' : b ⟶ c} (η : Completion2Path g g')
      (h : c ⟶ d) :
      Completion2PathRel
        (Completion2Path.whiskerRight (Completion2Path.whiskerLeft f η) h)
        (Completion2Path.vcomp (Completion2Path.eqToHom (LSteps.comp_assoc f g h))
          (Completion2Path.vcomp (Completion2Path.whiskerLeft f (Completion2Path.whiskerRight η h))
            (Completion2Path.eqToHom (LSteps.comp_assoc f g' h).symm)))
  | whisker_exchange {a b c : MWObj}
      {f g : a ⟶ b} {h i : b ⟶ c}
      (η : Completion2Path f g) (θ : Completion2Path h i) :
      Completion2PathRel
        (Completion2Path.vcomp (Completion2Path.whiskerLeft f θ) (Completion2Path.whiskerRight η i))
        (Completion2Path.vcomp (Completion2Path.whiskerRight η h) (Completion2Path.whiskerLeft g θ))
  | pentagon {a b c d e : MWObj} (f : a ⟶ b) (g : b ⟶ c) (h : c ⟶ d) (i : d ⟶ e) :
      Completion2PathRel
        (Completion2Path.vcomp
          (Completion2Path.whiskerRight (Completion2Path.eqToHom (LSteps.comp_assoc f g h)) i)
          (Completion2Path.vcomp (Completion2Path.eqToHom (LSteps.comp_assoc f (g ≫ h) i))
            (Completion2Path.whiskerLeft f (Completion2Path.eqToHom (LSteps.comp_assoc g h i)))))
        (Completion2Path.vcomp (Completion2Path.eqToHom (LSteps.comp_assoc (f ≫ g) h i))
          (Completion2Path.eqToHom (LSteps.comp_assoc f g (h ≫ i))))
  | triangle {a b c : MWObj} (f : a ⟶ b) (g : b ⟶ c) :
      Completion2PathRel
        (Completion2Path.vcomp (Completion2Path.eqToHom (LSteps.comp_assoc f (𝟙 b) g))
          (Completion2Path.whiskerLeft f (Completion2Path.id g)))
        (Completion2Path.whiskerRight (Completion2Path.eqToHom (LSteps.comp_refl_right f)) g)

/-! ## The quotient hom-category -/

/-- 2-cells in the quotient hom-category. -/
abbrev Completion2PathQuot {a b : MWObj} (p q : a ⟶ b) : Type :=
  Quot (Completion2PathRel (a := a) (b := b) (p := p) (q := q))

namespace Completion2PathQuot

/-- Category structure on each hom-type `a ⟶ b`, with morphisms the quotient 2-cells. -/
def homCategory (a b : MWObj) : Category (a ⟶ b) where
  Hom p q := Completion2PathQuot p q
  id p := Quot.mk _ (Completion2Path.id (a := a) (b := b) p)
  comp η θ :=
    Quot.map₂ (fun x y => Completion2Path.vcomp x y)
      (fun η θ₁ θ₂ hRel => Completion2PathRel.vcomp_right (a := a) (b := b) η θ₁ θ₂ hRel)
      (fun η₁ η₂ θ hRel => Completion2PathRel.vcomp_left (a := a) (b := b) η₁ η₂ θ hRel)
      η θ
  id_comp := by
    intro X Y f
    refine Quot.inductionOn f ?_
    intro η
    simp [Completion2Path.id, Completion2Path.vcomp]
  comp_id := by
    intro X Y f
    refine Quot.inductionOn f ?_
    intro η
    simp [Completion2Path.id, Completion2Path.vcomp]
  assoc := by
    intro W X Y Z f g h
    refine Quot.inductionOn f ?_
    intro η
    refine Quot.inductionOn g ?_
    intro θ
    refine Quot.inductionOn h ?_
    intro ι
    simp [Completion2Path.vcomp]

end Completion2PathQuot

/-! ## A bridge from `eqToIso` to the quotient constructors -/

/-- In the quotient hom-category, `eqToHom` is represented by the empty generator path. -/
theorem eqToHom_eq_mk {a b : MWObj} {p q : a ⟶ b} (h : p = q) :
    (by
        letI : Category (a ⟶ b) := Completion2PathQuot.homCategory a b
        exact (CategoryTheory.eqToHom h : p ⟶ q)) =
      Quot.mk _ (Completion2Path.eqToHom (a := a) (b := b) h) := by
  letI : Category (a ⟶ b) := Completion2PathQuot.homCategory a b
  cases h
  rfl

/-! ## The bicategory on `MWObj` -/

/-- A non-thin bicategory on `MWObj` obtained by quotienting `Completion2Path` by the exchange law. -/
def skyCompletion2PathQuotBicategory : Bicategory MWObj where
  toCategoryStruct := (inferInstance : CategoryStruct MWObj)
  homCategory a b := Completion2PathQuot.homCategory a b
  whiskerLeft {a b c} f {g h} η :=
    Quot.map (Completion2Path.whiskerLeft (a := a) (b := b) (c := c) f)
      (fun x y hRel => Completion2PathRel.whisker_left (f := f) x y hRel)
      η
  whiskerRight {a b c} {f g} η h :=
    Quot.map (fun x => Completion2Path.whiskerRight (a := a) (b := b) (c := c) x h)
      (fun x y hRel => Completion2PathRel.whisker_right (h := h) x y hRel)
      η
  associator {a b c d} f g h := by
    letI : Category (a ⟶ d) := Completion2PathQuot.homCategory a d
    exact eqToIso (LSteps.comp_assoc f g h)
  leftUnitor {a b} f := by
    letI : Category (a ⟶ b) := Completion2PathQuot.homCategory a b
    exact eqToIso (by rfl)
  rightUnitor {a b} f := by
    letI : Category (a ⟶ b) := Completion2PathQuot.homCategory a b
    exact eqToIso (LSteps.comp_refl_right f)
  whiskerLeft_id := by
    intro a b c f g
    exact Quot.sound (Completion2PathRel.whisker_left_id (f := f) (g := g))
  whiskerLeft_comp := by
    intro a b c f g h i η θ
    refine Quot.inductionOn η ?_
    intro η'
    refine Quot.inductionOn θ ?_
    intro θ'
    exact Quot.sound (Completion2PathRel.whisker_left_comp (f := f) (η := η') (θ := θ'))
  id_whiskerLeft := by
    intro a b f g η
    refine Quot.inductionOn η ?_
    intro η'
    exact Quot.sound (Completion2PathRel.id_whisker_left (η := η'))
  comp_whiskerLeft := by
    intro a b c d f g h h' η
    refine Quot.inductionOn η ?_
    intro η'
    simpa [eqToHom_eq_mk] using
      (Quot.sound (Completion2PathRel.comp_whisker_left (f := f) (g := g) (η := η')))
  id_whiskerRight := by
    intro a b c f g
    exact Quot.sound (Completion2PathRel.id_whisker_right (f := f) (g := g))
  comp_whiskerRight := by
    intro a b c f g h η θ i
    refine Quot.inductionOn η ?_
    intro η'
    refine Quot.inductionOn θ ?_
    intro θ'
    exact Quot.sound (Completion2PathRel.comp_whisker_right (η := η') (θ := θ') (i := i))
  whiskerRight_id := by
    intro a b f g η
    refine Quot.inductionOn η ?_
    intro η'
    simpa [eqToHom_eq_mk] using
      (Quot.sound (Completion2PathRel.whisker_right_id (η := η')))
  whiskerRight_comp := by
    intro a b c d f f' η g h
    refine Quot.inductionOn η ?_
    intro η'
    simpa [eqToHom_eq_mk] using
      (Quot.sound (Completion2PathRel.whisker_right_comp (η := η') (g := g) (h := h)))
  whisker_assoc := by
    intro a b c d f g g' η h
    refine Quot.inductionOn η ?_
    intro η'
    simpa [eqToHom_eq_mk] using
      (Quot.sound (Completion2PathRel.whisker_assoc (f := f) (η := η') (h := h)))
  whisker_exchange := by
    intro a b c f g h i η θ
    refine Quot.inductionOn η ?_
    intro η'
    refine Quot.inductionOn θ ?_
    intro θ'
    exact Quot.sound (Completion2PathRel.whisker_exchange (η := η') (θ := θ'))
  pentagon := by
    intro a b c d e f g h i
    simpa [eqToHom_eq_mk] using
      (Quot.sound (Completion2PathRel.pentagon (f := f) (g := g) (h := h) (i := i)))
  triangle := by
    intro a b c f g
    simpa [eqToHom_eq_mk] using
      (Quot.sound (Completion2PathRel.triangle (f := f) (g := g)))

end Category
end Combinators
end LoF
end HeytingLean
