import Mathlib.Data.Finset.Basic
import HeytingLean.Noneism.ProofTheory.Completeness.KripkeFOHenkin
import HeytingLean.Noneism.ProofTheory.Quantifiers.NDHParamToVarTransport

namespace HeytingLean
namespace Noneism
namespace HenkinCompleteness
namespace InternalH

open Syntax.Henkin
open NDH

variable {σ κ : Type}

/-!
Zorn scaffolding for `HasHenkinizedFamilyBase.henkinize`.

This file isolates the remaining Henkin "avoidance" lemma into a small interface
`HasHenkinOneStepExtension`. Everything else is standard finitary Zorn plumbing.
-/

/-- A witness request is a variable/formula pair. -/
abbrev HenkinRequest (σ : Type) (κ : Type) : Type :=
  Var × FormulaH σ κ

/-- A partial witness-choice is represented as a graph `request ↦ κ`. -/
abbrev HenkinGraph (σ : Type) (κ : Type) : Type :=
  Set (HenkinRequest σ κ × κ)

namespace HenkinGraph

variable {σ κ : Type}

/-- Domain of a partial witness-choice graph. -/
def dom (G : HenkinGraph σ κ) : Set (HenkinRequest σ κ) :=
  fun r => ∃ k, (r, k) ∈ G

/-- Functional-graph property: a request is mapped to at most one parameter. -/
def Functional (G : HenkinGraph σ κ) : Prop :=
  ∀ {r : HenkinRequest σ κ} {k₁ k₂ : κ},
    (r, k₁) ∈ G → (r, k₂) ∈ G → k₁ = k₂

/-- Henkin witness schema set generated by a partial witness-choice graph. -/
def henkinAxiomSetOf (G : HenkinGraph σ κ) : Set (FormulaH σ κ) :=
  fun ψ => ∃ (x : Var) (φ : FormulaH σ κ) (k : κ),
    (((x, φ), k) : HenkinRequest σ κ × κ) ∈ G ∧ ψ = henkinAxiom x k φ

/-- The working theory `Γ ∪ axioms(G)`. -/
def theory (Γ : List (FormulaH σ κ)) (G : HenkinGraph σ κ) : Set (FormulaH σ κ) :=
  fun ψ => ψ ∈ Γ ∨ ψ ∈ henkinAxiomSetOf (σ := σ) (κ := κ) G

/-- Good partial graphs preserve consistency and non-derivability of the goal. -/
def Good {Γ : List (FormulaH σ κ)} {φ : FormulaH σ κ} (G : HenkinGraph σ κ) : Prop :=
  ConsistentH (σ := σ) (κ := κ) (theory (σ := σ) (κ := κ) Γ G) ∧
  ¬ DerivableH (σ := σ) (κ := κ) (theory (σ := σ) (κ := κ) Γ G) φ

lemma dom_insert
    (G : HenkinGraph σ κ) (r : HenkinRequest σ κ) (k : κ) :
    dom (σ := σ) (κ := κ) (Set.insert (r, k) G) = Set.insert r (dom (σ := σ) (κ := κ) G) := by
  ext r'
  constructor
  · intro hr'
    rcases hr' with ⟨k', hk'⟩
    rcases hk' with hk' | hk'
    · cases hk'
      exact Or.inl rfl
    · exact Or.inr ⟨k', hk'⟩
  · intro hr'
    rcases hr' with hr' | hr'
    · subst hr'
      exact ⟨k, Or.inl rfl⟩
    · rcases hr' with ⟨k', hk'⟩
      exact ⟨k', Or.inr hk'⟩

lemma functional_insert_of_not_mem_dom
    {G : HenkinGraph σ κ} {r : HenkinRequest σ κ} {k : κ}
    (hFun : Functional (σ := σ) (κ := κ) G)
    (hr : r ∉ dom (σ := σ) (κ := κ) G) :
    Functional (σ := σ) (κ := κ) (Set.insert (r, k) G) := by
  intro r' k₁ k₂ hk₁ hk₂
  rcases hk₁ with hk₁ | hk₁ <;> rcases hk₂ with hk₂ | hk₂
  · cases hk₁; cases hk₂; rfl
  · cases hk₁
    exact False.elim (hr ⟨k₂, hk₂⟩)
  · cases hk₂
    exact False.elim (hr ⟨k₁, hk₁⟩)
  · exact hFun hk₁ hk₂

lemma henkinAxiomSetOf_insert
    (G : HenkinGraph σ κ) (x : Var) (φ : FormulaH σ κ) (k : κ) :
    henkinAxiomSetOf (σ := σ) (κ := κ) (Set.insert (((x, φ), k)) G) =
      Set.insert (henkinAxiom x k φ) (henkinAxiomSetOf (σ := σ) (κ := κ) G) := by
  ext ψ
  constructor
  · intro h
    rcases h with ⟨x', φ', k', hk', hEq⟩
    rcases hk' with hk' | hk'
    · cases hk'
      exact Or.inl hEq
    · exact Or.inr ⟨x', φ', k', hk', hEq⟩
  · intro h
    rcases h with hEq | hOld
    · exact ⟨x, φ, k, Or.inl rfl, hEq⟩
    · rcases hOld with ⟨x', φ', k', hk', hEq⟩
      exact ⟨x', φ', k', Or.inr hk', hEq⟩

lemma theory_insert
    (Γ : List (FormulaH σ κ))
    (G : HenkinGraph σ κ) (x : Var) (φ : FormulaH σ κ) (k : κ) :
    theory (σ := σ) (κ := κ) Γ (Set.insert (((x, φ), k)) G) =
      Set.insert (henkinAxiom x k φ) (theory (σ := σ) (κ := κ) Γ G) := by
  ext ψ
  constructor
  · intro h
    rcases h with hΓ | hAx
    · exact Or.inr (Or.inl hΓ)
    ·
      have hAx' : ψ ∈ Set.insert (henkinAxiom x k φ) (henkinAxiomSetOf (σ := σ) (κ := κ) G) := by
        simpa [henkinAxiomSetOf_insert] using hAx
      rcases hAx' with hEq | hOld
      · exact Or.inl hEq
      · exact Or.inr (Or.inr hOld)
  · intro h
    rcases h with hEq | hOld
    ·
      exact Or.inr (by
        have : ψ ∈ Set.insert (henkinAxiom x k φ) (henkinAxiomSetOf (σ := σ) (κ := κ) G) :=
          Or.inl hEq
        simpa [henkinAxiomSetOf_insert] using this)
    ·
      rcases hOld with hΓ | hAx
      · exact Or.inl hΓ
      ·
        exact Or.inr (by
          have : ψ ∈ Set.insert (henkinAxiom x k φ) (henkinAxiomSetOf (σ := σ) (κ := κ) G) :=
            Or.inr hAx
          simpa [henkinAxiomSetOf_insert] using this)

lemma good_insert_iff
    {Γ : List (FormulaH σ κ)} {χ : FormulaH σ κ}
    (G : HenkinGraph σ κ) (x : Var) (φ : FormulaH σ κ) (k : κ) :
    Good (σ := σ) (κ := κ) (Γ := Γ) (φ := χ) (Set.insert (((x, φ), k)) G) ↔
      ConsistentH (σ := σ) (κ := κ)
        (Set.insert (henkinAxiom x k φ) (theory (σ := σ) (κ := κ) Γ G)) ∧
      ¬ DerivableH (σ := σ) (κ := κ)
        (Set.insert (henkinAxiom x k φ) (theory (σ := σ) (κ := κ) Γ G)) χ := by
  simp [Good, theory_insert]

lemma exists_insert_good_and_functional_iff_exists_insert_good
    {Γ : List (FormulaH σ κ)} {χ : FormulaH σ κ}
    {G : HenkinGraph σ κ} {r : HenkinRequest σ κ}
    (hFun : Functional (σ := σ) (κ := κ) G)
    (hr : r ∉ dom (σ := σ) (κ := κ) G) :
    (∃ k : κ,
      Good (σ := σ) (κ := κ) (Γ := Γ) (φ := χ) (Set.insert (r, k) G) ∧
      Functional (σ := σ) (κ := κ) (Set.insert (r, k) G)) ↔
    ∃ k : κ, Good (σ := σ) (κ := κ) (Γ := Γ) (φ := χ) (Set.insert (r, k) G) := by
  constructor
  · intro h
    rcases h with ⟨k, hGood, _hFunIns⟩
    exact ⟨k, hGood⟩
  · intro h
    rcases h with ⟨k, hGood⟩
    refine ⟨k, hGood, ?_⟩
    exact functional_insert_of_not_mem_dom (σ := σ) (κ := κ) hFun hr

lemma exists_insert_good_iff_exists_axiom_insert_good
    {Γ : List (FormulaH σ κ)} {χ : FormulaH σ κ}
    {G : HenkinGraph σ κ} (x : Var) (φ : FormulaH σ κ) :
    (∃ k : κ,
      Good (σ := σ) (κ := κ) (Γ := Γ) (φ := χ) (Set.insert (((x, φ), k)) G)) ↔
    ∃ k : κ,
      ConsistentH (σ := σ) (κ := κ)
        (Set.insert (henkinAxiom x k φ) (theory (σ := σ) (κ := κ) Γ G)) ∧
      ¬ DerivableH (σ := σ) (κ := κ)
        (Set.insert (henkinAxiom x k φ) (theory (σ := σ) (κ := κ) Γ G)) χ := by
  constructor
  · intro h
    rcases h with ⟨k, hGood⟩
    exact ⟨k, (good_insert_iff (σ := σ) (κ := κ) G x φ k).1 hGood⟩
  · intro h
    rcases h with ⟨k, hGood⟩
    exact ⟨k, (good_insert_iff (σ := σ) (κ := κ) G x φ k).2 hGood⟩

lemma exists_insert_good_and_functional_iff_exists_axiom_insert_good
    {Γ : List (FormulaH σ κ)} {χ : FormulaH σ κ}
    {G : HenkinGraph σ κ} (x : Var) (φ : FormulaH σ κ)
    (hFun : Functional (σ := σ) (κ := κ) G)
    (hr : ((x, φ) : HenkinRequest σ κ) ∉ dom (σ := σ) (κ := κ) G) :
    (∃ k : κ,
      Good (σ := σ) (κ := κ) (Γ := Γ) (φ := χ) (Set.insert (((x, φ), k)) G) ∧
      Functional (σ := σ) (κ := κ) (Set.insert (((x, φ), k)) G)) ↔
    ∃ k : κ,
      ConsistentH (σ := σ) (κ := κ)
        (Set.insert (henkinAxiom x k φ) (theory (σ := σ) (κ := κ) Γ G)) ∧
      ¬ DerivableH (σ := σ) (κ := κ)
        (Set.insert (henkinAxiom x k φ) (theory (σ := σ) (κ := κ) Γ G)) χ := by
  calc
    (∃ k : κ,
      Good (σ := σ) (κ := κ) (Γ := Γ) (φ := χ) (Set.insert (((x, φ), k)) G) ∧
      Functional (σ := σ) (κ := κ) (Set.insert (((x, φ), k)) G)) ↔
      ∃ k : κ,
        Good (σ := σ) (κ := κ) (Γ := Γ) (φ := χ) (Set.insert (((x, φ), k)) G) := by
          exact exists_insert_good_and_functional_iff_exists_insert_good
            (σ := σ) (κ := κ) (Γ := Γ) (χ := χ) (G := G)
            (r := ((x, φ) : HenkinRequest σ κ)) hFun hr
    _ ↔
      ∃ k : κ,
        ConsistentH (σ := σ) (κ := κ)
          (Set.insert (henkinAxiom x k φ) (theory (σ := σ) (κ := κ) Γ G)) ∧
        ¬ DerivableH (σ := σ) (κ := κ)
          (Set.insert (henkinAxiom x k φ) (theory (σ := σ) (κ := κ) Γ G)) χ := by
            exact exists_insert_good_iff_exists_axiom_insert_good
              (σ := σ) (κ := κ) (Γ := Γ) (χ := χ) (G := G) x φ

end HenkinGraph

open HenkinGraph

/--
One-step extension interface for building a total witness-choice function:
if a request is not yet decided, we can extend the graph while keeping `Good`.

This is the true Henkin "avoidance" obligation.
-/
class HasHenkinOneStepExtension (σ : Type) (κ : Type) : Prop where
  extend :
    ∀ {Γ : List (FormulaH σ κ)} {φ : FormulaH σ κ}
      {G : HenkinGraph σ κ},
      Functional (σ := σ) (κ := κ) G →
      Good (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) G →
      ∀ r : HenkinRequest σ κ, r ∉ dom (σ := σ) (κ := κ) G →
        ∃ k : κ,
          Good (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) (Set.insert (r, k) G) ∧
          Functional (σ := σ) (κ := κ) (Set.insert (r, k) G)

/--
Sufficient one-step obligation in normalized "schema insert" form.

This isolates the hard content of one-step extension to finding a parameter `k` such that
inserting the corresponding Henkin witness schema into the current theory preserves both consistency
and non-derivability of the target formula.
-/
class HasHenkinAxiomInsertPreservation (σ : Type) (κ : Type) : Prop where
  choose_good :
    ∀ {Γ : List (FormulaH σ κ)} {φ : FormulaH σ κ}
      {G : HenkinGraph σ κ},
      Functional (σ := σ) (κ := κ) G →
      Good (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) G →
      ∀ (x : Var) (ψ : FormulaH σ κ),
        ((x, ψ) : HenkinRequest σ κ) ∉ dom (σ := σ) (κ := κ) G →
          ∃ k : κ,
            ConsistentH (σ := σ) (κ := κ)
              (Set.insert (henkinAxiom x k ψ) (theory (σ := σ) (κ := κ) Γ G)) ∧
            ¬ DerivableH (σ := σ) (κ := κ)
              (Set.insert (henkinAxiom x k ψ) (theory (σ := σ) (κ := κ) Γ G)) φ

/--
Rescue-style one-step obligation.

For a suitable witness parameter `k`, any derivation of either `⊥` or the target `φ` from the
inserted-schema theory can be "rescued" back to a derivation from the base theory.

This packages the local contradiction shape expected from a sigma-elimination admissibility theorem
without forcing callers to prove consistency/non-derivability directly.
-/
class HasHenkinAxiomInsertRescueChoice (σ : Type) (κ : Type) : Prop where
  choose_rescue :
    ∀ {Γ : List (FormulaH σ κ)} {φ : FormulaH σ κ}
      {G : HenkinGraph σ κ},
      Functional (σ := σ) (κ := κ) G →
      Good (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) G →
      ∀ (x : Var) (ψ : FormulaH σ κ),
        ((x, ψ) : HenkinRequest σ κ) ∉ dom (σ := σ) (κ := κ) G →
          ∃ k : κ,
            (DerivableH (σ := σ) (κ := κ)
              (Set.insert (henkinAxiom x k ψ) (theory (σ := σ) (κ := κ) Γ G))
              (.bot : FormulaH σ κ) →
                DerivableH (σ := σ) (κ := κ)
                  (theory (σ := σ) (κ := κ) Γ G)
                  (.bot : FormulaH σ κ)) ∧
            (DerivableH (σ := σ) (κ := κ)
              (Set.insert (henkinAxiom x k ψ) (theory (σ := σ) (κ := κ) Γ G))
              φ →
                DerivableH (σ := σ) (κ := κ)
                  (theory (σ := σ) (κ := κ) Γ G)
                  φ)

/--
Base-theory not/imp rescue interface.

This is a stricter normalization of one-step rescue: for a chosen witness parameter `k`,
it is enough to provide base-theory rescue for the two formulas produced by the deduction
steps from inserted-schema branches:
- `¬(henkinAxiom x k ψ)` for the `⊥` branch;
- `(henkinAxiom x k ψ) → φ` for the goal branch.
-/
class HasHenkinAxiomInsertNotImpRescueChoice (σ : Type) (κ : Type) : Prop where
  choose_not_imp :
    ∀ {Γ : List (FormulaH σ κ)} {φ : FormulaH σ κ}
      {G : HenkinGraph σ κ},
      Functional (σ := σ) (κ := κ) G →
      Good (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) G →
      ∀ (x : Var) (ψ : FormulaH σ κ),
        ((x, ψ) : HenkinRequest σ κ) ∉ dom (σ := σ) (κ := κ) G →
          ∃ k : κ,
            (DerivableH (σ := σ) (κ := κ)
              (theory (σ := σ) (κ := κ) Γ G)
              (.not (henkinAxiom x k ψ) : FormulaH σ κ) →
                DerivableH (σ := σ) (κ := κ)
                  (theory (σ := σ) (κ := κ) Γ G)
                  (.bot : FormulaH σ κ)) ∧
            (DerivableH (σ := σ) (κ := κ)
              (theory (σ := σ) (κ := κ) Γ G)
              (.imp (henkinAxiom x k ψ) φ : FormulaH σ κ) →
                DerivableH (σ := σ) (κ := κ)
                  (theory (σ := σ) (κ := κ) Γ G)
                  φ)

/--
Single-step derivability interface: choose a witness parameter `k` so that the corresponding
Henkin witness schema is already derivable from the base theory.

When available, this immediately yields the not/imp rescue obligations by combining
`DerivableH`-level modus ponens / contradiction with the derived schema.
-/
class HasHenkinAxiomInsertDerivableChoice (σ : Type) (κ : Type) : Prop where
  choose_derivable :
    ∀ {Γ : List (FormulaH σ κ)} {φ : FormulaH σ κ}
      {G : HenkinGraph σ κ},
      Functional (σ := σ) (κ := κ) G →
      Good (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) G →
      ∀ (x : Var) (ψ : FormulaH σ κ),
        ((x, ψ) : HenkinRequest σ κ) ∉ dom (σ := σ) (κ := κ) G →
          ∃ k : κ,
            DerivableH (σ := σ) (κ := κ)
              (theory (σ := σ) (κ := κ) Γ G)
              (henkinAxiom x k ψ)

private lemma derivableH_notE
    {T : Set (FormulaH σ κ)} {θ : FormulaH σ κ}
    (hNot : DerivableH (σ := σ) (κ := κ) T (.not θ))
    (hθ : DerivableH (σ := σ) (κ := κ) T θ) :
    DerivableH (σ := σ) (κ := κ) T (.bot : FormulaH σ κ) := by
  rcases hNot with ⟨Γn, hΓnT, hDerNot⟩
  rcases hθ with ⟨Γa, hΓaT, hDerA⟩
  let Δ : List (FormulaH σ κ) := Γn ++ Γa
  have hDerNotΔ : NDH.Derives (σ := σ) (κ := κ) Δ (.not θ) := by
    exact NDH.Derives.wk hDerNot (by
      intro ψ hψ
      exact List.mem_append.2 (Or.inl hψ))
  have hDerAΔ : NDH.Derives (σ := σ) (κ := κ) Δ θ := by
    exact NDH.Derives.wk hDerA (by
      intro ψ hψ
      exact List.mem_append.2 (Or.inr hψ))
  have hΔT : ∀ ψ ∈ Δ, ψ ∈ T := by
    intro ψ hψ
    rcases List.mem_append.1 hψ with hψn | hψa
    · exact hΓnT ψ hψn
    · exact hΓaT ψ hψa
  exact derivableH_of_derives (σ := σ) (κ := κ) hΔT (NDH.Derives.notE hDerNotΔ hDerAΔ)

private lemma derivableH_impE
    {T : Set (FormulaH σ κ)} {θ χ : FormulaH σ κ}
    (hImp : DerivableH (σ := σ) (κ := κ) T (.imp θ χ))
    (hθ : DerivableH (σ := σ) (κ := κ) T θ) :
    DerivableH (σ := σ) (κ := κ) T χ := by
  rcases hImp with ⟨Γimp, hΓimpT, hDerImp⟩
  rcases hθ with ⟨Γa, hΓaT, hDerA⟩
  let Δ : List (FormulaH σ κ) := Γimp ++ Γa
  have hDerImpΔ : NDH.Derives (σ := σ) (κ := κ) Δ (.imp θ χ) := by
    exact NDH.Derives.wk hDerImp (by
      intro ψ hψ
      exact List.mem_append.2 (Or.inl hψ))
  have hDerAΔ : NDH.Derives (σ := σ) (κ := κ) Δ θ := by
    exact NDH.Derives.wk hDerA (by
      intro ψ hψ
      exact List.mem_append.2 (Or.inr hψ))
  have hΔT : ∀ ψ ∈ Δ, ψ ∈ T := by
    intro ψ hψ
    rcases List.mem_append.1 hψ with hψi | hψa
    · exact hΓimpT ψ hψi
    · exact hΓaT ψ hψa
  exact derivableH_of_derives (σ := σ) (κ := κ) hΔT (NDH.Derives.impE hDerImpΔ hDerAΔ)

instance (priority := 69)
    hasHenkinAxiomInsertNotImpRescueChoice_of_derivableChoice
    [HasHenkinAxiomInsertDerivableChoice (σ := σ) (κ := κ)] :
    HasHenkinAxiomInsertNotImpRescueChoice (σ := σ) (κ := κ) where
  choose_not_imp := by
    intro Γ φ G hFun hGood x ψ hr
    rcases HasHenkinAxiomInsertDerivableChoice.choose_derivable
      (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) (G := G)
      hFun hGood x ψ hr with
      ⟨k, hAxDer⟩
    refine ⟨k, ?_, ?_⟩
    · intro hNotA
      exact derivableH_notE
        (σ := σ) (κ := κ) (T := theory (σ := σ) (κ := κ) Γ G)
        (θ := henkinAxiom x k ψ) hNotA hAxDer
    · intro hImpA
      exact derivableH_impE
        (σ := σ) (κ := κ) (T := theory (σ := σ) (κ := κ) Γ G)
        (θ := henkinAxiom x k ψ) (χ := φ) hImpA hAxDer

instance (priority := 68)
    hasHenkinAxiomInsertRescueChoice_of_notImpRescueChoice
    [HasHenkinAxiomInsertNotImpRescueChoice (σ := σ) (κ := κ)] :
    HasHenkinAxiomInsertRescueChoice (σ := σ) (κ := κ) where
  choose_rescue := by
    intro Γ φ G hFun hGood x ψ hr
    rcases HasHenkinAxiomInsertNotImpRescueChoice.choose_not_imp
      (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) (G := G)
      hFun hGood x ψ hr with
      ⟨k, hNotRescue, hImpRescue⟩
    refine ⟨k, ?_, ?_⟩
    · intro hBotIns
      have hNotA :
          DerivableH (σ := σ) (κ := κ)
            (theory (σ := σ) (κ := κ) Γ G)
            (.not (henkinAxiom x k ψ) : FormulaH σ κ) :=
        LindenbaumH.derivableH_not_of_derivable_insert_bot
          (σ := σ) (κ := κ)
          (T := theory (σ := σ) (κ := κ) Γ G)
          (θ := henkinAxiom x k ψ)
          (hWeak := HasOpenWeakening.weaken (σ := σ) (κ := κ))
          hBotIns
      exact hNotRescue hNotA
    · intro hGoalIns
      have hImp :
          DerivableH (σ := σ) (κ := κ)
            (theory (σ := σ) (κ := κ) Γ G)
            (.imp (henkinAxiom x k ψ) φ : FormulaH σ κ) :=
        LindenbaumH.derivableH_imp_of_derivable_insert
          (σ := σ) (κ := κ)
          (T := theory (σ := σ) (κ := κ) Γ G)
          (θ := henkinAxiom x k ψ)
          (χ := φ)
          (hWeak := HasOpenWeakening.weaken (σ := σ) (κ := κ))
          hGoalIns
      exact hImpRescue hImp

theorem hasHenkinAxiomInsertNotImpRescueChoice_of_rescueChoice
    [HasHenkinAxiomInsertRescueChoice (σ := σ) (κ := κ)] :
    HasHenkinAxiomInsertNotImpRescueChoice (σ := σ) (κ := κ) := by
  refine ⟨?_⟩
  intro Γ φ G hFun hGood x ψ hr
  rcases HasHenkinAxiomInsertRescueChoice.choose_rescue
    (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) (G := G)
    hFun hGood x ψ hr with
    ⟨k, hBotRescue, hGoalRescue⟩
  refine ⟨k, ?_, ?_⟩
  · intro hNotA
    let T0 : Set (FormulaH σ κ) := theory (σ := σ) (κ := κ) Γ G
    let A : FormulaH σ κ := henkinAxiom x k ψ
    let TA : Set (FormulaH σ κ) := Set.insert A T0
    have hNotAIns :
        DerivableH (σ := σ) (κ := κ) TA (.not A : FormulaH σ κ) :=
      DerivableH.mono (σ := σ) (κ := κ)
        (T := T0) (U := TA) (φ := (.not A : FormulaH σ κ))
        (by intro θ hθ; exact Or.inr hθ)
        hNotA
    have hBotInsAux :
        DerivableH (σ := σ) (κ := κ) (Set.insert (.not A : FormulaH σ κ) TA)
          (.bot : FormulaH σ κ) := by
      let Δ : List (FormulaH σ κ) := [(.not A : FormulaH σ κ), A]
      have hΔ :
          ∀ θ ∈ Δ, θ ∈ Set.insert (.not A : FormulaH σ κ) TA := by
        intro θ hθ
        rcases List.mem_cons.1 hθ with hNot | hTail
        · subst hNot
          exact Or.inl rfl
        · have hA : θ = A := by simpa [Δ] using hTail
          subst hA
          exact Or.inr (Or.inl rfl)
      have hDerNot : NDH.Derives (σ := σ) (κ := κ) Δ (.not A : FormulaH σ κ) :=
        NDH.Derives.hyp (by simp [Δ])
      have hDerA : NDH.Derives (σ := σ) (κ := κ) Δ A :=
        NDH.Derives.hyp (by simp [Δ])
      have hDerBot : NDH.Derives (σ := σ) (κ := κ) Δ (.bot : FormulaH σ κ) :=
        NDH.Derives.notE hDerNot hDerA
      exact derivableH_of_derives (σ := σ) (κ := κ) hΔ hDerBot
    have hBotIns :
        DerivableH (σ := σ) (κ := κ) TA (.bot : FormulaH σ κ) :=
      LindenbaumH.derivableH_of_insert_of_derivable
        (σ := σ) (κ := κ)
        (T := TA)
        (θ := (.not A : FormulaH σ κ))
        (χ := (.bot : FormulaH σ κ))
        (hWeak := HasOpenWeakening.weaken (σ := σ) (κ := κ))
        hNotAIns hBotInsAux
    simpa [T0, A, TA] using hBotRescue hBotIns
  · intro hImpA
    let T0 : Set (FormulaH σ κ) := theory (σ := σ) (κ := κ) Γ G
    let A : FormulaH σ κ := henkinAxiom x k ψ
    let TA : Set (FormulaH σ κ) := Set.insert A T0
    have hImpAIns :
        DerivableH (σ := σ) (κ := κ) TA (.imp A φ : FormulaH σ κ) :=
      DerivableH.mono (σ := σ) (κ := κ)
        (T := T0) (U := TA) (φ := (.imp A φ : FormulaH σ κ))
        (by intro θ hθ; exact Or.inr hθ)
        hImpA
    have hGoalInsAux :
        DerivableH (σ := σ) (κ := κ) (Set.insert (.imp A φ : FormulaH σ κ) TA) φ := by
      let Δ : List (FormulaH σ κ) := [(.imp A φ : FormulaH σ κ), A]
      have hΔ :
          ∀ θ ∈ Δ, θ ∈ Set.insert (.imp A φ : FormulaH σ κ) TA := by
        intro θ hθ
        rcases List.mem_cons.1 hθ with hImp | hTail
        · subst hImp
          exact Or.inl rfl
        · have hA : θ = A := by simpa [Δ] using hTail
          subst hA
          exact Or.inr (Or.inl rfl)
      have hDerImp : NDH.Derives (σ := σ) (κ := κ) Δ (.imp A φ : FormulaH σ κ) :=
        NDH.Derives.hyp (by simp [Δ])
      have hDerA : NDH.Derives (σ := σ) (κ := κ) Δ A :=
        NDH.Derives.hyp (by simp [Δ])
      have hDerφ : NDH.Derives (σ := σ) (κ := κ) Δ φ :=
        NDH.Derives.impE hDerImp hDerA
      exact derivableH_of_derives (σ := σ) (κ := κ) hΔ hDerφ
    have hGoalIns :
        DerivableH (σ := σ) (κ := κ) TA φ :=
      LindenbaumH.derivableH_of_insert_of_derivable
        (σ := σ) (κ := κ)
        (T := TA)
        (θ := (.imp A φ : FormulaH σ κ))
        (χ := φ)
        (hWeak := HasOpenWeakening.weaken (σ := σ) (κ := κ))
        hImpAIns hGoalInsAux
    simpa [T0, A, TA] using hGoalRescue hGoalIns

theorem hasHenkinAxiomInsertRescueChoice_iff_hasHenkinAxiomInsertNotImpRescueChoice :
    HasHenkinAxiomInsertRescueChoice (σ := σ) (κ := κ) ↔
      HasHenkinAxiomInsertNotImpRescueChoice (σ := σ) (κ := κ) := by
  constructor
  · intro hRescue
    letI : HasHenkinAxiomInsertRescueChoice (σ := σ) (κ := κ) := hRescue
    exact hasHenkinAxiomInsertNotImpRescueChoice_of_rescueChoice (σ := σ) (κ := κ)
  · intro hNotImp
    letI : HasHenkinAxiomInsertNotImpRescueChoice (σ := σ) (κ := κ) := hNotImp
    infer_instance

/--
One-step-local freshness extraction for inserted-schema bad branches.

Given any derivation witness from an inserted-schema theory, extract:
- a finite list-support derivation,
- and a parameter `kFresh` that is absent from both the goal formula parameters and
  every formula occurring in that support list.

This is the direct freshness bridge used for branch-local bad-derivation analysis.
-/
lemma exists_support_with_fresh_not_mem_params_of_derivable_insert_axiom
    [DecidableEq κ]
    [HenkinCardinalBounds.HasFreshFromFinset κ]
    {Γ : List (FormulaH σ κ)} {G : HenkinGraph σ κ}
    {x : Var} {ψ χ : FormulaH σ κ} {k : κ}
    (hDer :
      DerivableH (σ := σ) (κ := κ)
        (Set.insert (henkinAxiom x k ψ) (theory (σ := σ) (κ := κ) Γ G))
        χ) :
    ∃ kFresh : κ, ∃ Δ : List (FormulaH σ κ),
      kFresh ∉ paramsFormula (σ := σ) (κ := κ) χ ∧
      (∀ θ ∈ Δ, θ ∈ Set.insert (henkinAxiom x k ψ) (theory (σ := σ) (κ := κ) Γ G)) ∧
      NDH.Derives (σ := σ) (κ := κ) Δ χ ∧
      (∀ θ ∈ Δ, kFresh ∉ paramsFormula (σ := σ) (κ := κ) θ) := by
  simpa using
    DerivableH.exists_support_with_fresh_not_mem_params
      (σ := σ) (κ := κ)
      (T := Set.insert (henkinAxiom x k ψ) (theory (σ := σ) (κ := κ) Γ G))
      (φ := χ) hDer

/--
Normalize an inserted-schema `⊥` branch into a base-theory `¬A` branch with finite support
and a fresh-parameter witness.
-/
lemma bot_branch_to_base_not_with_fresh_support
    [DecidableEq κ]
    [HenkinCardinalBounds.HasFreshFromFinset κ]
    {Γ : List (FormulaH σ κ)} {G : HenkinGraph σ κ}
    {x : Var} {ψ : FormulaH σ κ} {k : κ}
    (hBotIns :
      DerivableH (σ := σ) (κ := κ)
        (Set.insert (henkinAxiom x k ψ) (theory (σ := σ) (κ := κ) Γ G))
        (.bot : FormulaH σ κ)) :
    ∃ kFresh : κ, ∃ Δ : List (FormulaH σ κ),
      kFresh ∉ paramsFormula (σ := σ) (κ := κ) (.not (henkinAxiom x k ψ) : FormulaH σ κ) ∧
      (∀ θ ∈ Δ, θ ∈ theory (σ := σ) (κ := κ) Γ G) ∧
      NDH.Derives (σ := σ) (κ := κ) Δ (.not (henkinAxiom x k ψ) : FormulaH σ κ) ∧
      (∀ θ ∈ Δ, kFresh ∉ paramsFormula (σ := σ) (κ := κ) θ) := by
  have hNotA :
      DerivableH (σ := σ) (κ := κ)
        (theory (σ := σ) (κ := κ) Γ G)
        (.not (henkinAxiom x k ψ) : FormulaH σ κ) :=
    LindenbaumH.derivableH_not_of_derivable_insert_bot
      (σ := σ) (κ := κ)
      (T := theory (σ := σ) (κ := κ) Γ G)
      (θ := henkinAxiom x k ψ)
      (hWeak := HasOpenWeakening.weaken (σ := σ) (κ := κ))
      hBotIns
  exact DerivableH.exists_support_with_fresh_not_mem_params
    (σ := σ) (κ := κ)
    (T := theory (σ := σ) (κ := κ) Γ G)
    (φ := (.not (henkinAxiom x k ψ) : FormulaH σ κ))
    hNotA

/--
Normalize an inserted-schema goal branch into a base-theory implication branch `A → φ`
with finite support and a fresh-parameter witness.
-/
lemma goal_branch_to_base_imp_with_fresh_support
    [DecidableEq κ]
    [HenkinCardinalBounds.HasFreshFromFinset κ]
    {Γ : List (FormulaH σ κ)} {G : HenkinGraph σ κ}
    {x : Var} {ψ φ : FormulaH σ κ} {k : κ}
    (hGoalIns :
      DerivableH (σ := σ) (κ := κ)
        (Set.insert (henkinAxiom x k ψ) (theory (σ := σ) (κ := κ) Γ G))
        φ) :
    ∃ kFresh : κ, ∃ Δ : List (FormulaH σ κ),
      kFresh ∉ paramsFormula (σ := σ) (κ := κ) (.imp (henkinAxiom x k ψ) φ : FormulaH σ κ) ∧
      (∀ θ ∈ Δ, θ ∈ theory (σ := σ) (κ := κ) Γ G) ∧
      NDH.Derives (σ := σ) (κ := κ) Δ (.imp (henkinAxiom x k ψ) φ : FormulaH σ κ) ∧
      (∀ θ ∈ Δ, kFresh ∉ paramsFormula (σ := σ) (κ := κ) θ) := by
  have hImp :
      DerivableH (σ := σ) (κ := κ)
        (theory (σ := σ) (κ := κ) Γ G)
        (.imp (henkinAxiom x k ψ) φ : FormulaH σ κ) :=
    LindenbaumH.derivableH_imp_of_derivable_insert
      (σ := σ) (κ := κ)
      (T := theory (σ := σ) (κ := κ) Γ G)
      (θ := henkinAxiom x k ψ)
      (χ := φ)
      (hWeak := HasOpenWeakening.weaken (σ := σ) (κ := κ))
      hGoalIns
  exact DerivableH.exists_support_with_fresh_not_mem_params
    (σ := σ) (κ := κ)
    (T := theory (σ := σ) (κ := κ) Γ G)
    (φ := (.imp (henkinAxiom x k ψ) φ : FormulaH σ κ))
    hImp

instance (priority := 66)
    hasHenkinAxiomInsertPreservation_of_rescueChoice
    [HasHenkinAxiomInsertRescueChoice (σ := σ) (κ := κ)] :
    HasHenkinAxiomInsertPreservation (σ := σ) (κ := κ) where
  choose_good := by
    intro Γ φ G hFun hGood x ψ hr
    rcases HasHenkinAxiomInsertRescueChoice.choose_rescue
      (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) (G := G)
      hFun hGood x ψ hr with
      ⟨k, hBotRescue, hGoalRescue⟩
    refine ⟨k, ?_⟩
    constructor
    · intro hBotIns
      exact hGood.1 (hBotRescue hBotIns)
    · intro hDerIns
      exact hGood.2 (hGoalRescue hDerIns)

/--
`HasHenkinAxiomInsertPreservation` can be viewed as a degenerate rescue-choice provider:
the inserted-schema bad branches are contradictory, so the rescue implications hold vacuously.
-/
theorem hasHenkinAxiomInsertRescueChoice_of_preservation
    [HasHenkinAxiomInsertPreservation (σ := σ) (κ := κ)] :
    HasHenkinAxiomInsertRescueChoice (σ := σ) (κ := κ) := by
  refine ⟨?_⟩
  intro Γ φ G hFun hGood x ψ hr
  rcases HasHenkinAxiomInsertPreservation.choose_good
    (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) (G := G)
    hFun hGood x ψ hr with ⟨k, hConsIns, hNoDerIns⟩
  refine ⟨k, ?_, ?_⟩
  · intro hBotIns
    exact False.elim (hConsIns hBotIns)
  · intro hDerIns
    exact False.elim (hNoDerIns hDerIns)

theorem hasHenkinAxiomInsertRescueChoice_iff_hasHenkinAxiomInsertPreservation :
    HasHenkinAxiomInsertRescueChoice (σ := σ) (κ := κ) ↔
      HasHenkinAxiomInsertPreservation (σ := σ) (κ := κ) := by
  constructor
  · intro hRescue
    letI : HasHenkinAxiomInsertRescueChoice (σ := σ) (κ := κ) := hRescue
    infer_instance
  · intro hPres
    letI : HasHenkinAxiomInsertPreservation (σ := σ) (κ := κ) := hPres
    exact hasHenkinAxiomInsertRescueChoice_of_preservation (σ := σ) (κ := κ)

instance (priority := 65)
    hasHenkinOneStepExtension_of_axiomInsertPreservation
    [HasHenkinAxiomInsertPreservation (σ := σ) (κ := κ)] :
    HasHenkinOneStepExtension (σ := σ) (κ := κ) where
  extend := by
    intro Γ φ G hFun hGood r hr
    rcases r with ⟨x, ψ⟩
    rcases HasHenkinAxiomInsertPreservation.choose_good
      (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) (G := G)
      hFun hGood x ψ hr with ⟨k, hAxiomGood⟩
    have hGoodIns :
        ∃ k' : κ,
          Good (σ := σ) (κ := κ) (Γ := Γ) (φ := φ)
            (Set.insert (((x, ψ), k') : HenkinRequest σ κ × κ) G) := by
      exact (HenkinGraph.exists_insert_good_iff_exists_axiom_insert_good
        (σ := σ) (κ := κ) (Γ := Γ) (χ := φ) (G := G) x ψ).2 ⟨k, hAxiomGood⟩
    exact (HenkinGraph.exists_insert_good_and_functional_iff_exists_insert_good
      (σ := σ) (κ := κ) (Γ := Γ) (χ := φ) (G := G)
      (r := ((x, ψ) : HenkinRequest σ κ)) hFun hr).2 hGoodIns

namespace HenkinizeZorn

open scoped Classical

variable {σ κ : Type}

/-- Family of good functional graphs, ordered by subset. -/
def Family
    (Γ : List (FormulaH σ κ)) (φ : FormulaH σ κ) : Set (HenkinGraph σ κ) :=
  {G | Functional (σ := σ) (κ := κ) G ∧ Good (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) G}

lemma chain_directedOn
    {α : Type} {c : Set (Set α)}
    (hc : IsChain (· ⊆ ·) c) :
    DirectedOn (· ⊆ ·) c := by
  intro a ha b hb
  rcases hc.total ha hb with hab | hba
  · exact ⟨b, hb, hab, subset_rfl⟩
  · exact ⟨a, ha, subset_rfl, hba⟩

lemma sUnion_functional_of_chain
    {Γ : List (FormulaH σ κ)} {φ : FormulaH σ κ}
    {c : Set (HenkinGraph σ κ)}
    (hc : IsChain (· ⊆ ·) c)
    (hcF : c ⊆ Family (σ := σ) (κ := κ) (Γ := Γ) (φ := φ)) :
    Functional (σ := σ) (κ := κ) (Set.sUnion c) := by
  intro r k₁ k₂ hk₁ hk₂
  rcases hk₁ with ⟨G₁, hG₁c, hk₁⟩
  rcases hk₂ with ⟨G₂, hG₂c, hk₂⟩
  rcases hc.total hG₁c hG₂c with h12 | h21
  · exact (hcF hG₂c).1 (h12 hk₁) hk₂
  · exact (hcF hG₁c).1 hk₁ (h21 hk₂)

lemma theory_mono
    {Γ : List (FormulaH σ κ)} {G H : HenkinGraph σ κ}
    (hGH : G ⊆ H) :
    theory (σ := σ) (κ := κ) Γ G ⊆ theory (σ := σ) (κ := κ) Γ H := by
  intro ψ hψ
  rcases hψ with hΓ | hAx
  · exact Or.inl hΓ
  ·
    rcases hAx with ⟨x, φ, k, hkG, rfl⟩
    exact Or.inr ⟨x, φ, k, hGH hkG, rfl⟩

lemma sUnion_good_of_chain
    {Γ : List (FormulaH σ κ)} {φ : FormulaH σ κ}
    {c : Set (HenkinGraph σ κ)}
    (hc : IsChain (· ⊆ ·) c)
    (hcne : c.Nonempty)
    (hcF : c ⊆ Family (σ := σ) (κ := κ) (Γ := Γ) (φ := φ)) :
    Good (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) (Set.sUnion c) := by
  classical
  have hdir : DirectedOn (· ⊆ ·) c := chain_directedOn (hc := hc)

  -- Helper: from a finite premise list in the union theory, extract a finite set of graph-pairs
  -- that witnesses all schema premises.
  have collectPairs :
      ∀ (Δ : List (FormulaH σ κ)),
        (∀ ψ ∈ Δ, ψ ∈ theory (σ := σ) (κ := κ) Γ (Set.sUnion c)) →
          ∃ P : Finset (HenkinRequest σ κ × κ),
            (∀ p ∈ P, p ∈ Set.sUnion c) ∧
            (∀ ψ ∈ Δ,
              ψ ∈ Γ ∨
                ∃ (x : Var) (φ' : FormulaH σ κ) (k : κ),
                  (((x, φ'), k) : HenkinRequest σ κ × κ) ∈ P ∧
                  ψ = henkinAxiom x k φ') := by
    intro Δ hΔ
    induction Δ with
    | nil =>
        refine ⟨∅, ?_, ?_⟩
        · intro p hp; cases hp
        · intro ψ hψ; cases hψ
    | cons ψ Δ ih =>
        have hψT : ψ ∈ theory (σ := σ) (κ := κ) Γ (Set.sUnion c) :=
          hΔ ψ (by simp)
        have hΔ' :
            ∀ θ ∈ Δ, θ ∈ theory (σ := σ) (κ := κ) Γ (Set.sUnion c) := by
          intro θ hθ
          exact hΔ θ (by simp [hθ])
        rcases ih hΔ' with ⟨P, hPUnion, hPrem⟩
        rcases hψT with hψΓ | hψAx
        ·
          refine ⟨P, hPUnion, ?_⟩
          intro θ hθ
          rcases List.mem_cons.1 hθ with rfl | hθ'
          · exact Or.inl hψΓ
          · exact hPrem θ hθ'
        ·
          rcases hψAx with ⟨x, φ', k, hkUnion, hEq⟩
          refine ⟨insert (((x, φ'), k) : HenkinRequest σ κ × κ) P, ?_, ?_⟩
          · intro p hp
            rcases Finset.mem_insert.1 hp with rfl | hp'
            · exact hkUnion
            · exact hPUnion p hp'
          · intro θ hθ
            rcases List.mem_cons.1 hθ with hθ0 | hθ'
            · subst hθ0
              refine Or.inr ⟨x, φ', k, ?_, hEq⟩
              simp
            ·
              rcases hPrem θ hθ' with hθΓ | hθAx
              · exact Or.inl hθΓ
              ·
                rcases hθAx with ⟨x', φ'', k', hkP, hθEq⟩
                refine Or.inr ⟨x', φ'', k', ?_, hθEq⟩
                simp [hkP]

  constructor
  · intro hBot
    rcases hBot with ⟨Δ, hΔT, hDerBot⟩
    rcases collectPairs Δ hΔT with ⟨P, hPUnion, hPrem⟩
    have hPSub : (P : Set (HenkinRequest σ κ × κ)) ⊆ Set.sUnion c := by
      intro p hp; exact hPUnion p hp
    rcases DirectedOn.exists_mem_subset_of_finite_of_subset_sUnion
      (α := HenkinRequest σ κ × κ)
      (c := c) hcne hdir (s := (P : Set (HenkinRequest σ κ × κ)))
      P.finite_toSet hPSub with ⟨G, hGc, hPG⟩
    have hΔG : ∀ ψ ∈ Δ, ψ ∈ theory (σ := σ) (κ := κ) Γ G := by
      intro ψ hψ
      rcases hPrem ψ hψ with hψΓ | hψAx
      · exact Or.inl hψΓ
      ·
        rcases hψAx with ⟨x, φ', k, hkP, hEq⟩
        refine Or.inr ⟨x, φ', k, hPG hkP, hEq⟩
    have hDerBotG :
        DerivableH (σ := σ) (κ := κ) (theory (σ := σ) (κ := κ) Γ G)
          (.bot : FormulaH σ κ) :=
      ⟨Δ, hΔG, hDerBot⟩
    exact (hcF hGc).2.1 hDerBotG
  · intro hDerφ
    rcases hDerφ with ⟨Δ, hΔT, hDerφ⟩
    rcases collectPairs Δ hΔT with ⟨P, hPUnion, hPrem⟩
    have hPSub : (P : Set (HenkinRequest σ κ × κ)) ⊆ Set.sUnion c := by
      intro p hp; exact hPUnion p hp
    rcases DirectedOn.exists_mem_subset_of_finite_of_subset_sUnion
      (α := HenkinRequest σ κ × κ)
      (c := c) hcne hdir (s := (P : Set (HenkinRequest σ κ × κ)))
      P.finite_toSet hPSub with ⟨G, hGc, hPG⟩
    have hΔG : ∀ ψ ∈ Δ, ψ ∈ theory (σ := σ) (κ := κ) Γ G := by
      intro ψ hψ
      rcases hPrem ψ hψ with hψΓ | hψAx
      · exact Or.inl hψΓ
      ·
        rcases hψAx with ⟨x, φ', k, hkP, hEq⟩
        refine Or.inr ⟨x, φ', k, hPG hkP, hEq⟩
    have hDerφG :
        DerivableH (σ := σ) (κ := κ) (theory (σ := σ) (κ := κ) Γ G) φ :=
      ⟨Δ, hΔG, hDerφ⟩
    exact (hcF hGc).2.2 hDerφG

theorem exists_maximal_graph
    {Γ : List (FormulaH σ κ)} {φ : FormulaH σ κ}
    (hBase :
      ∃ G : HenkinGraph σ κ,
        Functional (σ := σ) (κ := κ) G ∧
        Good (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) G) :
    ∃ G : HenkinGraph σ κ,
      G ∈ Family (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) ∧
      Maximal (· ∈ Family (σ := σ) (κ := κ) (Γ := Γ) (φ := φ)) G := by
  rcases hBase with ⟨G0, hFun0, hGood0⟩
  have hmem : G0 ∈ Family (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) := ⟨hFun0, hGood0⟩
  have H :
      ∀ c ⊆ Family (σ := σ) (κ := κ) (Γ := Γ) (φ := φ),
        IsChain (· ⊆ ·) c →
          c.Nonempty →
            ∃ ub ∈ Family (σ := σ) (κ := κ) (Γ := Γ) (φ := φ), ∀ s ∈ c, s ⊆ ub := by
    intro c hcF hc hcne
    refine ⟨Set.sUnion c, ?_, ?_⟩
    · refine ⟨?_, ?_⟩
      · exact sUnion_functional_of_chain (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) hc hcF
      · exact sUnion_good_of_chain (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) hc hcne hcF
    · intro s hs
      exact Set.subset_sUnion_of_mem hs
  rcases zorn_subset_nonempty (Family (σ := σ) (κ := κ) (Γ := Γ) (φ := φ)) H G0 hmem with
    ⟨G, _hG0G, hMax⟩
  exact ⟨G, hMax.prop, hMax⟩

theorem henkinize_of_oneStep
    [HasOpenWeakening σ κ]
    [HasHenkinOneStepExtension (σ := σ) (κ := κ)]
    {Γ : List (FormulaH σ κ)} {φ : FormulaH σ κ}
    (hNotDer : ¬ NDH.Derives (σ := σ) (κ := κ) Γ φ) :
    ∃ choose : Var → FormulaH σ κ → κ,
      ConsistentH (σ := σ) (κ := κ)
        (fun ψ => ψ ∈ Γ ∨ ψ ∈ henkinAxiomSet (σ := σ) (κ := κ) choose) ∧
      ¬ DerivableH (σ := σ) (κ := κ)
        (fun ψ => ψ ∈ Γ ∨ ψ ∈ henkinAxiomSet (σ := σ) (κ := κ) choose) φ := by
  classical
  -- Base partial graph: empty choice, so no axioms.
  let G0 : HenkinGraph σ κ := ∅
  have hFun0 : Functional (σ := σ) (κ := κ) G0 := by
    intro r k₁ k₂ hk₁
    cases hk₁
  have hGood0 : Good (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) G0 := by
    constructor
    ·
      have hBaseCons :
          ConsistentH (σ := σ) (κ := κ) (fun ψ : FormulaH σ κ => ψ ∈ Γ) :=
        HasSequentFamilyBase.base_consistent (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) hNotDer
      have hTheory0 : theory (σ := σ) (κ := κ) Γ G0 = (fun ψ : FormulaH σ κ => ψ ∈ Γ) := by
        ext ψ
        constructor
        · intro h
          rcases h with hΓ | hAx
          · exact hΓ
          ·
            rcases hAx with ⟨x, φ', k, hk, _hEq⟩
            cases hk
        · intro hΓ
          exact Or.inl hΓ
      simpa [hTheory0] using hBaseCons
    ·
      have hBaseNot :
          ¬ DerivableH (σ := σ) (κ := κ) (fun ψ : FormulaH σ κ => ψ ∈ Γ) φ :=
        HasSequentFamilyBase.base_notDerivable (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) hNotDer
      have hTheory0 : theory (σ := σ) (κ := κ) Γ G0 = (fun ψ : FormulaH σ κ => ψ ∈ Γ) := by
        ext ψ
        constructor
        · intro h
          rcases h with hΓ | hAx
          · exact hΓ
          ·
            rcases hAx with ⟨x, φ', k, hk, _hEq⟩
            cases hk
        · intro hΓ
          exact Or.inl hΓ
      simpa [hTheory0] using hBaseNot
  have hBase :
      ∃ G : HenkinGraph σ κ,
        Functional (σ := σ) (κ := κ) G ∧
        Good (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) G := by
    exact ⟨G0, hFun0, hGood0⟩
  rcases exists_maximal_graph (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) hBase with
    ⟨G, hGFam, hGMax⟩
  have hFunG : Functional (σ := σ) (κ := κ) G := hGFam.1
  have hGoodG : Good (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) G := hGFam.2

  have hTotal : ∀ r : HenkinRequest σ κ, r ∈ dom (σ := σ) (κ := κ) G := by
    intro r
    by_contra hr
    rcases HasHenkinOneStepExtension.extend
      (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) (G := G) hFunG hGoodG r hr with
      ⟨k, hGoodIns, hFunIns⟩
    have hInsMem :
        Set.insert (r, k) G ∈ Family (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) := ⟨hFunIns, hGoodIns⟩
    have hGSub : G ⊆ Set.insert (r, k) G := Set.subset_insert _ _
    have hEq : G = Set.insert (r, k) G :=
      Maximal.eq_of_subset hGMax hInsMem hGSub
    have : (r, k) ∈ G := by
      have hmem : (r, k) ∈ Set.insert (r, k) G := Or.inl rfl
      -- Rewrite only once (avoid simp-loops on `G = insert ... G`).
      rw [hEq]
      exact hmem
    exact hr ⟨k, this⟩

  have hExistsUnique :
      ∀ r : HenkinRequest σ κ, ∃! k : κ, (r, k) ∈ G := by
    intro r
    rcases hTotal r with ⟨k, hk⟩
    refine ⟨k, hk, ?_⟩
    intro k' hk'
    exact (hFunG (r := r) (k₁ := k) (k₂ := k') hk hk').symm

  let chooseReq : HenkinRequest σ κ → κ :=
    fun r => Classical.choose (ExistsUnique.exists (hExistsUnique r))
  have hChooseReq_mem :
      ∀ r : HenkinRequest σ κ, (r, chooseReq r) ∈ G := by
    intro r
    exact Classical.choose_spec (ExistsUnique.exists (hExistsUnique r))

  let choose : Var → FormulaH σ κ → κ := fun x φ => chooseReq (x, φ)

  have hAxiomsEq :
      henkinAxiomSet (σ := σ) (κ := κ) choose =
        henkinAxiomSetOf (σ := σ) (κ := κ) G := by
    ext ψ
    constructor
    · rintro ⟨x, φ', rfl⟩
      refine ⟨x, φ', choose x φ', hChooseReq_mem (x, φ'), rfl⟩
    · rintro ⟨x, φ', k, hkG, rfl⟩
      have hk' : (((x, φ') : HenkinRequest σ κ), choose x φ') ∈ G := by
        simpa using hChooseReq_mem (x, φ')
      have hkEq : k = choose x φ' := by
        exact hFunG (r := (x, φ')) (k₁ := k) (k₂ := choose x φ') hkG hk'
      subst hkEq
      exact ⟨x, φ', rfl⟩

  refine ⟨choose, ?_, ?_⟩
  · simpa [HenkinGraph.Good, HenkinGraph.theory, hAxiomsEq] using hGoodG.1
  · simpa [HenkinGraph.Good, HenkinGraph.theory, hAxiomsEq] using hGoodG.2

end HenkinizeZorn

instance (priority := 60)
    hasHenkinizedFamilyBase_of_oneStep
    [HasOpenWeakening σ κ]
    [HasHenkinOneStepExtension (σ := σ) (κ := κ)] :
    HasHenkinizedFamilyBase σ κ where
  henkinize := by
    intro Γ φ hNotDer
    exact HenkinizeZorn.henkinize_of_oneStep (σ := σ) (κ := κ) (Γ := Γ) (φ := φ) hNotDer

end InternalH
end HenkinCompleteness
end Noneism
end HeytingLean
