import HeytingLean.Tests.Bridges.ComputableTestKit
import HeytingLean.Tests.Bridges.OmegaComputable
import HeytingLean.Meta.LeanTT0.ExportCAB

/-!
# `diamond_topology_export` - Verified Heyting Algebra to C

Exports the Diamond lattice operations to C with full provenance tracking.

## Output Files

- `diamond.c`      - C implementation (pure functions, no malloc)
- `diamond.h`      - C ABI header
- `driver.c`       - Test driver with all operations
- `expected.txt`   - Expected output (computed in Lean)
- `provenance.json`- Theorem names guaranteeing correctness

## Provenance Chain

Each exported function has a corresponding Lean theorem proving its correctness:
- `diamond_le` ← `by decide` over all 16 input pairs
- `diamond_inf` ← `SemilatticeInf.inf_le_left/right`
- `diamond_sup` ← `SemilatticeSup.le_sup_left/right`
- `diamond_himp` ← `HeytingAlgebra.le_himp_iff`
- `diamond_compl` ← `compl' x = himp' x ⊥`

The C code is a direct transcription of the pattern-matching definitions,
which Lean has verified satisfy the algebraic laws.
-/

namespace HeytingLean
namespace CLI
namespace DiamondTopologyExport

open HeytingLean.Tests.Bridges.ComputableTestKit

/-! ## Configuration -/

structure Config where
  outDir : String := "dist/diamond_topology_export"
  generateCAB : Bool := true
deriving Repr

private def usage : String :=
  String.intercalate "\n"
    [ "diamond_topology_export"
    , ""
    , "Exports verified Diamond lattice operations to C with CAB certificate."
    , ""
    , "Output files:"
    , "  - diamond.c         (C source, pure functions)"
    , "  - diamond.h         (C header for FFI)"
    , "  - driver.c          (test driver)"
    , "  - expected.txt      (expected stdout)"
    , "  - provenance.json   (theorem provenance chain)"
    , "  - certificate.json  (CAB certificate with Merkle root)"
    , ""
    , "Flags:"
    , "  --out <dir>    output directory"
    , "  --no-cab       skip CAB certificate generation"
    , "  --help         show this message"
    ]

/-! ## C Code Generation -/

/-- Diamond element encoding: bot=0, left=1, right=2, top=3 -/
private def diamondToInt : Diamond → Int
  | .bot => 0
  | .left => 1
  | .right => 2
  | .top => 3

private def intToDiamondName : Int → String
  | 0 => "DIAMOND_BOT"
  | 1 => "DIAMOND_LEFT"
  | 2 => "DIAMOND_RIGHT"
  | 3 => "DIAMOND_TOP"
  | _ => "DIAMOND_INVALID"

/-- Generate the C header file -/
private def headerSource : String :=
  String.intercalate "\n"
    [ "/* Diamond Lattice - Verified Heyting Algebra"
    , " * Generated by HeytingLean (diamond_topology_export)"
    , " * "
    , " * This C code is a direct transcription of Lean definitions"
    , " * verified to satisfy Heyting algebra laws."
    , " */"
    , "#pragma once"
    , ""
    , "#ifdef __cplusplus"
    , "extern \"C\" {"
    , "#endif"
    , ""
    , "/* Diamond lattice elements */"
    , "typedef int Diamond;"
    , "#define DIAMOND_BOT   0"
    , "#define DIAMOND_LEFT  1"
    , "#define DIAMOND_RIGHT 2"
    , "#define DIAMOND_TOP   3"
    , ""
    , "/* Lattice operations (verified in Lean) */"
    , "int diamond_le(Diamond x, Diamond y);      /* x ≤ y */"
    , "Diamond diamond_inf(Diamond x, Diamond y); /* x ⊓ y (meet) */"
    , "Diamond diamond_sup(Diamond x, Diamond y); /* x ⊔ y (join) */"
    , ""
    , "/* Heyting operations (verified in Lean) */"
    , "Diamond diamond_himp(Diamond x, Diamond y);  /* x ⇨ y (implication) */"
    , "Diamond diamond_compl(Diamond x);            /* ¬x (pseudo-complement) */"
    , ""
    , "/* Nucleus operations (identity on Diamond) */"
    , "Diamond diamond_closure(Diamond x);  /* R(x) = x (discrete nucleus) */"
    , "int diamond_is_fixed(Diamond x);     /* R(x) == x (always true) */"
    , ""
    , "/* Verification helpers */"
    , "int diamond_is_valid_nucleus(void);  /* Returns 1 (only id is valid) */"
    , "const char* diamond_element_name(Diamond x);"
    , ""
    , "#ifdef __cplusplus"
    , "}"
    , "#endif"
    , ""
    ]

/-- Generate lookup table for le -/
private def leTable : String :=
  let rows := [Diamond.bot, .left, .right, .top].map fun x =>
    let cols := [Diamond.bot, .left, .right, .top].map fun y =>
      if Diamond.le' x y then "1" else "0"
    "  {" ++ String.intercalate ", " cols ++ "}"
  "static const int le_table[4][4] = {\n" ++ String.intercalate ",\n" rows ++ "\n};"

/-- Generate lookup table for inf -/
private def infTable : String :=
  let rows := [Diamond.bot, .left, .right, .top].map fun x =>
    let cols := [Diamond.bot, .left, .right, .top].map fun y =>
      toString (diamondToInt (Diamond.inf' x y))
    "  {" ++ String.intercalate ", " cols ++ "}"
  "static const Diamond inf_table[4][4] = {\n" ++ String.intercalate ",\n" rows ++ "\n};"

/-- Generate lookup table for sup -/
private def supTable : String :=
  let rows := [Diamond.bot, .left, .right, .top].map fun x =>
    let cols := [Diamond.bot, .left, .right, .top].map fun y =>
      toString (diamondToInt (Diamond.sup' x y))
    "  {" ++ String.intercalate ", " cols ++ "}"
  "static const Diamond sup_table[4][4] = {\n" ++ String.intercalate ",\n" rows ++ "\n};"

/-- Generate lookup table for himp -/
private def himpTable : String :=
  let rows := [Diamond.bot, .left, .right, .top].map fun x =>
    let cols := [Diamond.bot, .left, .right, .top].map fun y =>
      toString (diamondToInt (Diamond.himp' x y))
    "  {" ++ String.intercalate ", " cols ++ "}"
  "static const Diamond himp_table[4][4] = {\n" ++ String.intercalate ",\n" rows ++ "\n};"

/-- Generate lookup table for compl -/
private def complTable : String :=
  let vals := [Diamond.bot, .left, .right, .top].map fun x =>
    toString (diamondToInt (Diamond.compl' x))
  "static const Diamond compl_table[4] = {" ++ String.intercalate ", " vals ++ "};"

/-- Generate the C source file -/
private def sourceCode : String :=
  String.intercalate "\n"
    [ "/* Diamond Lattice - Verified Heyting Algebra"
    , " * Generated by HeytingLean (diamond_topology_export)"
    , " *"
    , " * PROVENANCE: Each lookup table is a direct transcription of"
    , " * pattern-matching definitions verified in Lean against the"
    , " * Heyting algebra axioms. See provenance.json for theorem names."
    , " */"
    , ""
    , "#include \"diamond.h\""
    , ""
    , "/* Lookup tables - computed in Lean, verified by type checker */"
    , ""
    , leTable
    , ""
    , infTable
    , ""
    , supTable
    , ""
    , himpTable
    , ""
    , complTable
    , ""
    , "static const char* element_names[4] = {"
    , "  \"bot\", \"left\", \"right\", \"top\""
    , "};"
    , ""
    , "/* --- Lattice Operations --- */"
    , ""
    , "int diamond_le(Diamond x, Diamond y) {"
    , "  if (x < 0 || x > 3 || y < 0 || y > 3) return 0;"
    , "  return le_table[x][y];"
    , "}"
    , ""
    , "Diamond diamond_inf(Diamond x, Diamond y) {"
    , "  if (x < 0 || x > 3 || y < 0 || y > 3) return DIAMOND_BOT;"
    , "  return inf_table[x][y];"
    , "}"
    , ""
    , "Diamond diamond_sup(Diamond x, Diamond y) {"
    , "  if (x < 0 || x > 3 || y < 0 || y > 3) return DIAMOND_TOP;"
    , "  return sup_table[x][y];"
    , "}"
    , ""
    , "/* --- Heyting Operations --- */"
    , ""
    , "Diamond diamond_himp(Diamond x, Diamond y) {"
    , "  if (x < 0 || x > 3 || y < 0 || y > 3) return DIAMOND_TOP;"
    , "  return himp_table[x][y];"
    , "}"
    , ""
    , "Diamond diamond_compl(Diamond x) {"
    , "  if (x < 0 || x > 3) return DIAMOND_TOP;"
    , "  return compl_table[x];"
    , "}"
    , ""
    , "/* --- Nucleus Operations --- */"
    , ""
    , "Diamond diamond_closure(Diamond x) {"
    , "  /* Discrete nucleus: R(x) = x */"
    , "  return x;"
    , "}"
    , ""
    , "int diamond_is_fixed(Diamond x) {"
    , "  /* All elements are fixed under identity nucleus */"
    , "  return (x >= 0 && x <= 3) ? 1 : 0;"
    , "}"
    , ""
    , "int diamond_is_valid_nucleus(void) {"
    , "  /* Diamond admits ONLY the identity nucleus */"
    , "  /* Proven in Lean: OmegaComputable.countValidNuclei = 1 */"
    , "  return 1;"
    , "}"
    , ""
    , "const char* diamond_element_name(Diamond x) {"
    , "  if (x < 0 || x > 3) return \"invalid\";"
    , "  return element_names[x];"
    , "}"
    , ""
    ]

/-- Generate the test driver -/
private def driverSource : String :=
  String.intercalate "\n"
    [ "#include <stdio.h>"
    , "#include \"diamond.h\""
    , ""
    , "int main(void) {"
    , "  printf(\"=== Diamond Lattice Verified Operations ===\\n\");"
    , "  printf(\"\\n--- Lattice Order (le) ---\\n\");"
    , "  printf(\"bot <= top: %d\\n\", diamond_le(DIAMOND_BOT, DIAMOND_TOP));"
    , "  printf(\"left <= top: %d\\n\", diamond_le(DIAMOND_LEFT, DIAMOND_TOP));"
    , "  printf(\"left <= right: %d\\n\", diamond_le(DIAMOND_LEFT, DIAMOND_RIGHT));"
    , "  printf(\"top <= bot: %d\\n\", diamond_le(DIAMOND_TOP, DIAMOND_BOT));"
    , ""
    , "  printf(\"\\n--- Meet (inf) ---\\n\");"
    , "  printf(\"left ⊓ right = %s\\n\", diamond_element_name(diamond_inf(DIAMOND_LEFT, DIAMOND_RIGHT)));"
    , "  printf(\"left ⊓ top = %s\\n\", diamond_element_name(diamond_inf(DIAMOND_LEFT, DIAMOND_TOP)));"
    , "  printf(\"top ⊓ top = %s\\n\", diamond_element_name(diamond_inf(DIAMOND_TOP, DIAMOND_TOP)));"
    , ""
    , "  printf(\"\\n--- Join (sup) ---\\n\");"
    , "  printf(\"left ⊔ right = %s\\n\", diamond_element_name(diamond_sup(DIAMOND_LEFT, DIAMOND_RIGHT)));"
    , "  printf(\"bot ⊔ left = %s\\n\", diamond_element_name(diamond_sup(DIAMOND_BOT, DIAMOND_LEFT)));"
    , ""
    , "  printf(\"\\n--- Heyting Implication (himp) ---\\n\");"
    , "  printf(\"left ⇨ right = %s\\n\", diamond_element_name(diamond_himp(DIAMOND_LEFT, DIAMOND_RIGHT)));"
    , "  printf(\"right ⇨ left = %s\\n\", diamond_element_name(diamond_himp(DIAMOND_RIGHT, DIAMOND_LEFT)));"
    , "  printf(\"bot ⇨ top = %s\\n\", diamond_element_name(diamond_himp(DIAMOND_BOT, DIAMOND_TOP)));"
    , "  printf(\"top ⇨ bot = %s\\n\", diamond_element_name(diamond_himp(DIAMOND_TOP, DIAMOND_BOT)));"
    , ""
    , "  printf(\"\\n--- Complement (compl) ---\\n\");"
    , "  printf(\"¬bot = %s\\n\", diamond_element_name(diamond_compl(DIAMOND_BOT)));"
    , "  printf(\"¬left = %s\\n\", diamond_element_name(diamond_compl(DIAMOND_LEFT)));"
    , "  printf(\"¬right = %s\\n\", diamond_element_name(diamond_compl(DIAMOND_RIGHT)));"
    , "  printf(\"¬top = %s\\n\", diamond_element_name(diamond_compl(DIAMOND_TOP)));"
    , ""
    , "  printf(\"\\n--- Nucleus (closure) ---\\n\");"
    , "  printf(\"R(left) = %s\\n\", diamond_element_name(diamond_closure(DIAMOND_LEFT)));"
    , "  printf(\"is_fixed(left) = %d\\n\", diamond_is_fixed(DIAMOND_LEFT));"
    , "  printf(\"is_valid_nucleus = %d\\n\", diamond_is_valid_nucleus());"
    , ""
    , "  printf(\"\\n=== All tests passed ===\\n\");"
    , "  return 0;"
    , "}"
    , ""
    ]

/-- Generate expected output (computed in Lean) -/
private def expectedOutput : String :=
  String.intercalate "\n"
    [ "=== Diamond Lattice Verified Operations ==="
    , ""
    , "--- Lattice Order (le) ---"
    , s!"bot <= top: {if Diamond.le' .bot .top then 1 else 0}"
    , s!"left <= top: {if Diamond.le' .left .top then 1 else 0}"
    , s!"left <= right: {if Diamond.le' .left .right then 1 else 0}"
    , s!"top <= bot: {if Diamond.le' .top .bot then 1 else 0}"
    , ""
    , "--- Meet (inf) ---"
    , s!"left ⊓ right = {match Diamond.inf' .left .right with | .bot => "bot" | .left => "left" | .right => "right" | .top => "top"}"
    , s!"left ⊓ top = {match Diamond.inf' .left .top with | .bot => "bot" | .left => "left" | .right => "right" | .top => "top"}"
    , s!"top ⊓ top = {match Diamond.inf' .top .top with | .bot => "bot" | .left => "left" | .right => "right" | .top => "top"}"
    , ""
    , "--- Join (sup) ---"
    , s!"left ⊔ right = {match Diamond.sup' .left .right with | .bot => "bot" | .left => "left" | .right => "right" | .top => "top"}"
    , s!"bot ⊔ left = {match Diamond.sup' .bot .left with | .bot => "bot" | .left => "left" | .right => "right" | .top => "top"}"
    , ""
    , "--- Heyting Implication (himp) ---"
    , s!"left ⇨ right = {match Diamond.himp' .left .right with | .bot => "bot" | .left => "left" | .right => "right" | .top => "top"}"
    , s!"right ⇨ left = {match Diamond.himp' .right .left with | .bot => "bot" | .left => "left" | .right => "right" | .top => "top"}"
    , s!"bot ⇨ top = {match Diamond.himp' .bot .top with | .bot => "bot" | .left => "left" | .right => "right" | .top => "top"}"
    , s!"top ⇨ bot = {match Diamond.himp' .top .bot with | .bot => "bot" | .left => "left" | .right => "right" | .top => "top"}"
    , ""
    , "--- Complement (compl) ---"
    , s!"¬bot = {match Diamond.compl' .bot with | .bot => "bot" | .left => "left" | .right => "right" | .top => "top"}"
    , s!"¬left = {match Diamond.compl' .left with | .bot => "bot" | .left => "left" | .right => "right" | .top => "top"}"
    , s!"¬right = {match Diamond.compl' .right with | .bot => "bot" | .left => "left" | .right => "right" | .top => "top"}"
    , s!"¬top = {match Diamond.compl' .top with | .bot => "bot" | .left => "left" | .right => "right" | .top => "top"}"
    , ""
    , "--- Nucleus (closure) ---"
    , "R(left) = left"
    , "is_fixed(left) = 1"
    , "is_valid_nucleus = 1"
    , ""
    , "=== All tests passed ==="
    , ""
    ]

/-- Generate provenance JSON -/
private def provenanceJson : String :=
  String.intercalate "\n"
    [ "{"
    , "  \"generator\": \"HeytingLean.CLI.DiamondTopologyExport\","
    , "  \"lean_module\": \"HeytingLean.Tests.Bridges.ComputableTestKit\","
    , "  \"algebraic_structure\": \"HeytingAlgebra\","
    , "  \"carrier\": \"Diamond (4-element lattice)\","
    , "  \"theorems\": {"
    , "    \"lattice_order\": {"
    , "      \"le_refl\": \"by decide\","
    , "      \"le_trans\": \"by decide\","
    , "      \"le_antisymm\": \"by decide\""
    , "    },"
    , "    \"semilattice_inf\": {"
    , "      \"inf_le_left\": \"by decide\","
    , "      \"inf_le_right\": \"by decide\","
    , "      \"le_inf\": \"by decide\""
    , "    },"
    , "    \"semilattice_sup\": {"
    , "      \"le_sup_left\": \"by decide\","
    , "      \"le_sup_right\": \"by decide\","
    , "      \"sup_le\": \"by decide\""
    , "    },"
    , "    \"heyting_algebra\": {"
    , "      \"le_himp_iff\": \"by decide\","
    , "      \"himp_bot\": \"by decide\""
    , "    },"
    , "    \"nucleus_uniqueness\": {"
    , "      \"theorem\": \"OmegaComputable.countValidNuclei = 1\","
    , "      \"proof\": \"Computational enumeration of all 4 inflationary candidates\""
    , "    }"
    , "  },"
    , "  \"computational_method\": \"Lookup tables transcribed from Lean pattern matching\","
    , "  \"verification\": \"All table entries computed in Lean kernel, verified by type checker\""
    , "}"
    ]

/-! ## CLI Main -/

private partial def parseArgs (args : List String) (cfg : Config := {}) : IO (Config × Bool) :=
  match args with
  | [] => pure (cfg, false)
  | "--" :: rest => parseArgs rest cfg
  | "--help" :: _ => pure (cfg, true)
  | "--out" :: dir :: rest => parseArgs rest { cfg with outDir := dir }
  | "--no-cab" :: rest => parseArgs rest { cfg with generateCAB := false }
  | "--cab" :: rest => parseArgs rest { cfg with generateCAB := true }
  | x :: _ => throw <| IO.userError s!"unknown arg: {x} (try --help)"

private def resolveOutDir (dir : String) : IO System.FilePath := do
  if dir.startsWith "/" then
    return System.FilePath.mk dir
  let cwd ← IO.currentDir
  let base :=
    if cwd.fileName == some "lean" then
      cwd.parent.getD cwd
    else
      cwd
  return base / dir

private def writeFile (path : System.FilePath) (contents : String) : IO Unit := do
  let some parent := path.parent
    | throw <| IO.userError s!"could not compute parent directory for {path}"
  IO.FS.createDirAll parent
  IO.FS.writeFile path contents

def main (argv : List String) : IO UInt32 := do
  try
    let (cfg, showHelp) ← parseArgs argv
    if showHelp then
      IO.println usage
      return (0 : UInt32)

    let outDir ← resolveOutDir cfg.outDir

    let diamondCPath := outDir / "diamond.c"
    let diamondHPath := outDir / "diamond.h"
    let driverCPath := outDir / "driver.c"
    let expectedPath := outDir / "expected.txt"
    let provenancePath := outDir / "provenance.json"

    writeFile diamondHPath headerSource
    writeFile diamondCPath sourceCode
    writeFile driverCPath driverSource
    writeFile expectedPath expectedOutput
    writeFile provenancePath provenanceJson

    IO.println s!"[diamond_topology_export] wrote {diamondHPath}"
    IO.println s!"[diamond_topology_export] wrote {diamondCPath}"
    IO.println s!"[diamond_topology_export] wrote {driverCPath}"
    IO.println s!"[diamond_topology_export] wrote {expectedPath}"
    IO.println s!"[diamond_topology_export] wrote {provenancePath}"

    -- Generate CAB certificate if enabled
    if cfg.generateCAB then
      let artifacts : List HeytingLean.Meta.LeanTT0.ExportCAB.Artifact := [
        { name := "diamond.h", content := headerSource },
        { name := "diamond.c", content := sourceCode },
        { name := "driver.c", content := driverSource },
        { name := "expected.txt", content := expectedOutput },
        { name := "provenance.json", content := provenanceJson }
      ]
      let theorems := [
        "Diamond.le_refl",
        "Diamond.le_trans",
        "Diamond.le_antisymm",
        "Diamond.inf_le_left",
        "Diamond.inf_le_right",
        "Diamond.le_inf",
        "Diamond.le_sup_left",
        "Diamond.le_sup_right",
        "Diamond.sup_le",
        "Diamond.le_himp_iff",
        "Diamond.himp_bot",
        "OmegaComputable.countValidNuclei"
      ]
      let leanModules := [
        "HeytingLean.Tests.Bridges.ComputableTestKit",
        "HeytingLean.Tests.Bridges.OmegaComputable"
      ]
      let certificate := HeytingLean.Meta.LeanTT0.ExportCAB.generateCertificate
        "diamond"
        artifacts
        theorems
        leanModules
        "Verified Diamond Heyting algebra operations exported to C"
      let certPath := outDir / "certificate.json"
      writeFile certPath (Lean.Json.pretty certificate)
      IO.println s!"[diamond_topology_export] wrote {certPath}"

    IO.println ""
    IO.println "To build and test:"
    IO.println s!"  cd {outDir}"
    IO.println "  cc -o driver driver.c diamond.c"
    IO.println "  ./driver"
    IO.println "  diff <(./driver) expected.txt && echo 'VERIFIED OK'"
    if cfg.generateCAB then
      IO.println ""
      IO.println "To verify CAB certificate:"
      IO.println s!"  lake exe cab_verify_export {outDir}/certificate.json"

    return (0 : UInt32)
  catch e =>
    IO.eprintln s!"[diamond_topology_export] error: {e}"
    return (1 : UInt32)

end DiamondTopologyExport
end CLI
end HeytingLean

def main (args : List String) : IO UInt32 :=
  HeytingLean.CLI.DiamondTopologyExport.main args
