import HeytingLean.C.Emit
import HeytingLean.LambdaIR.Add1EndToEnd
import HeytingLean.LambdaIR.Add2EndToEnd
import HeytingLean.LambdaIR.Compile
import HeytingLean.MiniC.Semantics
import HeytingLean.MiniC.ToC

/-!
# `lambda_kernel_export` (Kernel Bundle v0)

Emits a small, *verified* LambdaIR→MiniC→C kernel slice as plain C source suitable for FFI:

- `kernel.c`      (function definitions; no `main`)
- `kernel.h`      (C ABI header)
- `driver.c`      (tiny test driver `main`)
- `expected.txt`  (expected stdout from driver)

This is intentionally small (nat→nat fragments only) to keep the extracted C in the
integer-only `HeytingLean.C` subset that already has a verified compiler path from MiniC.
-/

namespace HeytingLean
namespace CLI
namespace LambdaKernelExport

open HeytingLean
open HeytingLean.C
open HeytingLean.C.Emit
open HeytingLean.Certified
open HeytingLean.LambdaIR
open HeytingLean.LambdaIR.Add1EndToEnd
open HeytingLean.LambdaIR.Add1MiniCProof
open HeytingLean.LambdaIR.Add2EndToEnd
open HeytingLean.LambdaIR.Add2MiniCProof
open HeytingLean.LambdaIR.CertifiedCompile
open HeytingLean.MiniC

structure Config where
  outDir : String := "dist/lambda_kernel_export"
deriving Repr

private def usage : String :=
  String.intercalate "\n"
    [ "lambda_kernel_export"
    , ""
    , "Emits:"
    , "  - kernel.c        (C source, no main)"
    , "  - kernel.h        (C header for FFI)"
    , "  - driver.c        (tiny test main)"
    , "  - expected.txt    (expected stdout)"
    , "  - minic.repr.txt  (debug repr of the MiniC kernel)"
    , ""
    , "Flags:"
    , "  --out <dir>    output directory (relative to repo root unless absolute)"
    , "  --help         show this message"
    ]

private partial def parseArgs (args : List String) (cfg : Config := {}) : IO (Config × Bool) :=
  match args with
  | [] => pure (cfg, false)
  | "--" :: rest => parseArgs rest cfg
  | "--help" :: _ => pure (cfg, true)
  | "--out" :: dir :: rest => parseArgs rest { cfg with outDir := dir }
  | x :: _ => throw <| IO.userError s!"unknown arg: {x} (try --help)"

private def resolveOutDir (dir : String) : IO System.FilePath := do
  if dir.startsWith "/" then
    return System.FilePath.mk dir

  let cwd ← IO.currentDir
  let base :=
    if cwd.fileName == some "lean" then
      cwd.parent.getD cwd
    else
      cwd
  return base / dir

private def writeFile (path : System.FilePath) (contents : String) : IO Unit := do
  let some parent := path.parent
    | throw <| IO.userError s!"could not compute parent directory for {path}"
  IO.FS.createDirAll parent
  IO.FS.writeFile path contents

private def headerSource (funs : List CFun) : String :=
  let protos :=
    funs.map (fun f =>
      let params :=
        if f.params.isEmpty then
          "void"
        else
          String.intercalate ", " (f.params.map (fun p => s!"long long {p}"))
      s!"long long {f.name}({params});")
  String.intercalate "\n"
    ([ "#pragma once"
     , ""
     , "#ifdef __cplusplus"
     , "extern \"C\" {"
     , "#endif"
     , ""
     ] ++ protos ++
     [ ""
     , "#ifdef __cplusplus"
     , "}"
     , "#endif"
     , ""
     ])

private def driverSource (arg1 x2 y2 : Int) : String :=
  String.intercalate "\n"
    [ "#include <stdio.h>"
    , "#include \"kernel.h\""
    , ""
    , "int main(void) {"
    , s!"  printf(\"%lld\\n\", heyting_add1({arg1}));"
    , s!"  printf(\"%lld\\n\", heyting_add2({x2}, {y2}));"
    , "  return 0;"
    , "}"
    , ""
    ]

def main (argv : List String) : IO UInt32 := do
  try
    let (cfg, showHelp) ← parseArgs argv
    if showHelp then
      IO.println usage
      return (0 : UInt32)

    let outDir ← resolveOutDir cfg.outDir
    let kernelCPath := outDir / "kernel.c"
    let kernelHPath := outDir / "kernel.h"
    let driverCPath := outDir / "driver.c"
    let expectedPath := outDir / "expected.txt"
    let minicPath := outDir / "minic.repr.txt"

    -- Compile a tiny certified LambdaIR nat→nat fragment to MiniC, then to tiny-C.
    let add1Minic :=
      (compileNat1Fun (funName := "heyting_add1") (paramName := "x") (t := termAdd1IR)
          termAdd1_isNatFun).val
    let add2Minic :=
      (compileNat2Fun (funName := "heyting_add2") (t := termAdd2IR)
          termAdd2_isNat2Fun).val
    let funsMinic : List MiniC.Fun := [add1Minic, add2Minic]
    let funsC : List CFun := funsMinic.map MiniC.ToC.compileFun

    -- Expected output, computed at the Lean level.
    let demoArg : Nat := 41
    let demoX2 : Nat := 20
    let demoY2 : Nat := 22
    let expected1 : Nat := leanAdd1 demoArg
    let expected2 : Nat := leanAdd2 demoX2 demoY2

    let cHeader :=
      String.intercalate "\n"
        [ "/* Generated by HeytingLean (lambda_kernel_export)"
        , "   Kernel slice: LambdaIR nat→nat fragment (verified at IR level)."
        , "*/"
        , ""
        , "#include \"kernel.h\""
        , ""
        ]
    let cSource := cHeader ++ Emit.funDefs funsC ++ "\n"

    writeFile kernelCPath cSource
    writeFile kernelHPath (headerSource funsC)
    writeFile driverCPath (driverSource (Int.ofNat demoArg) (Int.ofNat demoX2) (Int.ofNat demoY2))
    writeFile expectedPath (String.intercalate "\n" [toString expected1, toString expected2] ++ "\n")
    writeFile minicPath (reprStr funsMinic ++ "\n")

    IO.println s!"[lambda_kernel_export] wrote {kernelCPath}"
    IO.println s!"[lambda_kernel_export] wrote {kernelHPath}"
    IO.println s!"[lambda_kernel_export] wrote {driverCPath}"
    IO.println s!"[lambda_kernel_export] wrote {expectedPath}"
    return (0 : UInt32)
  catch e =>
    IO.eprintln s!"[lambda_kernel_export] error: {e}"
    return (1 : UInt32)

end LambdaKernelExport
end CLI
end HeytingLean

def main (args : List String) : IO UInt32 :=
  HeytingLean.CLI.LambdaKernelExport.main args
