import HeytingLean.Core.Nucleus
import HeytingLean.Bridge.NoCoincidence.Basic.Property

namespace HeytingLean.Bridge.NoCoincidence.Nucleus

open HeytingLean

/-- Circuit properties form the lattice on which the no-coincidence nuclei act. -/
abbrev CircuitProp (n : ℕ) := Basic.RevCircuit n → Prop

/-- Closure by a structural focus predicate. The nucleus enlarges a property by adding every
circuit selected by the focus lens. -/
def closureByFocus (focus : CircuitProp n) : Core.Nucleus (CircuitProp n) where
  R := fun P C => P C ∨ focus C
  extensive := by
    intro P C hPC
    exact Or.inl hPC
  idempotent := by
    intro P
    funext C
    apply propext
    constructor
    · intro h
      rcases h with h | h
      · exact h
      · exact Or.inr h
    · intro h
      rcases h with h | h
      · exact Or.inl (Or.inl h)
      · exact Or.inr h
  meet_preserving := by
    intro P Q
    funext C
    apply propext
    constructor
    · intro h
      rcases h with ⟨hP, hQ⟩ | hF
      · exact ⟨Or.inl hP, Or.inl hQ⟩
      · exact ⟨Or.inr hF, Or.inr hF⟩
    · intro h
      rcases h with ⟨hP, hQ⟩
      rcases hP with hP | hF
      · rcases hQ with hQ | hF
        · exact Or.inl ⟨hP, hQ⟩
        · exact Or.inr hF
      · exact Or.inr hF

/-- A named nucleus for CNCC reasoning. The core closure operator is always an existing
`HeytingLean.Core.Nucleus`; the extra fields only record the structural lens. -/
structure CircuitNucleus (n : ℕ) where
  adviceTag : String
  focus : CircuitProp n

/-- Every circuit nucleus in this lane is concretely the closure generated by its focus lens. -/
def CircuitNucleus.toNucleus (R : CircuitNucleus n) : Core.Nucleus (CircuitProp n) :=
  closureByFocus R.focus

/-- Build a circuit nucleus from a structural lens. -/
def mkFocusNucleus (tag : String) (focus : CircuitProp n) : CircuitNucleus n where
  adviceTag := tag
  focus := focus

/-- A circuit is structurally explained by a nucleus when it lies in the focus lens selected by
the advice string. -/
def CircuitNucleus.explains (R : CircuitNucleus n) (C : Basic.RevCircuit n) : Prop :=
  R.focus C

theorem explains_iff_focus (R : CircuitNucleus n) (C : Basic.RevCircuit n) :
    R.explains C ↔ R.focus C := Iff.rfl

theorem fixed_property_iff_contains_focus (R : CircuitNucleus n) (P : CircuitProp n) :
    P ∈ R.toNucleus.fixedPoints ↔ ∀ C, R.focus C → P C := by
  constructor
  · intro hFixed C hFocus
    have hEq : R.toNucleus.R P = P := (Core.Nucleus.mem_fixedPoints _ _).1 hFixed
    have : R.toNucleus.R P C := Or.inr hFocus
    simpa [hEq] using this
  · intro hContain
    change R.toNucleus.R P = P
    funext C
    apply propext
    constructor
    · intro h
      rcases h with hP | hFocus
      · exact hP
      · exact hContain C hFocus
    · intro hP
      exact Or.inl hP

/-- Small circuits form one canonical structural lens. -/
def smallCircuit (n : ℕ) : CircuitProp n :=
  fun C => C.size ≤ 1

/-- Involutive circuits form a second canonical lens. -/
def involutiveCircuit (n : ℕ) : CircuitProp n :=
  fun C => ∀ x, C.eval (C.eval x) = x

end HeytingLean.Bridge.NoCoincidence.Nucleus
