import HeytingLean.Compilation.CBackend.LayoutCodegen
import HeytingLean.Compilation.CUTLASSBackend.TemplateCodegen
import HeytingLean.Compilation.Codegen.ProofManifest
import HeytingLean.Compilation.LambdaIR.Layout
import Mathlib.Data.List.Basic

/-!
# Unified code generator (scaffold)

Single entry point for emitting either:
- Plain C layout helpers, and/or
- CUTLASS/CuTe-flavored C++ layout aliases.

This is intentionally conservative: it produces deterministic text artifacts and defers the
“typed tensor IR → verified low-level kernels” integration to later work.
-/

namespace HeytingLean
namespace Compilation
namespace Codegen

open HeytingLean.Compilation.LambdaIR

inductive Backend
  | PlainC
  | CUTLASS
  | Hybrid
  deriving Repr, DecidableEq

structure CodegenOptions where
  backend : Backend
  moduleName : String
  emitCertificates : Bool := true
  staticLayouts : Bool := true
  deriving Repr, DecidableEq

structure GeneratedCode where
  cHeader : Option String
  cSource : Option String
  cppHeader : Option String
  cppSource : Option String
  proofManifest : String
  deriving Repr

/-! Render a compact summary of a layout-annotated expression. -/
private def renderExprSummary (expr : AnnotatedExpr) : String :=
  let exprText :=
    match expr.expr with
    | LExpr.var v => s!"var({v})"
    | LExpr.lam x _body _e => s!"lam({x})"
    | LExpr.app _ _ => "app"
    | LExpr.lit n => s!"lit({n})"
    | LExpr.tensorAlloc _ => "tensorAlloc"
    | LExpr.tensorIndex _ _ => "tensorIndex"
    | LExpr.tensorStore _ _ _ => "tensorStore"
    | LExpr.layoutCompose _ _ => "layoutCompose"
    | LExpr.layoutCoalesce _ => "layoutCoalesce"
  let certCount := expr.certificates.length
  s!"/* expr: {exprText}, certificates: {certCount} */"

private def renderLayoutSummary (name : String) (layout : LayoutAnnotation) : String :=
  s!"/* layout {name}: rank={layout.rank}, static={layout.isStatic}, size={layout.size} */"

/-- Generate a C implementation from the layout-aware IR. -/
def genCImplementation (moduleName : String) (exprs : List AnnotatedExpr)
    (layouts : List (String × LayoutAnnotation)) : String :=
  let header := s!"/* Generated by HeytingLean (C) — module: {moduleName} */\n"
  let stats := s!"/* IR exprs: {exprs.length}, layouts: {layouts.length} */\n"
  let exprSection :=
    exprs.map (fun e => renderExprSummary e) |>.toString
  let layoutSection :=
    layouts.map (fun (n, l) => renderLayoutSummary n l) |>.toString
  header ++ stats ++ "/* expr summaries */\n" ++ exprSection ++ "\n/* layout summaries */\n" ++ layoutSection ++ "\n"

/-! Render a simple CuTe-style placeholder kernel for layout entries. -/
private def renderCutlassKernel (moduleName : String) (name : String) (layout : LayoutAnnotation) : String :=
  let nameSafe := if name.isEmpty then "kernel" else name
  "__global__ void " ++ nameSafe ++ "_" ++ moduleName ++
  "(const float* input, float* output) {\n" ++
  "  // rank=" ++ toString layout.rank ++ ", static=" ++ toString layout.isStatic ++
  ", size=" ++ toString layout.size ++ "\n" ++
  "  // Layout-aware kernel body is intentionally abstract in this scaffold.\n" ++
  "  (void)input; (void)output;\n" ++
  "}\n"

/-- Generate a CUTLASS `.cu` kernel section from the layout-aware IR. -/
def genCUTLASSKernels (moduleName : String) (exprs : List AnnotatedExpr)
    (layouts : List (String × LayoutAnnotation)) : String :=
  let header := s!"/* Generated by HeytingLean (CUTLASS) — module: {moduleName} */\n"
  let stats := s!"/* IR exprs: {exprs.length}, layouts: {layouts.length} */\n"
  let kernels := layouts.map (fun (n, l) => renderCutlassKernel moduleName n l)
  header ++ stats ++ String.intercalate "\n" kernels

/-- Main code generation entry point. -/
def generateCode (opts : CodegenOptions)
    (irModule : List AnnotatedExpr)
    (layouts : List (String × LayoutAnnotation))
    (certs : List LayoutCertificate) : IO GeneratedCode := do
  let proofManifest :=
    if opts.emitCertificates then
      proofManifestJson opts.moduleName certs
    else
      proofManifestJson opts.moduleName []

  match opts.backend with
  | .PlainC =>
      let cHeader := CBackend.genCFile opts.moduleName layouts certs
      let cSource := genCImplementation opts.moduleName irModule layouts
      return { cHeader := some cHeader, cSource := some cSource
               cppHeader := none, cppSource := none, proofManifest }
  | .CUTLASS =>
      let cppHeader := CUTLASSBackend.genCUTLASSHeader opts.moduleName layouts certs
      let cppSource := genCUTLASSKernels opts.moduleName irModule layouts
      return { cHeader := none, cSource := none
               cppHeader := some cppHeader, cppSource := some cppSource, proofManifest }
  | .Hybrid =>
      let cHeader := CBackend.genCFile opts.moduleName layouts certs
      let cSource := genCImplementation opts.moduleName irModule layouts
      let cppHeader := CUTLASSBackend.genCUTLASSHeader opts.moduleName layouts certs
      let cppSource := genCUTLASSKernels opts.moduleName irModule layouts
      return { cHeader := some cHeader, cSource := some cSource
               cppHeader := some cppHeader, cppSource := some cppSource, proofManifest }

end Codegen
end Compilation
end HeytingLean
