import HeytingLean.LoF.ICC.Soundness

namespace HeytingLean
namespace LoF
namespace ICC

/--
`legacyYChain f n` is the explicit bounded unfolding spine generated by the
local interoperability rule for `legacyY` when the seed `f` is already in
normal form.

This file does not claim unrestricted-`Y` soundness. It isolates what we can
prove operationally:

- the unrestricted fragment is executable
- `legacyY · legacyY` exposes a bounded expanding reduction prefix on a closed seed
- stronger normalization / coherence claims remain outside the proved surface

Coherence / logical consistency for unrestricted `Y` remain open.
-/
def legacyYChain (f : Term) : Nat → Term
  | 0 => .app legacyY f
  | n + 1 => .app f (legacyYChain f n)

@[simp] theorem legacyYChain_zero (f : Term) :
    legacyYChain f 0 = .app legacyY f := rfl

@[simp] theorem legacyYChain_succ (f : Term) (n : Nat) :
    legacyYChain f (n + 1) = .app f (legacyYChain f n) := rfl

theorem closed_legacyYChain {f : Term} (hf : Term.Closed f) :
    ∀ n, Term.Closed (legacyYChain f n)
  | 0 => by
      simpa [legacyYChain, Term.Closed, Term.closedAbove] using And.intro closed_legacyY hf
  | n + 1 => by
      simpa [legacyYChain, Term.Closed, Term.closedAbove] using
        And.intro hf (closed_legacyYChain hf n)

@[simp] theorem containsLegacyYShim_legacyYChain (f : Term) :
    ∀ n, containsLegacyYShim (legacyYChain f n) = true
  | 0 => by
      simp [legacyYChain, containsLegacyYShim, containsLegacyYShim_legacyY]
  | n + 1 => by
      simp [legacyYChain, containsLegacyYShim, containsLegacyYShim_legacyYChain f n]

theorem not_yFree_legacyYChain (f : Term) (n : Nat) :
    ¬ YFree (legacyYChain f n) := by
  simp [YFree, isYFree, containsLegacyYShim_legacyYChain]

@[simp] theorem step?_legacyYChain_zero (f : Term) :
    step? (legacyYChain f 0) = some (legacyYChain f 1) := by
  simp [legacyYChain, step?, legacyY]

def legacyYSelfChain : Nat → Term
  | 0 => .app legacyY legacyY
  | n + 1 => .app legacyY (legacyYSelfChain n)

@[simp] theorem legacyYSelfChain_zero :
    legacyYSelfChain 0 = .app legacyY legacyY := rfl

@[simp] theorem legacyYSelfChain_succ (n : Nat) :
    legacyYSelfChain (n + 1) = .app legacyY (legacyYSelfChain n) := rfl

@[simp] theorem closed_legacyYSelfChain : ∀ n, Term.Closed (legacyYSelfChain n)
  | 0 => by
      simp [legacyYSelfChain, Term.Closed, Term.closedAbove, closed_legacyY]
  | n + 1 => by
      simpa [legacyYSelfChain, Term.Closed, Term.closedAbove] using
        And.intro closed_legacyY (closed_legacyYSelfChain n)

@[simp] theorem containsLegacyYShim_legacyYSelfChain (n : Nat) :
    containsLegacyYShim (legacyYSelfChain n) = true := by
  cases n <;> simp [legacyYSelfChain, containsLegacyYShim, containsLegacyYShim_legacyY]

theorem not_yFree_legacyYSelfChain (n : Nat) : ¬ YFree (legacyYSelfChain n) := by
  simp [YFree, isYFree, containsLegacyYShim_legacyYSelfChain]

def legacyYOrbit0 : Term := legacyYSelfChain 0
def legacyYOrbit1 : Term := legacyYSelfChain 1
def legacyYOrbit2 : Term := .app legacyYOrbit0 legacyYOrbit1
def legacyYOrbit3 : Term := .app legacyYOrbit1 legacyYOrbit1
def legacyYOrbit4 : Term := .app legacyYOrbit2 legacyYOrbit1

@[simp] theorem step?_legacyYOrbit0 :
    step? legacyYOrbit0 = some legacyYOrbit1 := by
  simp [legacyYOrbit0, legacyYOrbit1, legacyYSelfChain, step?, legacyY]

@[simp] theorem step?_legacyYOrbit1 :
    step? legacyYOrbit1 = some legacyYOrbit2 := by
  simp [legacyYOrbit1, legacyYOrbit2, legacyYOrbit0, legacyYSelfChain, step?, legacyY]

@[simp] theorem step?_legacyYOrbit2 :
    step? legacyYOrbit2 = some legacyYOrbit3 := by
  simp [legacyYOrbit2, legacyYOrbit3, legacyYOrbit0, legacyYOrbit1, legacyYSelfChain, step?, legacyY]

@[simp] theorem step?_legacyYOrbit3 :
    step? legacyYOrbit3 = some legacyYOrbit4 := by
  simp [legacyYOrbit3, legacyYOrbit4, legacyYOrbit2, legacyYOrbit1, legacyYOrbit0,
    legacyYSelfChain, step?, legacyY]

theorem reduceFuel_legacyYOrbit0 :
    reduceFuel 0 legacyYOrbit0 = legacyYOrbit0 := by
  simp [reduceFuel, legacyYOrbit0]

theorem reduceFuel_legacyYOrbit1 :
    reduceFuel 1 legacyYOrbit0 = legacyYOrbit1 := by
  native_decide

theorem reduceFuel_legacyYOrbit2 :
    reduceFuel 2 legacyYOrbit0 = legacyYOrbit2 := by
  native_decide

theorem reduceFuel_legacyYOrbit3 :
    reduceFuel 3 legacyYOrbit0 = legacyYOrbit3 := by
  native_decide

theorem reduceFuel_legacyYOrbit4 :
    reduceFuel 4 legacyYOrbit0 = legacyYOrbit4 := by
  native_decide

theorem legacyYOrbit_size_growth_01 :
    Term.size legacyYOrbit0 < Term.size legacyYOrbit1 := by
  native_decide

theorem legacyYOrbit_size_growth_12 :
    Term.size legacyYOrbit1 < Term.size legacyYOrbit2 := by
  native_decide

theorem legacyYOrbit_size_growth_23 :
    Term.size legacyYOrbit2 < Term.size legacyYOrbit3 := by
  native_decide

theorem legacyYOrbit_size_growth_34 :
    Term.size legacyYOrbit3 < Term.size legacyYOrbit4 := by
  native_decide

/--
The simple `legacyYSelfChain` spine stops matching the actual global orbit after
the first unrestricted step. This is the concrete blocker that prevents us from
promoting the bounded prefix into the naive `legacyYSelfChain` invariant.
-/
theorem legacyYSelfChain_two_ne_legacyYOrbit2 :
    legacyYSelfChain 2 ≠ legacyYOrbit2 := by
  native_decide

/--
`legacyYOrbit n` is the actual operational orbit generated by repeatedly stepping
the closed seed `legacyY · legacyY` on the current evaluator.

Unlike the naive `legacyYSelfChain`, this recurrence matches the real orbit
after the first unrestricted step.
-/
def legacyYOrbit : Nat → Term
  | 0 => legacyYOrbit0
  | 1 => legacyYOrbit1
  | n + 2 => .app (legacyYOrbit n) legacyYOrbit1

@[simp] theorem legacyYOrbit_zero :
    legacyYOrbit 0 = legacyYOrbit0 := rfl

@[simp] theorem legacyYOrbit_one :
    legacyYOrbit 1 = legacyYOrbit1 := rfl

@[simp] theorem legacyYOrbit_succ_succ (n : Nat) :
    legacyYOrbit (n + 2) = .app (legacyYOrbit n) legacyYOrbit1 := rfl

@[simp] theorem legacyYOrbit_two :
    legacyYOrbit 2 = legacyYOrbit2 := by
  simp [legacyYOrbit, legacyYOrbit2]

@[simp] theorem legacyYOrbit_three :
    legacyYOrbit 3 = legacyYOrbit3 := by
  simp [legacyYOrbit, legacyYOrbit3]

@[simp] theorem legacyYOrbit_four :
    legacyYOrbit 4 = legacyYOrbit4 := by
  simp [legacyYOrbit, legacyYOrbit4, legacyYOrbit2]

@[simp] theorem closed_legacyYOrbit : ∀ n, Term.Closed (legacyYOrbit n)
  | 0 => by simpa [legacyYOrbit] using closed_legacyYSelfChain 0
  | 1 => by simpa [legacyYOrbit] using closed_legacyYSelfChain 1
  | n + 2 => by
      simpa [legacyYOrbit, Term.Closed, Term.closedAbove] using
        And.intro (closed_legacyYOrbit n) (closed_legacyYOrbit 1)

@[simp] theorem containsLegacyYShim_legacyYOrbit (n : Nat) :
    containsLegacyYShim (legacyYOrbit n) = true := by
  cases n with
  | zero =>
      simpa [legacyYOrbit] using containsLegacyYShim_legacyYSelfChain 0
  | succ n =>
      cases n with
      | zero =>
          simpa [legacyYOrbit] using containsLegacyYShim_legacyYSelfChain 1
      | succ n =>
          simp [legacyYOrbit, containsLegacyYShim, containsLegacyYShim_legacyYOrbit n]

theorem not_yFree_legacyYOrbit (n : Nat) : ¬ YFree (legacyYOrbit n) := by
  simp [YFree, isYFree, containsLegacyYShim_legacyYOrbit]

theorem legacyYOrbit_isApp (n : Nat) : ∃ fn arg, legacyYOrbit n = .app fn arg := by
  cases n with
  | zero =>
      exact ⟨legacyY, legacyY, by simp [legacyYOrbit, legacyYOrbit0, legacyYSelfChain]⟩
  | succ n =>
      cases n with
      | zero =>
          exact ⟨legacyY, legacyYOrbit0, by
            simp [legacyYOrbit, legacyYOrbit0, legacyYOrbit1, legacyYSelfChain]⟩
      | succ n =>
          exact ⟨legacyYOrbit n, legacyYOrbit1, by simp [legacyYOrbit]⟩

@[simp] theorem step?_legacyYOrbit : ∀ n, step? (legacyYOrbit n) = some (legacyYOrbit (n + 1))
  | 0 => by simp [legacyYOrbit, step?_legacyYOrbit0]
  | 1 => by simp [legacyYOrbit, legacyYOrbit2, step?_legacyYOrbit1]
  | n + 2 => by
      rcases legacyYOrbit_isApp n with ⟨fn, arg, hEq⟩
      have hStepFn : step? (.app fn arg) = some (legacyYOrbit (n + 1)) := by
        simpa [hEq] using step?_legacyYOrbit n
      rw [legacyYOrbit_succ_succ, hEq]
      simp [step?, hStepFn, legacyYOrbit]

theorem legacyYOrbit_never_normal (n : Nat) :
    step? (legacyYOrbit n) ≠ none := by
  rw [step?_legacyYOrbit n]
  simp

theorem legacyYOrbit_size_growth : ∀ n, Term.size (legacyYOrbit n) < Term.size (legacyYOrbit (n + 1))
  | 0 => by simpa [legacyYOrbit] using legacyYOrbit_size_growth_01
  | 1 => by simpa [legacyYOrbit] using legacyYOrbit_size_growth_12
  | n + 2 => by
      have ih := legacyYOrbit_size_growth n
      calc
        Term.size (legacyYOrbit (n + 2))
            = Term.size (legacyYOrbit n) + (Term.size legacyYOrbit1 + 1) := by
                rw [legacyYOrbit_succ_succ]
                simp [Term.size, Nat.add_assoc, Nat.add_comm]
        _ < Term.size (legacyYOrbit (n + 1)) + (Term.size legacyYOrbit1 + 1) := by
              exact Nat.add_lt_add_right ih (Term.size legacyYOrbit1 + 1)
        _ = Term.size (legacyYOrbit (n + 3)) := by
              rw [show n + 3 = (n + 1) + 2 by omega]
              rw [legacyYOrbit_succ_succ]
              simp [Term.size, Nat.add_assoc, Nat.add_comm]

/--
`UnrestrictedYRefutation` packages the terminal negative theorem we can now
prove about unrestricted `Y` on the current evaluator: the closed seed
`legacyY · legacyY` generates an explicit infinite operational orbit and thus
does not strongly normalize on this surface.
-/
structure UnrestrictedYRefutation where
  seedClosed : Term.Closed legacyYOrbit0
  seedNotYFree : ¬ YFree legacyYOrbit0
  stepSucc : ∀ n, step? (legacyYOrbit n) = some (legacyYOrbit (n + 1))
  sizeGrowth : ∀ n, Term.size (legacyYOrbit n) < Term.size (legacyYOrbit (n + 1))
  naiveSelfChainBreaks : legacyYSelfChain 2 ≠ legacyYOrbit2

/--
Terminal verdict for unrestricted `Y` on the current ICC evaluator surface.

- `proved`: a genuine positive closure theorem was obtained
- `refuted`: the current evaluator admits an explicit infinite unrestricted-`Y`
  orbit, so strong normalization on this surface is false
-/
inductive UnrestrictedYVerdict where
  | proved
  | refuted (witness : UnrestrictedYRefutation)

def unrestrictedYRefutation : UnrestrictedYRefutation where
  seedClosed := by simpa using closed_legacyYSelfChain 0
  seedNotYFree := by simpa [legacyYOrbit0] using not_yFree_legacyYSelfChain 0
  stepSucc := step?_legacyYOrbit
  sizeGrowth := legacyYOrbit_size_growth
  naiveSelfChainBreaks := legacyYSelfChain_two_ne_legacyYOrbit2

/--
Final honest unrestricted-`Y` verdict for the current evaluator.

This closes the lane with a proved negative result rather than a soft frontier:
the current evaluator exposes an explicit infinite orbit on the closed
unrestricted-`Y` seed, so strong normalization for that lane is refuted.
-/
def unrestrictedYFinalVerdict : UnrestrictedYVerdict :=
  .refuted unrestrictedYRefutation

/--
The current unrestricted-`Y` lane ends in the refuted state.
-/
theorem unrestrictedY_final_verdict_refuted :
    unrestrictedYFinalVerdict = .refuted unrestrictedYRefutation := rfl

/--
Bounded operational evidence for unrestricted `Y`.

The reducer exhibits a bounded expanding prefix beginning from `legacyY · legacyY`
for the first four steps. Stronger normalization, coherence, and logical
consistency claims remain outside the Y-free soundness theorem, but strong
normalization is no longer open: it is refuted by `unrestrictedYRefutation`.
-/
theorem unrestrictedY_bounded_operational_prefix :
    reduceFuel 4 legacyYOrbit0 = legacyYOrbit4 := by
  exact reduceFuel_legacyYOrbit4

/--
Every point on the explicit unrestricted-`Y` orbit has a next operational step,
so this evaluator surface does not strongly normalize on the `legacyY · legacyY`
seed.
-/
theorem unrestrictedY_has_infinite_operational_orbit :
    ∀ n, step? (legacyYOrbit n) = some (legacyYOrbit (n + 1)) :=
  step?_legacyYOrbit

theorem unrestrictedY_not_strongly_normalizing :
    ∀ n, step? (legacyYOrbit n) ≠ none :=
  legacyYOrbit_never_normal

end ICC
end LoF
end HeytingLean
