import HeytingLean.HeytingVeil.MiniCMachine.Core
import HeytingLean.HeytingVeil.MiniCMachine.Properties
import HeytingLean.HeytingVeil.MiniCMachine.Decidable
import HeytingLean.HeytingVeil.MiniCMachine.Examples.AbsVal
import HeytingLean.HeytingVeil.MiniCMachine.Examples.Clamp
import HeytingLean.HeytingVeil.MiniCMachine.Examples.SumLoop
import HeytingLean.HeytingVeil.MiniCMachine.Examples.Arrays
