/-!
# CUTLASS codegen patterns (scaffold)

This module collects small string templates used by the CUTLASS-flavored backend.
The output is *text-only* and does not assume CUDA/CUTLASS is installed.
-/

namespace HeytingLean
namespace Compilation
namespace CUTLASSBackend

def headerPreamble (moduleName : String) : String :=
  s!"/* Generated by HeytingLean - Verified CUTLASS Layouts\n * Module: {moduleName}\n */\n"

def pragmaOnce : String := "#pragma once\n"

def includes : String :=
  String.intercalate "\n"
    ["#include <cute/tensor.hpp>", "#include <cute/layout.hpp>", "", "using namespace cute;", ""]

def namespaceOpen (moduleName : String) : String :=
  "namespace heytinglean {\nnamespace " ++ moduleName ++ " {\n"

def namespaceClose : String := "} // namespace\n} // namespace\n"

end CUTLASSBackend
end Compilation
end HeytingLean
