import HeytingLean.C.Emit
import HeytingLean.LambdaIR.Compile
import HeytingLean.MiniC.Semantics
import HeytingLean.MiniC.ToC

/-!
# `cdl_codegen_demo`

Local end-to-end hook that emits a tiny-C file illustrating CDL “weight tying”:

- `sep(x,y) = x + y` (two independent parameters),
- `tied(p) = p + p` (tie via the diagonal `Δ p = (p,p)`).

Pipeline: LambdaIR → MiniC → tiny-C AST → emitted C source in `dist/`.

This executable does **not** invoke an external C compiler; see `scripts/build_cdl_local.sh` to
compile and run the emitted C with the host toolchain.
-/

namespace HeytingLean
namespace CDL
namespace CodegenDemo

open HeytingLean
open HeytingLean.C
open HeytingLean.C.Emit
open HeytingLean.LambdaIR
open HeytingLean.LambdaIR.CertifiedCompile
open HeytingLean.MiniC

/-! ## LambdaIR terms -/

namespace Terms

open HeytingLean.Core
open HeytingLean.LambdaIR
open HeytingLean.LambdaIR.NatFunFragment
open HeytingLean.LambdaIR.Nat2FunFragment

def add2 : Term [] (Ty.arrow Ty.nat (Ty.arrow Ty.nat Ty.nat)) :=
  Term.lam <|
    Term.lam <|
      Term.app (Term.app Term.primAddNat (Term.var (Var.vs Var.vz))) (Term.var Var.vz)

def double : Term [] (Ty.arrow Ty.nat Ty.nat) :=
  Term.lam <|
    Term.app (Term.app Term.primAddNat (Term.var Var.vz)) (Term.var Var.vz)

theorem add2_isNat2 : IsNat2Fun add2 := by
  refine ⟨_, rfl, ?_⟩
  refine IsNatBody₂.expr ?_
  exact IsNatExpr₂.add IsNatExpr₂.varFirst IsNatExpr₂.varSecond

theorem double_isNat1 : IsNatFun double := by
  refine ⟨_, rfl, ?_⟩
  refine IsNatBody.expr ?_
  exact IsNatExpr.add IsNatExpr.var IsNatExpr.var

end Terms

/-! ## CLI plumbing -/

structure Config where
  outDir : String := "dist/cdl_codegen_demo"
deriving Repr

private def usage : String :=
  String.intercalate "\n"
    [ "cdl_codegen_demo"
    , ""
    , "Emits:"
    , "  - generated.c        (C source for sep/tied + a tiny driver main)"
    , "  - expected.txt       (expected stdout from driver main)"
    , "  - lambdair.repr.txt  (debug repr of the LambdaIR terms)"
    , "  - minic.repr.txt     (debug repr of compiled MiniC functions)"
    , ""
    , "Flags:"
    , "  --out <dir>    output directory (relative to repo root unless absolute)"
    , "  --help         show this message"
    ]

private partial def parseArgs (args : List String) (cfg : Config := {}) : IO (Config × Bool) :=
  match args with
  | [] => pure (cfg, false)
  | "--" :: rest => parseArgs rest cfg
  | "--help" :: _ => pure (cfg, true)
  | "--out" :: dir :: rest => parseArgs rest { cfg with outDir := dir }
  | x :: _ => throw <| IO.userError s!"unknown arg: {x} (try --help)"

private def resolveOutDir (dir : String) : System.FilePath :=
  if dir.startsWith "/" then
    System.FilePath.mk dir
  else
    System.FilePath.mk ".." / dir

private def writeFile (path : System.FilePath) (contents : String) : IO Unit := do
  let some parent := path.parent
    | throw <| IO.userError s!"could not compute parent directory for {path}"
  IO.FS.createDirAll parent
  IO.FS.writeFile path contents

private def driverMainSource (p q : Int) : String :=
  String.intercalate "\n"
    [ "int main(void) {"
    , s!"  long long p = {p};"
    , s!"  long long q = {q};"
    , "  printf(\"%lld\\n\", cdl_add2_sep(p, q));"
    , "  printf(\"%lld\\n\", cdl_add2_sep(p, p));"
    , "  printf(\"%lld\\n\", cdl_double_tied(p));"
    , "  return 0;"
    , "}"
    ]

def main (argv : List String) : IO UInt32 := do
  try
    let (cfg, showHelp) ← parseArgs argv
    if showHelp then
      IO.println usage
      return (0 : UInt32)

    let outDir := resolveOutDir cfg.outDir

    -- Compile the LambdaIR terms (with certificates).
    let add2C := compileNat2Fun (funName := "cdl_add2_sep") (t := Terms.add2) Terms.add2_isNat2
    let dblC := compileNat1Fun (funName := "cdl_double_tied") (paramName := "p")
        (t := Terms.double) Terms.double_isNat1

    -- Compute expected output via MiniC semantics.
    let p : Nat := 7
    let q : Nat := 11
    let some out1 := MiniC.runNat2FunFrag add2C.val Nat2CompileFragCorrectness.param1
        Nat2CompileFragCorrectness.param2 p q
      | throw <| IO.userError "failed to run cdl_add2_sep(p,q) under MiniC semantics"
    let some out2 := MiniC.runNat2FunFrag add2C.val Nat2CompileFragCorrectness.param1
        Nat2CompileFragCorrectness.param2 p p
      | throw <| IO.userError "failed to run cdl_add2_sep(p,p) under MiniC semantics"
    let some out3 := MiniC.runNatFunFrag dblC.val "p" p
      | throw <| IO.userError "failed to run cdl_double_tied(p) under MiniC semantics"

    -- Emit C source.
    let cPath := outDir / "generated.c"
    let expectedPath := outDir / "expected.txt"
    let lambdaPath := outDir / "lambdair.repr.txt"
    let minicPath := outDir / "minic.repr.txt"

    let cHeader :=
      String.intercalate "\n"
        [ "/* Generated by HeytingLean (cdl_codegen_demo)"
        , "   Demonstrates tying via diagonal Δ: sep(p,p) = tied(p)"
        , "*/"
        , "#include <stdio.h>"
        , ""
        ]
    let cDefs :=
      Emit.funDefs
        [ MiniC.ToC.compileFun add2C.val
        , MiniC.ToC.compileFun dblC.val
        ]
    let driver := driverMainSource (p := Int.ofNat p) (q := Int.ofNat q)
    let cSource := cHeader ++ cDefs ++ "\n\n" ++ driver ++ "\n"

    writeFile cPath cSource
    writeFile expectedPath (toString out1 ++ "\n" ++ toString out2 ++ "\n" ++ toString out3 ++ "\n")
    writeFile lambdaPath (reprStr Terms.add2 ++ "\n\n" ++ reprStr Terms.double ++ "\n")
    writeFile minicPath (reprStr add2C.val ++ "\n\n" ++ reprStr dblC.val ++ "\n")

    IO.println s!"[cdl_codegen_demo] wrote {cPath}"
    IO.println s!"[cdl_codegen_demo] wrote {expectedPath} (expected stdout)"
    return (0 : UInt32)
  catch e =>
    IO.eprintln s!"[cdl_codegen_demo] error: {e}"
    return (1 : UInt32)

end CodegenDemo
end CDL
end HeytingLean

/-! Expose entry point for the Lake executable target. -/

def main (args : List String) : IO UInt32 :=
  HeytingLean.CDL.CodegenDemo.main args

