import HeytingLean.LoF.CuTe.Generate
import HeytingLean.Layouts.Tuple.Realization

/-!
# CuTe → LoF semantic grounding (bundle slice)

This module provides a minimal “ground” direction for the LoF/CuTe bridge.

The full bidirectional correspondence is future work; for now we:

* define a `GroundedLayout` package (layout + expression + consistency),
* define a small notion of “standard form” as “generated by some expression”,
* implement a partial inverse `groundToLoF` for the `mark`-chain fragment.
-/

namespace HeytingLean
namespace LoF
namespace CuTe

open HeytingLean.Layouts
open HeytingLean.Layouts.Flat

/-- A grounded layout packages a flat layout with a LoF-shaped expression that generates it. -/
structure GroundedLayout where
  layout : FlatLayout
  lofExpr : LoFLayoutExpr
  consistent : generateLayout lofExpr = some layout

/-- “Standard form” layouts: those that are generated by some `LoFLayoutExpr`. -/
def isStandardForm (L : FlatLayout) : Prop :=
  ∃ e : LoFLayoutExpr, generateLayout e = some L

/-- Standard form layouts correspond to (some) generating expression.

This lemma is intentionally just a restatement of `isStandardForm`.
-/
theorem standard_form_is_eigenform (L : FlatLayout) (h : isStandardForm L) :
    ∃ e : LoFLayoutExpr, generateLayout e = some L :=
  h

/-- Attempt to invert `generateLayout` for the `mark`-chain fragment.

This succeeds for layouts of the form `[(2, size inner), ...]` recursively.
-/
def groundToLoF : FlatLayout → Option LoFLayoutExpr
  | [] => some .void
  | p :: ps =>
      if p.shapeNat = 2 ∧ p.stride = FlatLayout.size ps then
        (groundToLoF ps).map LoFLayoutExpr.mark
      else
        none

end CuTe
end LoF
end HeytingLean
