import HeytingLean.NucleusPOD

namespace HeytingLean
namespace Tests
namespace NucleusPOD

open HeytingLean.NucleusPOD

#check category_id_left
#check category_id_right
#check category_assoc
#check categoryTheory_assoc
#check sieve_maximal
#check pullback_stable
#check local_character
#check swarm_topos
#check subobject_classifier
#check inducedSwarmCovers_iff_self_arrow
#check swarmGrothendieck_top_mem
#check swarmGrothendieck_not_top
#check lt_top
#check lt_idempotent
#check lt_meet
#check closureOperatorNat
#check closureGaloisInsertion
#check closureOperatorNat_reconstructs_from_gi
#check closure_le_iff_le_of_closed
#check plus_construction
#check sheafification_is_R
#check sheafification_left_adjoint
#check gluing_unique
#check gluing_R_closed
#check transport_exact_for_R_closed
#check cocycle_from_meet_pres
#check cocycle_auto_for_R_closed
#check slice_topos
#check slice_subobject_classifier
#check role_lattice
#check pullback_preserves_heyting
#check internal_hom_universal
#check cartesian_closed
#check genesis_minimal_closure
#check genesis_omega_growth
#check temporal_priority
#check admin_immutability
#check occam
#check psr
#check dialectic
#check bridge_adjunction
#check bridge_left_exact
#check R_commutes_with_pullback
#check grant_constraint_preservation
#check meet_comm
#check meet_assoc
#check meet_idem
#check join_comm
#check join_assoc
#check agent_meet_join_distrib
#check meet_join_valid
#check contextuality_witness
#check contextuality_iff_not_R_closed
#check contextuality_detectable
#check H0_R_contains_H0
#check cohomological_weakening
#check R_solvability
#check nucleus_consensus_terminates
#check nucleus_consensus_safe
#check nucleus_consensus_valid
#check consensus_without_EM
#check assurance_heyting_algebra
#check R_identity_extensive
#check R_identity_idempotent
#check R_identity_meet_preserving
#check grant_condition_R_closed
#check nucleus_semilattice
#check nucleus_inflationary_update
#check nucleus_SEC
#check nucleus_convergence_rate
#check merge_order_independent
#check merge_idempotent
#check merge_monotone
#check venue_game
#check cooperation_nash
#check cooperation_ESS
#check grant_DSIC
#check revelation_principle
#check nucleus_as_mechanism
#check nucleus_nash
#check nash_is_R_closed
#check FLP_classical
#check FLP_requires_EM
#check nucleus_escapes_FLP
#check FLP_blackout_no_termination
#check no_blackout_sound_rule_terminates
#check decideFromQuorum_blackout_sound
#check FLP_blackout_no_termination_general
#check CAP_classical
#check nucleus_partition_tolerance
#check NP_strict_hierarchy
#check byzantine_classical
#check R_absorbs_byzantine
#check effective_byzantine_threshold
#check laplacian_zero_iff_consistent
#check R_modified_laplacian
#check phronesis_bound
#check contextuality_is_cohomological
#check byzantine_is_contextual
#check constant_product_invariant
#check no_arbitrage
#check k_coherence
#check infinity_groupoid_completion
#check QD_diversity_maintained
#check ratchet_irreversibility
#check pair_bond_convergence
#check provenance_tamper_evident
#check provenance_chain_valid
#check provenance_composable

end NucleusPOD
end Tests
end HeytingLean
