import HeytingLean.WasmMini.Syntax

/-!
# HeytingLean.WasmMini.EmitWAT

Phase-1 WASM backend: emit a tiny, deterministic **WAT** module for `WasmMini`.

Design notes:
- We emit `i64` operations and represent booleans as `0/1` in the same spirit as the tiny-C backend.
- This file is an emitter only; semantic equivalence with the official WASM spec is established by
  differential testing (assemble via `wat2wasm`, run via `wasmtime`, compare to MiniC semantics).
- We keep the emitted WASM subset intentionally small and structured (`if`, `block`, `loop`).
  No raw opcode bytes are emitted here.
-/

namespace HeytingLean
namespace WasmMini

open HeytingLean
open HeytingLean.WasmMini

private def indent (n : Nat) : String :=
  String.intercalate "" (List.replicate (2 * n) " ")

private def sanitizeIdent (s : String) : String :=
  Id.run do
    let mut out : List Char := []
    for c in s.data do
      let ok := (c.isAlphanum) || c == '_' || c == '.'
      out := (if ok then c else '_') :: out
    let core := String.mk out.reverse
    if core.isEmpty then "x" else core

private def watLocal (name : String) : String :=
  s!"${sanitizeIdent name}"

private def watLabel (name : String) : String :=
  s!"${sanitizeIdent name}"

private def i64ConstLit (n : Int) : String :=
  -- WAT integer literals must fit i64; rely on runtime validation/assembly to catch overflow.
  s!"(i64.const {n})"

mutual
  private partial def emitInstrLines (i : Instr) (lvl : Nat) : List String :=
    match i with
    | .i64Const n => [indent lvl ++ i64ConstLit n]
    | .localGet x => [indent lvl ++ s!"(local.get {watLocal x})"]
    | .localSet x => [indent lvl ++ s!"(local.set {watLocal x})"]
    | .i64Add => [indent lvl ++ "i64.add"]
    | .i64Sub => [indent lvl ++ "i64.sub"]
    | .i64Mul => [indent lvl ++ "i64.mul"]
    | .i64LeS => [indent lvl ++ "i64.le_s"]
    | .i64Eq => [indent lvl ++ "i64.eq"]
    | .i64Ne => [indent lvl ++ "i64.ne"]
    | .i64Eqz => [indent lvl ++ "i64.eqz"]
    | .i64ExtendI32u => [indent lvl ++ "i64.extend_i32_u"]
    | .br lbl => [indent lvl ++ s!"br {watLabel lbl}"]
    | .return_ => [indent lvl ++ "return"]
    | .if_ then_ else_ =>
        [indent lvl ++ "(if"] ++
        [indent (lvl+1) ++ "(then"] ++
        emitInstrsLines then_ (lvl+2) ++
        [indent (lvl+1) ++ ")"] ++
        [indent (lvl+1) ++ "(else"] ++
        emitInstrsLines else_ (lvl+2) ++
        [indent (lvl+1) ++ ")"] ++
        [indent lvl ++ ")"]
    | .block lbl body =>
        [indent lvl ++ s!"(block {watLabel lbl}"] ++
        emitInstrsLines body (lvl+1) ++
        [indent lvl ++ ")"]
    | .loop lbl body =>
        [indent lvl ++ s!"(loop {watLabel lbl}"] ++
        emitInstrsLines body (lvl+1) ++
        [indent lvl ++ ")"]

  private partial def emitInstrsLines (is : List Instr) (lvl : Nat) : List String :=
    is.foldl (fun acc i => acc ++ emitInstrLines i lvl) []
end

private def emitFunHeader (fn : Fun) : List String :=
  let params := fn.params
  let header :=
    [ "(func " ++ watLocal fn.name
    , indent 1 ++ s!"(export \"{fn.name}\")"
    ] ++
    (params.map (fun p => indent 1 ++ s!"(param {watLocal p} i64)")) ++
    [ indent 1 ++ "(result i64)" ] ++
    (fn.locals.map (fun x => indent 1 ++ s!"(local {watLocal x} i64)"))
  header

/-- Emit a single `WasmMini` function as a WAT `(func ...)` definition (exports the function name). -/
def emitFun (fn : Fun) : String :=
  let header := emitFunHeader fn
  let bodyLines := emitInstrsLines fn.body 1
  let tail := [")"]
  String.intercalate "\n" (header ++ bodyLines ++ tail)

/-- Emit a full WAT module containing exported `WasmMini` functions. -/
def emitModule (funs : List Fun) : String :=
  let header :=
    String.intercalate "\n"
      [ ";; Generated by HeytingLean (MiniC → WAT)"
      , ";; Phase-1 WASM backend: i64-only, booleans encoded as 0/1."
      , "(module"
      ]
  let body := String.intercalate "\n\n" (funs.map emitFun)
  String.intercalate "\n" [header, body, ")", ""]

/-- Emit a Stylus-compatible WAT module.

This is a pragmatic “Wasm → Solidity” bridge for Arbitrum Stylus-style runtimes:
- keep the verified core (`MiniC → WasmMini`) untouched,
- add a thin, **unverified** adapter that exposes a single `user_entrypoint` and
  uses Stylus host hooks to read calldata and write return data.

The adapter uses a very small custom ABI:
- calldata layout: `tag:u8 | args...`
  - `tag=0`: call `$heyting_add1(x:i64)`
  - `tag=1`: call `$heyting_add2(x:i64, y:i64)`
- args are little-endian `i64` packed at byte offsets 1 and 9.
- return data is 32 bytes: the first 8 bytes are the `i64` result in little-endian, remaining bytes are zero.

This keeps the “Solidity side” simple while we iterate.
-/
def emitStylusModule (funs : List Fun) : String :=
  let header :=
    String.intercalate "\n"
      [ ";; Generated by HeytingLean (MiniC → WAT, Stylus adapter)"
      , ";; Core functions are compiled by `WasmMini.emitFun` (verified at the WasmMini level)."
      , ";; The `user_entrypoint` adapter is unverified and intended for smoke-level validation."
      , "(module"
      , indent 1 ++ "(import \"vm_hooks\" \"read_args\" (func $read_args (param i32)))"
      , indent 1 ++ "(import \"vm_hooks\" \"write_result\" (func $write_result (param i32 i32)))"
      , indent 1 ++ "(import \"vm_hooks\" \"pay_for_memory_grow\" (func $pay_for_memory_grow (param i32)))"
      , indent 1 ++ "(memory (export \"memory\") 1 1)"
      ]
  let body := String.intercalate "\n\n" (funs.map emitFun)
  let entrypoint :=
    String.intercalate "\n"
      [ ""
      , indent 1 ++ "(func (export \"user_entrypoint\") (param $len i32) (result i32)"
      , indent 2 ++ "(local $tag i32)"
      , indent 2 ++ "(local $x i64)"
      , indent 2 ++ "(local $y i64)"
      , indent 2 ++ "(local $res i64)"
      , ""
      , indent 2 ++ "(call $read_args (i32.const 0))"
      , indent 2 ++ "(local.set $tag (i32.load8_u (i32.const 0)))"
      , indent 2 ++ "(if (i32.eq (local.get $tag) (i32.const 0))"
      , indent 3 ++ "(then"
      , indent 4 ++ "(local.set $x (i64.load offset=1 align=1 (i32.const 0)))"
      , indent 4 ++ "(local.set $res (call $heyting_add1 (local.get $x)))"
      , indent 3 ++ ")"
      , indent 3 ++ "(else"
      , indent 4 ++ "(if (i32.eq (local.get $tag) (i32.const 1))"
      , indent 5 ++ "(then"
      , indent 6 ++ "(local.set $x (i64.load offset=1 align=1 (i32.const 0)))"
      , indent 6 ++ "(local.set $y (i64.load offset=9 align=1 (i32.const 0)))"
      , indent 6 ++ "(local.set $res (call $heyting_add2 (local.get $x) (local.get $y)))"
      , indent 5 ++ ")"
      , indent 5 ++ "(else"
      , indent 6 ++ "(return (i32.const 1))"
      , indent 5 ++ ")"
      , indent 4 ++ ")"
      , indent 3 ++ ")"
      , indent 2 ++ ")"
      , ""
      , indent 2 ++ "(i64.store align=1 (i32.const 64) (local.get $res))"
      , indent 2 ++ "(i64.store offset=8 align=1 (i32.const 64) (i64.const 0))"
      , indent 2 ++ "(i64.store offset=16 align=1 (i32.const 64) (i64.const 0))"
      , indent 2 ++ "(i64.store offset=24 align=1 (i32.const 64) (i64.const 0))"
      , indent 2 ++ "(call $write_result (i32.const 64) (i32.const 32))"
      , indent 2 ++ "(i32.const 0)"
      , indent 1 ++ ")"
      ]
  String.intercalate "\n" [header, body, entrypoint, ")", ""]

/-- Emit a zkWASM-compatible WAT module (Delphinus zkWasm CLI).

This adapter targets the `zkwasm-cli` “prove execution of WASM” workflow:
- core functions are compiled via the verified `MiniC → WasmMini` path;
- a thin **unverified** `zkmain` adapter:
  - reads inputs via `env.wasm_input`
  - emits the result via `env.wasm_output` (public IO instances)
  - also writes the result via `env.wasm_write_context` so CLIs can save it to a file (`--context-out`)

Input convention (minimal, for smoke-level integration):
- public inputs consumed by `wasm_input(1)`:
  - `tag` (0 or 1)
  - `x`
  - `y` (only when `tag=1`)
- semantics:
  - `tag=0`: call `$heyting_add1(x)`
  - `tag=1`: call `$heyting_add2(x,y)`
- outputs:
  - `wasm_output(res)` and `wasm_write_context(res)` once.

References:
- Delphinus zkWasm CLI expects an exported `zkmain` and host imports under module `"env"`.
- The C SDK header uses the same host function names (`wasm_input`, `wasm_output`, `wasm_write_context`).
-/
def emitZkWasmModule (funs : List Fun) : String :=
  let header :=
    String.intercalate "\n"
      [ ";; Generated by HeytingLean (MiniC → WAT, zkWASM adapter)"
      , ";; Core functions are compiled by `WasmMini.emitFun` (verified at the WasmMini level)."
      , ";; The `zkmain` adapter is unverified and intended for zkWASM prove/verify integration."
      , "(module"
      , indent 1 ++ "(import \"env\" \"wasm_input\" (func $wasm_input (param i32) (result i64)))"
      , indent 1 ++ "(import \"env\" \"wasm_output\" (func $wasm_output (param i64)))"
      , indent 1 ++ "(import \"env\" \"wasm_write_context\" (func $wasm_write_context (param i64)))"
      ]
  let body := String.intercalate "\n\n" (funs.map emitFun)
  let entrypoint :=
    String.intercalate "\n"
      [ ""
      , indent 1 ++ "(func (export \"zkmain\") (result i32)"
      , indent 2 ++ "(local $tag i64)"
      , indent 2 ++ "(local $x i64)"
      , indent 2 ++ "(local $y i64)"
      , indent 2 ++ "(local $res i64)"
      , ""
      , indent 2 ++ "(local.set $tag (call $wasm_input (i32.const 1)))"
      , indent 2 ++ "(if (i64.eq (local.get $tag) (i64.const 0))"
      , indent 3 ++ "(then"
      , indent 4 ++ "(local.set $x (call $wasm_input (i32.const 1)))"
      , indent 4 ++ "(local.set $res (call $heyting_add1 (local.get $x)))"
      , indent 3 ++ ")"
      , indent 3 ++ "(else"
      , indent 4 ++ "(if (i64.eq (local.get $tag) (i64.const 1))"
      , indent 5 ++ "(then"
      , indent 6 ++ "(local.set $x (call $wasm_input (i32.const 1)))"
      , indent 6 ++ "(local.set $y (call $wasm_input (i32.const 1)))"
      , indent 6 ++ "(local.set $res (call $heyting_add2 (local.get $x) (local.get $y)))"
      , indent 5 ++ ")"
      , indent 5 ++ "(else"
      , indent 6 ++ "(return (i32.const 1))"
      , indent 5 ++ ")"
      , indent 4 ++ ")"
      , indent 3 ++ ")"
      , indent 2 ++ ")"
      , ""
      , indent 2 ++ "(call $wasm_output (local.get $res))"
      , indent 2 ++ "(call $wasm_write_context (local.get $res))"
      , indent 2 ++ "(i32.const 0)"
      , indent 1 ++ ")"
      ]
  String.intercalate "\n" [header, body, entrypoint, ")", ""]

/-- Emit a CosmWasm-compatible WAT module (CosmWasm VM ABI, adapter layer).

This adapter is an **unverified glue layer** that targets the CosmWasm VM entrypoints:
- exports `instantiate`, `execute`, `query` using the canonical region-pointer ABI,
- exports `allocate` / `deallocate` and `interface_version_8`,
- exports `memory`.

For smoke-level integration we use a tiny **JSON** message:
- `msg` is expected to contain (at least) three integers in this order:
- `msg` is expected to contain a tiny JSON object with integer fields (order-independent):
  - selector: either `fn` (preferred) or `tag`
  - arguments: `x` (required for all current demos), `y` (optional; defaults to 0)
  - e.g. `{"fn":1,"x":41,"y":1}` or `{"tag":0,"x":41}`
- dispatch (selector value):
  - 0 → call `$heyting_add1(x)`
  - 1 → call `$heyting_add2(x,y)`
  - 2 → call `$heyting_if_demo(x)`
  - 3 → call `$heyting_while_sum(x)`

Return values follow the standard JSON ABI:
- `instantiate/execute` return `ContractResult<Response>` JSON bytes.
  - `execute` stores the result as `Response.data` (base64 of the 8-byte little-endian i64).
- `query` returns `ContractResult<Binary>` JSON bytes, where the `Binary` payload is itself **JSON bytes**
  (CosmWasm VM requires this). Concretely:
  - outer JSON: `{"ok":"<base64>"}` where `<base64>` decodes to inner JSON bytes
  - inner JSON: `{"res_b64":"<base64>"}` where the inner `<base64>` decodes to 8 bytes (LE i64).

This is intended to be exercised via `cosmwasm-vm` (and raw calls as needed) while we iterate.
-/
def emitCosmWasmModule (funs : List Fun) : String :=
  let header :=
    String.intercalate "\n"
      [ ";; Generated by HeytingLean (MiniC → WAT, CosmWasm adapter)"
      , ";; Core functions are compiled by `WasmMini.emitFun` (verified at the WasmMini level)."
      , ";; The CosmWasm adapter layer is unverified and uses a tiny JSON msg format (see docstring)."
      , "(module"
      , indent 1 ++ "(memory (export \"memory\") 2)"
      , indent 1 ++ "(global $heap_ptr (mut i32) (i32.const 1024))"
      , indent 1 ++ "(global $free_head (mut i32) (i32.const 0))"
      , ""
      , indent 1 ++ ";; CosmWasm interface version marker (required export)."
      , indent 1 ++ "(func (export \"interface_version_8\"))"
      , ""
      , indent 1 ++ ";; Const data (below the heap base)."
      , indent 1 ++ "(data (i32.const 0) \"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\")"
      , indent 1 ++ "(data (i32.const 80) \"{\\\"ok\\\":\\\"\")"
      , indent 1 ++ "(data (i32.const 100) \"\\\"}\")"
      , indent 1 ++ "(data (i32.const 120) \"{\\\"ok\\\":{\\\"messages\\\":[],\\\"attributes\\\":[],\\\"events\\\":[],\\\"data\\\":\\\"\")"
      , indent 1 ++ "(data (i32.const 200) \"\\\"}}\")"
      , indent 1 ++ "(data (i32.const 220) \"{\\\"ok\\\":{\\\"messages\\\":[],\\\"attributes\\\":[],\\\"events\\\":[],\\\"data\\\":null}}\")"
      , indent 1 ++ "(data (i32.const 320) \"{\\\"error\\\":\\\"bad msg\\\"}\")"
      , indent 1 ++ "(data (i32.const 360) \"{\\\"res_b64\\\":\\\"\")"
      , indent 1 ++ "(data (i32.const 380) \"\\\"}\")"
      , ""
      , indent 1 ++ ";; Region layout (3x u32): offset | capacity | length"
      , indent 1 ++ "(func $allocate (export \"allocate\") (param $size i32) (result i32)"
      , indent 2 ++ "(local $region i32)"
      , indent 2 ++ "(local $prev i32)"
      , indent 2 ++ "(local $cur i32)"
      , indent 2 ++ "(local $cap i32)"
      , indent 2 ++ "(local $data i32)"
      , indent 2 ++ "(local $next i32)"
      , indent 2 ++ ";; First-fit freelist scan (stores `next` pointer in freed region's offset field)."
      , indent 2 ++ "(local.set $region (i32.const 0))"
      , indent 2 ++ "(local.set $prev (i32.const 0))"
      , indent 2 ++ "(local.set $cur (global.get $free_head))"
      , indent 2 ++ "(block $scan_done"
      , indent 3 ++ "(loop $scan"
      , indent 4 ++ "(br_if $scan_done (i32.eq (local.get $cur) (i32.const 0)))"
      , indent 4 ++ "(local.set $cap (i32.load offset=4 (local.get $cur)))"
      , indent 4 ++ "(if (i32.ge_u (local.get $cap) (local.get $size))"
      , indent 5 ++ "(then"
      , indent 6 ++ "(local.set $region (local.get $cur))"
      , indent 6 ++ "(local.set $next (i32.load (local.get $cur)))"
      , indent 6 ++ "(if (i32.eq (local.get $prev) (i32.const 0))"
      , indent 7 ++ "(then (global.set $free_head (local.get $next)))"
      , indent 7 ++ "(else (i32.store (local.get $prev) (local.get $next)))"
      , indent 6 ++ ")"
      , indent 6 ++ "(br $scan_done)"
      , indent 5 ++ ")"
      , indent 4 ++ ")"
      , indent 4 ++ "(local.set $prev (local.get $cur))"
      , indent 4 ++ "(local.set $cur (i32.load (local.get $cur)))"
      , indent 4 ++ "(br $scan)"
      , indent 3 ++ ")"
      , indent 2 ++ ")"
      , indent 2 ++ "(if (i32.eq (local.get $region) (i32.const 0))"
      , indent 3 ++ "(then"
      , indent 4 ++ "(local.set $region (global.get $heap_ptr))"
      , indent 4 ++ "(local.set $cap (local.get $size))"
      , indent 4 ++ "(local.set $data (i32.add (local.get $region) (i32.const 12)))"
      , indent 4 ++ ";; advance heap ptr (region header + payload), aligned to 8 bytes"
      , indent 4 ++ "(local.set $next"
      , indent 5 ++ "(i32.add"
      , indent 6 ++ "(local.get $data)"
      , indent 6 ++ "(i32.and"
      , indent 7 ++ "(i32.add (local.get $size) (i32.const 7))"
      , indent 7 ++ "(i32.const -8)"
      , indent 6 ++ ")"
      , indent 5 ++ ")"
      , indent 4 ++ ")"
      , indent 4 ++ "(global.set $heap_ptr (local.get $next))"
      , indent 3 ++ ")"
      , indent 3 ++ "(else"
      , indent 4 ++ "(local.set $data (i32.add (local.get $region) (i32.const 12)))"
      , indent 3 ++ ")"
      , indent 2 ++ ")"
      , indent 2 ++ ";; write region header"
      , indent 2 ++ "(i32.store (local.get $region) (local.get $data))"
      , indent 2 ++ "(i32.store offset=4 (local.get $region) (local.get $cap))"
      , indent 2 ++ "(i32.store offset=8 (local.get $region) (local.get $size))"
      , indent 2 ++ "(local.get $region)"
      , indent 1 ++ ")"
      , ""
      , indent 1 ++ "(func $deallocate (export \"deallocate\") (param $region i32)"
      , indent 2 ++ "(local $cap i32)"
      , indent 2 ++ "(local $end i32)"
      , indent 2 ++ "(if (i32.eq (local.get $region) (i32.const 0)) (then (return)))"
      , indent 2 ++ "(if (i32.lt_u (local.get $region) (i32.const 1024)) (then (return)))"
      , indent 2 ++ "(local.set $cap (i32.load offset=4 (local.get $region)))"
      , indent 2 ++ "(local.set $end"
      , indent 3 ++ "(i32.add"
      , indent 4 ++ "(i32.add (local.get $region) (i32.const 12))"
      , indent 4 ++ "(i32.and"
      , indent 5 ++ "(i32.add (local.get $cap) (i32.const 7))"
      , indent 5 ++ "(i32.const -8)"
      , indent 4 ++ ")"
      , indent 3 ++ ")"
      , indent 2 ++ ")"
      , indent 2 ++ "(if (i32.eq (local.get $end) (global.get $heap_ptr))"
      , indent 3 ++ "(then (global.set $heap_ptr (local.get $region)))"
      , indent 3 ++ "(else"
      , indent 4 ++ "(i32.store (local.get $region) (global.get $free_head))"
      , indent 4 ++ "(global.set $free_head (local.get $region))"
      , indent 3 ++ ")"
      , indent 2 ++ ")"
      , indent 1 ++ ")"
      , ""
      , indent 1 ++ ";; Helper: read msg region offset/length."
      , indent 1 ++ "(func $region_offset (param $r i32) (result i32)"
      , indent 2 ++ "(i32.load (local.get $r))"
      , indent 1 ++ ")"
      , indent 1 ++ "(func $region_length (param $r i32) (result i32)"
      , indent 2 ++ "(i32.load offset=8 (local.get $r))"
      , indent 1 ++ ")"
      , ""
      , indent 1 ++ ";; Globals used for tiny JSON parsing."
      , indent 1 ++ "(global $g_tag (mut i32) (i32.const 0))"
      , indent 1 ++ "(global $g_fn (mut i32) (i32.const 0))"
      , indent 1 ++ "(global $g_x (mut i64) (i64.const 0))"
      , indent 1 ++ "(global $g_y (mut i64) (i64.const 0))"
      , indent 1 ++ "(global $g_have_tag (mut i32) (i32.const 0))"
      , indent 1 ++ "(global $g_have_fn (mut i32) (i32.const 0))"
      , indent 1 ++ "(global $g_have_x (mut i32) (i32.const 0))"
      , indent 1 ++ "(global $g_have_y (mut i32) (i32.const 0))"
      , ""
      , indent 1 ++ ";; Parse a tiny JSON object for integer fields: tag/fn/x/y (order-independent)."
      , indent 1 ++ "(func $parse_fields (param $msg i32)"
      , indent 2 ++ "(local $ptr i32)"
      , indent 2 ++ "(local $len i32)"
      , indent 2 ++ "(local $i i32)"
      , indent 2 ++ "(local $c i32)"
      , indent 2 ++ "(local $key i32)"
      , indent 2 ++ "(local $j i32)"
      , indent 2 ++ "(local $sign i32)"
      , indent 2 ++ "(local $acc i64)"
      , indent 2 ++ "(local $val i64)"
      , indent 2 ++ "(global.set $g_tag (i32.const 0))"
      , indent 2 ++ "(global.set $g_fn (i32.const 0))"
      , indent 2 ++ "(global.set $g_x (i64.const 0))"
      , indent 2 ++ "(global.set $g_y (i64.const 0))"
      , indent 2 ++ "(global.set $g_have_tag (i32.const 0))"
      , indent 2 ++ "(global.set $g_have_fn (i32.const 0))"
      , indent 2 ++ "(global.set $g_have_x (i32.const 0))"
      , indent 2 ++ "(global.set $g_have_y (i32.const 0))"
      , indent 2 ++ "(local.set $ptr (call $region_offset (local.get $msg)))"
      , indent 2 ++ "(local.set $len (call $region_length (local.get $msg)))"
      , indent 2 ++ "(local.set $i (i32.const 0))"
      , indent 2 ++ "(local.set $sign (i32.const 1))"
      , indent 2 ++ "(local.set $acc (i64.const 0))"
      , indent 2 ++ "(block $done"
      , indent 3 ++ "(loop $loop"
      , indent 4 ++ "(br_if $done (i32.ge_u (local.get $i) (local.get $len)))"
      , indent 4 ++ "(local.set $c (i32.load8_u (i32.add (local.get $ptr) (local.get $i))))"
      , indent 4 ++ "(if (i32.eq (local.get $c) (i32.const 34))"
      , indent 5 ++ "(then"
      , indent 6 ++ "(local.set $key (i32.const 0))"
      , indent 6 ++ ";; match keys: \"tag\", \"x\", \"y\", \"fn\""
      , indent 6 ++ "(if (i32.lt_u (i32.add (local.get $i) (i32.const 4)) (local.get $len))"
      , indent 7 ++ "(then"
      , indent 8 ++ "(if (i32.and"
      , indent 9 ++ "(i32.eq (i32.load8_u (i32.add (local.get $ptr) (i32.add (local.get $i) (i32.const 1)))) (i32.const 116))"
      , indent 9 ++ "(i32.and"
      , indent 10 ++ "(i32.eq (i32.load8_u (i32.add (local.get $ptr) (i32.add (local.get $i) (i32.const 2)))) (i32.const 97))"
      , indent 10 ++ "(i32.and"
      , indent 11 ++ "(i32.eq (i32.load8_u (i32.add (local.get $ptr) (i32.add (local.get $i) (i32.const 3)))) (i32.const 103))"
      , indent 11 ++ "(i32.eq (i32.load8_u (i32.add (local.get $ptr) (i32.add (local.get $i) (i32.const 4)))) (i32.const 34))"
      , indent 10 ++ ")"
      , indent 9 ++ ")"
      , indent 8 ++ ")"
      , indent 9 ++ "(then (local.set $key (i32.const 1)))"
      , indent 8 ++ ")"
      , indent 7 ++ ")"
      , indent 6 ++ ")"
      , indent 6 ++ "(if (i32.eq (local.get $key) (i32.const 0))"
      , indent 7 ++ "(then"
      , indent 8 ++ "(if (i32.lt_u (i32.add (local.get $i) (i32.const 2)) (local.get $len))"
      , indent 9 ++ "(then"
      , indent 10 ++ "(if (i32.and"
      , indent 11 ++ "(i32.eq (i32.load8_u (i32.add (local.get $ptr) (i32.add (local.get $i) (i32.const 1)))) (i32.const 120))"
      , indent 11 ++ "(i32.eq (i32.load8_u (i32.add (local.get $ptr) (i32.add (local.get $i) (i32.const 2)))) (i32.const 34))"
      , indent 10 ++ ")"
      , indent 11 ++ "(then (local.set $key (i32.const 2)))"
      , indent 10 ++ ")"
      , indent 9 ++ ")"
      , indent 8 ++ ")"
      , indent 7 ++ ")"
      , indent 6 ++ ")"
      , indent 6 ++ "(if (i32.eq (local.get $key) (i32.const 0))"
      , indent 7 ++ "(then"
      , indent 8 ++ "(if (i32.lt_u (i32.add (local.get $i) (i32.const 2)) (local.get $len))"
      , indent 9 ++ "(then"
      , indent 10 ++ "(if (i32.and"
      , indent 11 ++ "(i32.eq (i32.load8_u (i32.add (local.get $ptr) (i32.add (local.get $i) (i32.const 1)))) (i32.const 121))"
      , indent 11 ++ "(i32.eq (i32.load8_u (i32.add (local.get $ptr) (i32.add (local.get $i) (i32.const 2)))) (i32.const 34))"
      , indent 10 ++ ")"
      , indent 11 ++ "(then (local.set $key (i32.const 3)))"
      , indent 10 ++ ")"
      , indent 9 ++ ")"
      , indent 8 ++ ")"
      , indent 7 ++ ")"
      , indent 6 ++ ")"
      , indent 6 ++ "(if (i32.eq (local.get $key) (i32.const 0))"
      , indent 7 ++ "(then"
      , indent 8 ++ "(if (i32.lt_u (i32.add (local.get $i) (i32.const 3)) (local.get $len))"
      , indent 9 ++ "(then"
      , indent 10 ++ "(if (i32.and"
      , indent 11 ++ "(i32.eq (i32.load8_u (i32.add (local.get $ptr) (i32.add (local.get $i) (i32.const 1)))) (i32.const 102))"
      , indent 11 ++ "(i32.and"
      , indent 12 ++ "(i32.eq (i32.load8_u (i32.add (local.get $ptr) (i32.add (local.get $i) (i32.const 2)))) (i32.const 110))"
      , indent 12 ++ "(i32.eq (i32.load8_u (i32.add (local.get $ptr) (i32.add (local.get $i) (i32.const 3)))) (i32.const 34))"
      , indent 11 ++ ")"
      , indent 10 ++ ")"
      , indent 11 ++ "(then (local.set $key (i32.const 4)))"
      , indent 10 ++ ")"
      , indent 9 ++ ")"
      , indent 8 ++ ")"
      , indent 7 ++ ")"
      , indent 6 ++ ")"
      , indent 6 ++ "(if (i32.ne (local.get $key) (i32.const 0))"
      , indent 7 ++ "(then"
      , indent 8 ++ ";; find ':' starting at current index"
      , indent 8 ++ "(local.set $j (local.get $i))"
      , indent 8 ++ "(block $colon_done"
      , indent 9 ++ "(loop $colon_loop"
      , indent 10 ++ "(br_if $colon_done (i32.ge_u (local.get $j) (local.get $len)))"
      , indent 10 ++ "(local.set $c (i32.load8_u (i32.add (local.get $ptr) (local.get $j))))"
      , indent 10 ++ "(if (i32.eq (local.get $c) (i32.const 58)) (then (br $colon_done)))"
      , indent 10 ++ "(local.set $j (i32.add (local.get $j) (i32.const 1)))"
      , indent 10 ++ "(br $colon_loop)"
      , indent 9 ++ ")"
      , indent 8 ++ ")"
      , indent 8 ++ "(if (i32.lt_u (local.get $j) (local.get $len))"
      , indent 9 ++ "(then"
      , indent 10 ++ "(local.set $j (i32.add (local.get $j) (i32.const 1)))"
      , indent 10 ++ ";; skip whitespace"
      , indent 10 ++ "(block $ws_done"
      , indent 11 ++ "(loop $ws_loop"
      , indent 12 ++ "(br_if $ws_done (i32.ge_u (local.get $j) (local.get $len)))"
      , indent 12 ++ "(local.set $c (i32.load8_u (i32.add (local.get $ptr) (local.get $j))))"
      , indent 12 ++ "(if (i32.or"
      , indent 13 ++ "(i32.eq (local.get $c) (i32.const 32))"
      , indent 13 ++ "(i32.or"
      , indent 14 ++ "(i32.eq (local.get $c) (i32.const 9))"
      , indent 14 ++ "(i32.or"
      , indent 15 ++ "(i32.eq (local.get $c) (i32.const 10))"
      , indent 15 ++ "(i32.eq (local.get $c) (i32.const 13))"
      , indent 14 ++ ")"
      , indent 13 ++ ")"
      , indent 12 ++ ")"
      , indent 13 ++ "(then"
      , indent 14 ++ "(local.set $j (i32.add (local.get $j) (i32.const 1)))"
      , indent 14 ++ "(br $ws_loop)"
      , indent 13 ++ ")"
      , indent 12 ++ ")"
      , indent 12 ++ "(br $ws_done)"
      , indent 11 ++ ")"
      , indent 10 ++ ")"
      , indent 10 ++ "(local.set $sign (i32.const 1))"
      , indent 10 ++ "(local.set $acc (i64.const 0))"
      , indent 10 ++ "(if (i32.lt_u (local.get $j) (local.get $len))"
      , indent 11 ++ "(then"
      , indent 12 ++ "(local.set $c (i32.load8_u (i32.add (local.get $ptr) (local.get $j))))"
      , indent 12 ++ "(if (i32.eq (local.get $c) (i32.const 45))"
      , indent 13 ++ "(then"
      , indent 14 ++ "(local.set $sign (i32.const -1))"
      , indent 14 ++ "(local.set $j (i32.add (local.get $j) (i32.const 1)))"
      , indent 13 ++ ")"
      , indent 12 ++ ")"
      , indent 11 ++ ")"
      , indent 10 ++ ")"
      , indent 10 ++ "(block $digits_done"
      , indent 11 ++ "(loop $digits_loop"
      , indent 12 ++ "(br_if $digits_done (i32.ge_u (local.get $j) (local.get $len)))"
      , indent 12 ++ "(local.set $c (i32.load8_u (i32.add (local.get $ptr) (local.get $j))))"
      , indent 12 ++ "(br_if $digits_done (i32.lt_u (local.get $c) (i32.const 48)))"
      , indent 12 ++ "(br_if $digits_done (i32.gt_u (local.get $c) (i32.const 57)))"
      , indent 12 ++ "(local.set $acc (i64.add (i64.mul (local.get $acc) (i64.const 10)) (i64.extend_i32_u (i32.sub (local.get $c) (i32.const 48)))))"
      , indent 12 ++ "(local.set $j (i32.add (local.get $j) (i32.const 1)))"
      , indent 12 ++ "(br $digits_loop)"
      , indent 11 ++ ")"
      , indent 10 ++ ")"
      , indent 10 ++ "(local.set $val (i64.mul (local.get $acc) (i64.extend_i32_s (local.get $sign))))"
      , indent 10 ++ "(if (i32.eq (local.get $key) (i32.const 1))"
      , indent 11 ++ "(then"
      , indent 12 ++ "(global.set $g_tag (i32.wrap_i64 (local.get $val)))"
      , indent 12 ++ "(global.set $g_have_tag (i32.const 1))"
      , indent 11 ++ ")"
      , indent 11 ++ "(else"
      , indent 12 ++ "(if (i32.eq (local.get $key) (i32.const 2))"
      , indent 13 ++ "(then (global.set $g_x (local.get $val)) (global.set $g_have_x (i32.const 1)))"
      , indent 13 ++ "(else"
      , indent 14 ++ "(if (i32.eq (local.get $key) (i32.const 3))"
      , indent 15 ++ "(then (global.set $g_y (local.get $val)) (global.set $g_have_y (i32.const 1)))"
      , indent 15 ++ "(else"
      , indent 16 ++ "(if (i32.eq (local.get $key) (i32.const 4))"
      , indent 17 ++ "(then (global.set $g_fn (i32.wrap_i64 (local.get $val))) (global.set $g_have_fn (i32.const 1)))"
      , indent 17 ++ "(else nop)"
      , indent 16 ++ ")"
      , indent 15 ++ ")"
      , indent 14 ++ ")"
      , indent 13 ++ ")"
      , indent 12 ++ ")"
      , indent 11 ++ ")"
      , indent 10 ++ ")"
      , indent 10 ++ "(local.set $i (local.get $j))"
      , indent 10 ++ "(br $loop)"
      , indent 9 ++ ")"
      , indent 8 ++ ")"
      , indent 7 ++ ")"
      , indent 6 ++ ")"
      , indent 5 ++ ")"
      , indent 4 ++ ")"
      , indent 4 ++ "(local.set $i (i32.add (local.get $i) (i32.const 1)))"
      , indent 4 ++ "(br $loop)"
      , indent 3 ++ ")"
      , indent 2 ++ ")"
      , indent 1 ++ ")"
      , ""
      , indent 1 ++ ";; memcpy(dst, src, len)"
      , indent 1 ++ "(func $memcpy (param $dst i32) (param $src i32) (param $len i32)"
      , indent 2 ++ "(local $i i32)"
      , indent 2 ++ "(local.set $i (i32.const 0))"
      , indent 2 ++ "(block $exit"
      , indent 3 ++ "(loop $lp"
      , indent 4 ++ "(br_if $exit (i32.ge_u (local.get $i) (local.get $len)))"
      , indent 4 ++ "(i32.store8"
      , indent 5 ++ "(i32.add (local.get $dst) (local.get $i))"
      , indent 5 ++ "(i32.load8_u (i32.add (local.get $src) (local.get $i)))"
      , indent 4 ++ ")"
      , indent 4 ++ "(local.set $i (i32.add (local.get $i) (i32.const 1)))"
      , indent 4 ++ "(br $lp)"
      , indent 3 ++ ")"
      , indent 2 ++ ")"
      , indent 1 ++ ")"
      , ""
      , indent 1 ++ ";; Base64-encode 8 bytes (little-endian i64) into 12 chars (with one '=' padding)."
      , indent 1 ++ "(func $b64_i64 (param $x i64) (param $out i32)"
      , indent 2 ++ "(local $b0 i32) (local $b1 i32) (local $b2 i32) (local $b3 i32)"
      , indent 2 ++ "(local $b4 i32) (local $b5 i32) (local $b6 i32) (local $b7 i32)"
      , indent 2 ++ "(local $i0 i32) (local $i1 i32) (local $i2 i32) (local $i3 i32)"
      , indent 2 ++ "(local $j0 i32) (local $j1 i32) (local $j2 i32) (local $j3 i32)"
      , indent 2 ++ "(local $k0 i32) (local $k1 i32) (local $k2 i32)"
      , indent 2 ++ "(local.set $b0 (i32.wrap_i64 (i64.and (local.get $x) (i64.const 255))))"
      , indent 2 ++ "(local.set $b1 (i32.wrap_i64 (i64.and (i64.shr_u (local.get $x) (i64.const 8)) (i64.const 255))))"
      , indent 2 ++ "(local.set $b2 (i32.wrap_i64 (i64.and (i64.shr_u (local.get $x) (i64.const 16)) (i64.const 255))))"
      , indent 2 ++ "(local.set $b3 (i32.wrap_i64 (i64.and (i64.shr_u (local.get $x) (i64.const 24)) (i64.const 255))))"
      , indent 2 ++ "(local.set $b4 (i32.wrap_i64 (i64.and (i64.shr_u (local.get $x) (i64.const 32)) (i64.const 255))))"
      , indent 2 ++ "(local.set $b5 (i32.wrap_i64 (i64.and (i64.shr_u (local.get $x) (i64.const 40)) (i64.const 255))))"
      , indent 2 ++ "(local.set $b6 (i32.wrap_i64 (i64.and (i64.shr_u (local.get $x) (i64.const 48)) (i64.const 255))))"
      , indent 2 ++ "(local.set $b7 (i32.wrap_i64 (i64.and (i64.shr_u (local.get $x) (i64.const 56)) (i64.const 255))))"
      , indent 2 ++ ";; group 1"
      , indent 2 ++ "(local.set $i0 (i32.shr_u (local.get $b0) (i32.const 2)))"
      , indent 2 ++ "(local.set $i1 (i32.or (i32.shl (i32.and (local.get $b0) (i32.const 3)) (i32.const 4)) (i32.shr_u (local.get $b1) (i32.const 4))))"
      , indent 2 ++ "(local.set $i2 (i32.or (i32.shl (i32.and (local.get $b1) (i32.const 15)) (i32.const 2)) (i32.shr_u (local.get $b2) (i32.const 6))))"
      , indent 2 ++ "(local.set $i3 (i32.and (local.get $b2) (i32.const 63)))"
      , indent 2 ++ ";; group 2"
      , indent 2 ++ "(local.set $j0 (i32.shr_u (local.get $b3) (i32.const 2)))"
      , indent 2 ++ "(local.set $j1 (i32.or (i32.shl (i32.and (local.get $b3) (i32.const 3)) (i32.const 4)) (i32.shr_u (local.get $b4) (i32.const 4))))"
      , indent 2 ++ "(local.set $j2 (i32.or (i32.shl (i32.and (local.get $b4) (i32.const 15)) (i32.const 2)) (i32.shr_u (local.get $b5) (i32.const 6))))"
      , indent 2 ++ "(local.set $j3 (i32.and (local.get $b5) (i32.const 63)))"
      , indent 2 ++ ";; group 3 (2 bytes + '=')"
      , indent 2 ++ "(local.set $k0 (i32.shr_u (local.get $b6) (i32.const 2)))"
      , indent 2 ++ "(local.set $k1 (i32.or (i32.shl (i32.and (local.get $b6) (i32.const 3)) (i32.const 4)) (i32.shr_u (local.get $b7) (i32.const 4))))"
      , indent 2 ++ "(local.set $k2 (i32.shl (i32.and (local.get $b7) (i32.const 15)) (i32.const 2)))"
      , indent 2 ++ ";; write chars"
      , indent 2 ++ "(i32.store8 (i32.add (local.get $out) (i32.const 0)) (i32.load8_u (i32.add (i32.const 0) (local.get $i0))))"
      , indent 2 ++ "(i32.store8 (i32.add (local.get $out) (i32.const 1)) (i32.load8_u (i32.add (i32.const 0) (local.get $i1))))"
      , indent 2 ++ "(i32.store8 (i32.add (local.get $out) (i32.const 2)) (i32.load8_u (i32.add (i32.const 0) (local.get $i2))))"
      , indent 2 ++ "(i32.store8 (i32.add (local.get $out) (i32.const 3)) (i32.load8_u (i32.add (i32.const 0) (local.get $i3))))"
      , indent 2 ++ "(i32.store8 (i32.add (local.get $out) (i32.const 4)) (i32.load8_u (i32.add (i32.const 0) (local.get $j0))))"
      , indent 2 ++ "(i32.store8 (i32.add (local.get $out) (i32.const 5)) (i32.load8_u (i32.add (i32.const 0) (local.get $j1))))"
      , indent 2 ++ "(i32.store8 (i32.add (local.get $out) (i32.const 6)) (i32.load8_u (i32.add (i32.const 0) (local.get $j2))))"
      , indent 2 ++ "(i32.store8 (i32.add (local.get $out) (i32.const 7)) (i32.load8_u (i32.add (i32.const 0) (local.get $j3))))"
      , indent 2 ++ "(i32.store8 (i32.add (local.get $out) (i32.const 8)) (i32.load8_u (i32.add (i32.const 0) (local.get $k0))))"
      , indent 2 ++ "(i32.store8 (i32.add (local.get $out) (i32.const 9)) (i32.load8_u (i32.add (i32.const 0) (local.get $k1))))"
      , indent 2 ++ "(i32.store8 (i32.add (local.get $out) (i32.const 10)) (i32.load8_u (i32.add (i32.const 0) (local.get $k2))))"
      , indent 2 ++ "(i32.store8 (i32.add (local.get $out) (i32.const 11)) (i32.const 61))"
      , indent 1 ++ ")"
      , ""
      , indent 1 ++ ";; Base64-encode 26 bytes into 36 chars (with one '=' padding)."
      , indent 1 ++ "(func $b64_26 (param $in i32) (param $out i32)"
      , indent 2 ++ "(local $i i32)"
      , indent 2 ++ "(local $o i32)"
      , indent 2 ++ "(local $b0 i32) (local $b1 i32) (local $b2 i32)"
      , indent 2 ++ "(local $x0 i32) (local $x1 i32) (local $x2 i32) (local $x3 i32)"
      , indent 2 ++ "(local.set $i (i32.const 0))"
      , indent 2 ++ "(local.set $o (i32.const 0))"
      , indent 2 ++ "(block $exit"
      , indent 3 ++ "(loop $lp"
      , indent 4 ++ "(br_if $exit (i32.ge_u (local.get $i) (i32.const 24)))"
      , indent 4 ++ "(local.set $b0 (i32.load8_u (i32.add (local.get $in) (local.get $i))))"
      , indent 4 ++ "(local.set $b1 (i32.load8_u (i32.add (local.get $in) (i32.add (local.get $i) (i32.const 1)))))"
      , indent 4 ++ "(local.set $b2 (i32.load8_u (i32.add (local.get $in) (i32.add (local.get $i) (i32.const 2)))))"
      , indent 4 ++ "(local.set $x0 (i32.shr_u (local.get $b0) (i32.const 2)))"
      , indent 4 ++ "(local.set $x1 (i32.or (i32.shl (i32.and (local.get $b0) (i32.const 3)) (i32.const 4)) (i32.shr_u (local.get $b1) (i32.const 4))))"
      , indent 4 ++ "(local.set $x2 (i32.or (i32.shl (i32.and (local.get $b1) (i32.const 15)) (i32.const 2)) (i32.shr_u (local.get $b2) (i32.const 6))))"
      , indent 4 ++ "(local.set $x3 (i32.and (local.get $b2) (i32.const 63)))"
      , indent 4 ++ "(i32.store8 (i32.add (local.get $out) (local.get $o)) (i32.load8_u (i32.add (i32.const 0) (local.get $x0))))"
      , indent 4 ++ "(i32.store8 (i32.add (local.get $out) (i32.add (local.get $o) (i32.const 1))) (i32.load8_u (i32.add (i32.const 0) (local.get $x1))))"
      , indent 4 ++ "(i32.store8 (i32.add (local.get $out) (i32.add (local.get $o) (i32.const 2))) (i32.load8_u (i32.add (i32.const 0) (local.get $x2))))"
      , indent 4 ++ "(i32.store8 (i32.add (local.get $out) (i32.add (local.get $o) (i32.const 3))) (i32.load8_u (i32.add (i32.const 0) (local.get $x3))))"
      , indent 4 ++ "(local.set $i (i32.add (local.get $i) (i32.const 3)))"
      , indent 4 ++ "(local.set $o (i32.add (local.get $o) (i32.const 4)))"
      , indent 4 ++ "(br $lp)"
      , indent 3 ++ ")"
      , indent 2 ++ ")"
      , indent 2 ++ ";; final 2 bytes at i=24"
      , indent 2 ++ "(local.set $b0 (i32.load8_u (i32.add (local.get $in) (i32.const 24))))"
      , indent 2 ++ "(local.set $b1 (i32.load8_u (i32.add (local.get $in) (i32.const 25))))"
      , indent 2 ++ "(local.set $x0 (i32.shr_u (local.get $b0) (i32.const 2)))"
      , indent 2 ++ "(local.set $x1 (i32.or (i32.shl (i32.and (local.get $b0) (i32.const 3)) (i32.const 4)) (i32.shr_u (local.get $b1) (i32.const 4))))"
      , indent 2 ++ "(local.set $x2 (i32.shl (i32.and (local.get $b1) (i32.const 15)) (i32.const 2)))"
      , indent 2 ++ "(i32.store8 (i32.add (local.get $out) (local.get $o)) (i32.load8_u (i32.add (i32.const 0) (local.get $x0))))"
      , indent 2 ++ "(i32.store8 (i32.add (local.get $out) (i32.add (local.get $o) (i32.const 1))) (i32.load8_u (i32.add (i32.const 0) (local.get $x1))))"
      , indent 2 ++ "(i32.store8 (i32.add (local.get $out) (i32.add (local.get $o) (i32.const 2))) (i32.load8_u (i32.add (i32.const 0) (local.get $x2))))"
      , indent 2 ++ "(i32.store8 (i32.add (local.get $out) (i32.add (local.get $o) (i32.const 3))) (i32.const 61))"
      , indent 1 ++ ")"
      , ""
      , indent 1 ++ ";; Return helpers (JSON ABI)."
      , indent 1 ++ "(func $ret_error_badmsg (result i32)"
      , indent 2 ++ "(local $r i32)"
      , indent 2 ++ "(local $off i32)"
      , indent 2 ++ "(local.set $r (call $allocate (i32.const 19)))"
      , indent 2 ++ "(local.set $off (call $region_offset (local.get $r)))"
      , indent 2 ++ "(call $memcpy (local.get $off) (i32.const 320) (i32.const 19))"
      , indent 2 ++ "(local.get $r)"
      , indent 1 ++ ")"
      , indent 1 ++ "(func $ret_query (param $res i64) (result i32)"
      , indent 2 ++ "(local $r i32)"
      , indent 2 ++ "(local $off i32)"
      , indent 2 ++ "(local.set $r (call $allocate (i32.const 45)))"
      , indent 2 ++ "(local.set $off (call $region_offset (local.get $r)))"
      , indent 2 ++ "(call $memcpy (local.get $off) (i32.const 80) (i32.const 7))"
      , indent 2 ++ ";; inner JSON in scratch @512: {\"res_b64\":\"<12b64>\"}"
      , indent 2 ++ "(call $memcpy (i32.const 512) (i32.const 360) (i32.const 12))"
      , indent 2 ++ "(call $b64_i64 (local.get $res) (i32.add (i32.const 512) (i32.const 12)))"
      , indent 2 ++ "(call $memcpy (i32.add (i32.const 512) (i32.const 24)) (i32.const 380) (i32.const 2))"
      , indent 2 ++ ";; outer base64 into ContractResult<Binary> string"
      , indent 2 ++ "(call $b64_26 (i32.const 512) (i32.add (local.get $off) (i32.const 7)))"
      , indent 2 ++ "(call $memcpy (i32.add (local.get $off) (i32.const 43)) (i32.const 100) (i32.const 2))"
      , indent 2 ++ "(local.get $r)"
      , indent 1 ++ ")"
      , indent 1 ++ "(func $ret_execute (param $res i64) (result i32)"
      , indent 2 ++ "(local $r i32)"
      , indent 2 ++ "(local $off i32)"
      , indent 2 ++ "(local.set $r (call $allocate (i32.const 72)))"
      , indent 2 ++ "(local.set $off (call $region_offset (local.get $r)))"
      , indent 2 ++ "(call $memcpy (local.get $off) (i32.const 120) (i32.const 57))"
      , indent 2 ++ "(call $b64_i64 (local.get $res) (i32.add (local.get $off) (i32.const 57)))"
      , indent 2 ++ "(call $memcpy (i32.add (local.get $off) (i32.const 69)) (i32.const 200) (i32.const 3))"
      , indent 2 ++ "(local.get $r)"
      , indent 1 ++ ")"
      , indent 1 ++ "(func $ret_instantiate_ok (result i32)"
      , indent 2 ++ "(local $r i32)"
      , indent 2 ++ "(local $off i32)"
      , indent 2 ++ "(local.set $r (call $allocate (i32.const 62)))"
      , indent 2 ++ "(local.set $off (call $region_offset (local.get $r)))"
      , indent 2 ++ "(call $memcpy (local.get $off) (i32.const 220) (i32.const 62))"
      , indent 2 ++ "(local.get $r)"
      , indent 1 ++ ")"
      ]
  let body := String.intercalate "\n\n" (funs.map emitFun)
  let entrypoints :=
    String.intercalate "\n"
      [ ""
      , indent 1 ++ "(func (export \"instantiate\") (param $env i32) (param $info i32) (param $msg i32) (result i32)"
      , indent 2 ++ "(drop (local.get $msg))"
      , indent 2 ++ "(call $deallocate (local.get $msg))"
      , indent 2 ++ "(call $deallocate (local.get $info))"
      , indent 2 ++ "(call $deallocate (local.get $env))"
      , indent 2 ++ "(call $ret_instantiate_ok)"
      , indent 1 ++ ")"
      , ""
      , indent 1 ++ "(func (export \"execute\") (param $env i32) (param $info i32) (param $msg i32) (result i32)"
      , indent 2 ++ "(local $sel i32)"
      , indent 2 ++ "(local $x i64)"
      , indent 2 ++ "(local $y i64)"
      , indent 2 ++ "(local $res i64)"
      , indent 2 ++ "(call $parse_fields (local.get $msg))"
      , indent 2 ++ "(local.set $x (global.get $g_x))"
      , indent 2 ++ "(local.set $y (global.get $g_y))"
      , indent 2 ++ "(if (i32.eq (global.get $g_have_x) (i32.const 0))"
      , indent 3 ++ "(then (return (call $ret_error_badmsg)))"
      , indent 2 ++ ")"
      , indent 2 ++ "(if (i32.eq (global.get $g_have_fn) (i32.const 1))"
      , indent 3 ++ "(then (local.set $sel (global.get $g_fn)))"
      , indent 3 ++ "(else"
      , indent 4 ++ "(if (i32.eq (global.get $g_have_tag) (i32.const 1))"
      , indent 5 ++ "(then (local.set $sel (global.get $g_tag)))"
      , indent 5 ++ "(else (return (call $ret_error_badmsg)))"
      , indent 4 ++ ")"
      , indent 3 ++ ")"
      , indent 2 ++ ")"
      , indent 2 ++ "(if (i32.eq (local.get $sel) (i32.const 0))"
      , indent 3 ++ "(then (local.set $res (call $heyting_add1 (local.get $x))))"
      , indent 3 ++ "(else"
      , indent 4 ++ "(if (i32.eq (local.get $sel) (i32.const 1))"
      , indent 5 ++ "(then (local.set $res (call $heyting_add2 (local.get $x) (local.get $y))))"
      , indent 5 ++ "(else"
      , indent 6 ++ "(if (i32.eq (local.get $sel) (i32.const 2))"
      , indent 7 ++ "(then (local.set $res (call $heyting_if_demo (local.get $x))))"
      , indent 7 ++ "(else"
      , indent 8 ++ "(if (i32.eq (local.get $sel) (i32.const 3))"
      , indent 9 ++ "(then (local.set $res (call $heyting_while_sum (local.get $x))))"
      , indent 9 ++ "(else (return (call $ret_error_badmsg)))"
      , indent 8 ++ ")"
      , indent 7 ++ ")"
      , indent 6 ++ ")"
      , indent 5 ++ ")"
      , indent 4 ++ ")"
      , indent 3 ++ ")"
      , indent 2 ++ ")"
      , indent 2 ++ "(call $deallocate (local.get $msg))"
      , indent 2 ++ "(call $deallocate (local.get $info))"
      , indent 2 ++ "(call $deallocate (local.get $env))"
      , indent 2 ++ "(call $ret_execute (local.get $res))"
      , indent 1 ++ ")"
      , ""
      , indent 1 ++ "(func (export \"query\") (param $env i32) (param $msg i32) (result i32)"
      , indent 2 ++ "(local $sel i32)"
      , indent 2 ++ "(local $x i64)"
      , indent 2 ++ "(local $y i64)"
      , indent 2 ++ "(local $res i64)"
      , indent 2 ++ "(call $parse_fields (local.get $msg))"
      , indent 2 ++ "(local.set $x (global.get $g_x))"
      , indent 2 ++ "(local.set $y (global.get $g_y))"
      , indent 2 ++ "(if (i32.eq (global.get $g_have_x) (i32.const 0))"
      , indent 3 ++ "(then (return (call $ret_error_badmsg)))"
      , indent 2 ++ ")"
      , indent 2 ++ "(if (i32.eq (global.get $g_have_fn) (i32.const 1))"
      , indent 3 ++ "(then (local.set $sel (global.get $g_fn)))"
      , indent 3 ++ "(else"
      , indent 4 ++ "(if (i32.eq (global.get $g_have_tag) (i32.const 1))"
      , indent 5 ++ "(then (local.set $sel (global.get $g_tag)))"
      , indent 5 ++ "(else (return (call $ret_error_badmsg)))"
      , indent 4 ++ ")"
      , indent 3 ++ ")"
      , indent 2 ++ ")"
      , indent 2 ++ "(if (i32.eq (local.get $sel) (i32.const 0))"
      , indent 3 ++ "(then (local.set $res (call $heyting_add1 (local.get $x))))"
      , indent 3 ++ "(else"
      , indent 4 ++ "(if (i32.eq (local.get $sel) (i32.const 1))"
      , indent 5 ++ "(then (local.set $res (call $heyting_add2 (local.get $x) (local.get $y))))"
      , indent 5 ++ "(else"
      , indent 6 ++ "(if (i32.eq (local.get $sel) (i32.const 2))"
      , indent 7 ++ "(then (local.set $res (call $heyting_if_demo (local.get $x))))"
      , indent 7 ++ "(else"
      , indent 8 ++ "(if (i32.eq (local.get $sel) (i32.const 3))"
      , indent 9 ++ "(then (local.set $res (call $heyting_while_sum (local.get $x))))"
      , indent 9 ++ "(else (return (call $ret_error_badmsg)))"
      , indent 8 ++ ")"
      , indent 7 ++ ")"
      , indent 6 ++ ")"
      , indent 5 ++ ")"
      , indent 4 ++ ")"
      , indent 3 ++ ")"
      , indent 2 ++ ")"
      , indent 2 ++ "(call $deallocate (local.get $msg))"
      , indent 2 ++ "(call $deallocate (local.get $env))"
      , indent 2 ++ "(call $ret_query (local.get $res))"
      , indent 1 ++ ")"
      ]
  String.intercalate "\n" [header, body, entrypoints, ")", ""]

end WasmMini
end HeytingLean
