import Mathlib.Algebra.Polynomial.Laurent
import HeytingLean.Topology.Knot.Bracket
import HeytingLean.Topology.Knot.Reidemeister

/-!
# Knot theory: Kauffman bracket valued in Mathlib Laurent polynomials (Phase 1 proof layer)

`HeytingLean.Topology.Knot.Bracket` computes the Kauffman bracket into the executable type
`HeytingLean.Topology.Knot.LaurentPoly`.

For Phase 1 Reidemeister proofs we want standard ring rewriting, so this module provides a
proof-oriented bracket computation with the **same combinatorial smoothing algorithm** but valued
in Mathlib’s `LaurentPolynomial ℤ` (notation: `ℤ[T;T⁻¹]`).
-/

namespace HeytingLean
namespace Topology
namespace Knot

open Std

namespace Kauffman

open scoped LaurentPolynomial

abbrev PolyML := ℤ[T;T⁻¹]

noncomputable section

/-- The Kauffman bracket parameter `A` as a Laurent monomial (Mathlib layer). -/
def AML : PolyML :=
  LaurentPolynomial.T 1

/-- The Laurent monomial `A⁻¹` (Mathlib layer). -/
def AinvML : PolyML :=
  LaurentPolynomial.T (-1)

/-- The Kauffman bracket loop factor `d = -A^2 - A^{-2}` (Mathlib layer). -/
def dML : PolyML :=
  -(LaurentPolynomial.T 2) - (LaurentPolynomial.T (-2))

/--
Core smoothing step for the last crossing, copied from the executable implementation and kept
computable (it only rewires the `arcNbr` involution and updates the free-loop count).

This is intentionally exposed (not `private`) so Phase‑1 proof files can reason about its output.
-/
def smoothLastCoreML_smooth (n : Nat) (isB : Bool) (idx : Nat) : Nat :=
  let base := (4 * n) - 4
  let pos := idx % 4
  if isB then
    match pos with
    | 0 => base + 3
    | 1 => base + 2
    | 2 => base + 1
    | _ => base + 0
  else
    match pos with
    | 0 => base + 1
    | 1 => base + 0
    | 2 => base + 3
    | _ => base + 2

def smoothLastCoreML_deltaLoops (n : Nat) (arcNbr : Array Nat) (isB : Bool) : Nat := Id.run do
  let base := (4 * n) - 4

  let smooth (idx : Nat) : Nat :=
    smoothLastCoreML_smooth n isB idx

  -- Count new free loops created entirely inside the removed region (4 half-edges).
  --
  -- We compute connected components of the 4-node graph generated by:
  -- - the `arcNbr` involution (restricted to the removed region), and
  -- - the smoothing involution `smooth`.
  --
  -- A component contributes a new free loop iff it does not touch any external half-edge.
  let arcOff (off : Nat) : Option Nat :=
    let a := arcNbr[base + off]!
    if a < base then
      none
    else
      some (a - base)

  let smoothOff (off : Nat) : Nat :=
    (smooth (base + off)) - base

  let neighbors (off : Nat) : List Nat :=
    match arcOff off with
    | none => [smoothOff off]
    | some a => [smoothOff off, a]

  let rec explore (fuel : Nat) (todo : List Nat) (seen : List Nat) : List Nat :=
    match fuel, todo with
    | 0, _ => seen
    | _, [] => seen
    | Nat.succ fuel, v :: rest =>
        if v ∈ seen then
          explore fuel rest seen
        else
          explore fuel (neighbors v ++ rest) (v :: seen)

  let mut seen : List Nat := []
  let mut deltaLoops : Nat := 0
  for off in [0:4] do
    if off ∈ seen then
      continue
    let comp := explore 8 [off] []
    for v in comp do
      if v ∉ seen then
        seen := v :: seen
    let touchesExternal := comp.any (fun v => arcNbr[base + v]! < base)
    if !touchesExternal then
      deltaLoops := deltaLoops + 1

  return deltaLoops

def smoothLastCoreML_exitFromExternalAux
    (n : Nat) (arcNbr : Array Nat) (isB : Bool) (x : Nat) : Nat → Nat → Nat
  | 0, _ => x
  | Nat.succ fuel, r =>
      let base := (4 * n) - 4
      let r' := smoothLastCoreML_smooth n isB r
      let y := arcNbr[r']!
      if y < base then
        y
      else
        smoothLastCoreML_exitFromExternalAux n arcNbr isB x fuel y

def smoothLastCoreML_exitFromExternal (n : Nat) (arcNbr : Array Nat) (isB : Bool) (x : Nat) : Nat :=
  smoothLastCoreML_exitFromExternalAux n arcNbr isB x 4 (arcNbr[x]!)

def smoothLastCoreML_rewire (n : Nat) (arcNbr : Array Nat) (isB : Bool) : Array Nat :=
  let base := (4 * n) - 4
  -- Proof-friendly definition: for each external half-edge `x < base`, either keep the original
  -- pairing (`arcNbr[x]! < base`) or, if `x` was incident to the removed region, jump across the
  -- smoothing via `exitFromExternal`.
  --
  -- For well-formed inputs (`PDGraph.Valid`), this is extensionally equal to the executable-style
  -- loop that only rewires the at-most-4 incident external endpoints.
  Array.ofFn fun x : Fin base =>
    let i := x.1
    let p := arcNbr[i]!
    if p < base then
      p
    else
      smoothLastCoreML_exitFromExternal n arcNbr isB i

def smoothLastCoreML (freeLoops : Nat) (n : Nat) (arcNbr : Array Nat) (isB : Bool) :
    (Nat × Array Nat) :=
  let deltaLoops := smoothLastCoreML_deltaLoops n arcNbr isB
  let newNbr := smoothLastCoreML_rewire n arcNbr isB
  (freeLoops + deltaLoops, newNbr)

noncomputable def bracketCoreML (freeLoops : Nat) : Nat → Array Nat → PolyML
  | 0, _ =>
      if freeLoops = 0 then
        1
      else
        dML ^ (freeLoops - 1)
  | Nat.succ n', arcNbr =>
      let (freeA, nbrA) := smoothLastCoreML freeLoops (Nat.succ n') arcNbr false
      let (freeB, nbrB) := smoothLastCoreML freeLoops (Nat.succ n') arcNbr true
      (AML * bracketCoreML freeA n' nbrA) + (AinvML * bracketCoreML freeB n' nbrB)

private noncomputable def bracketBaseML (freeLoops : Nat) : PolyML :=
  if freeLoops = 0 then
    1
  else
    dML ^ (freeLoops - 1)

theorem bracketBaseML_eq (freeLoops : Nat) :
    bracketBaseML freeLoops = (if freeLoops = 0 then (1 : PolyML) else dML ^ (freeLoops - 1)) := by
  rfl

/-- Increment the `freeLoops` counter by `k` (keeping crossings and wiring unchanged). -/
def _root_.HeytingLean.Topology.Knot.PDGraph.addFreeLoops
    (g : _root_.HeytingLean.Topology.Knot.PDGraph) (k : Nat) :
    _root_.HeytingLean.Topology.Knot.PDGraph :=
  { g with freeLoops := g.freeLoops + k }

@[simp] theorem _root_.HeytingLean.Topology.Knot.PDGraph.addFreeLoops_freeLoops
    (g : _root_.HeytingLean.Topology.Knot.PDGraph) (k : Nat) :
    (g.addFreeLoops k).freeLoops = g.freeLoops + k := by
  rfl

@[simp] theorem _root_.HeytingLean.Topology.Knot.PDGraph.addFreeLoops_n
    (g : _root_.HeytingLean.Topology.Knot.PDGraph) (k : Nat) :
    (g.addFreeLoops k).n = g.n := by
  rfl

@[simp] theorem _root_.HeytingLean.Topology.Knot.PDGraph.addFreeLoops_arcNbr
    (g : _root_.HeytingLean.Topology.Knot.PDGraph) (k : Nat) :
    (g.addFreeLoops k).arcNbr = g.arcNbr := by
  rfl

@[simp] theorem _root_.HeytingLean.Topology.Knot.PDGraph.numHalfEdges_addFreeLoops
    (g : _root_.HeytingLean.Topology.Knot.PDGraph) (k : Nat) :
    (g.addFreeLoops k).numHalfEdges = g.numHalfEdges := by
  simp [PDGraph.numHalfEdges]

@[simp] theorem _root_.HeytingLean.Topology.Knot.PDGraph.validate_addFreeLoops
    (g : _root_.HeytingLean.Topology.Knot.PDGraph) (k : Nat) :
    _root_.HeytingLean.Topology.Knot.PDGraph.validate (g.addFreeLoops k) =
      _root_.HeytingLean.Topology.Knot.PDGraph.validate g := by
  rfl

/--
Mathlib-layer bracket evaluation as an `Except`-valued recursion on `PDGraph`.

This is the proof-layer analogue of the executable `Kauffman.bracketGraph`, with one additional
convenience: if the *last* crossing is recognized as a Reidemeister-I curl (`r1RemoveLast`), we
short-circuit using the standard scaling factors `-(A^3)` / `-(A⁻³)`.

Implementation note: we define an internal recursion with an explicit `fuel : Nat` parameter
(initialized to `g.n`). This avoids any termination proof obligations while keeping the definition
transparent for rewriting in Phase‑1 proofs.
-/
noncomputable def bracketGraphMLAux : Nat → PDGraph → Except String PolyML
  | 0, g => do
      PDGraph.validate g
      if g.n = 0 then
        return bracketBaseML g.freeLoops
      else
        throw "bracketGraphML: fuel exhausted"
  | Nat.succ fuel, g => do
      PDGraph.validate g
      if g.n = 0 then
        return bracketBaseML g.freeLoops
      else
        match Reidemeister.r1RemoveLast g .pos with
        | .ok g0 =>
            let b ← bracketGraphMLAux fuel g0
            return (-(AML ^ 3 : PolyML)) * b
        | .error _ =>
            match Reidemeister.r1RemoveLast g .neg with
            | .ok g0 =>
                let b ← bracketGraphMLAux fuel g0
                return (-(AinvML ^ 3 : PolyML)) * b
            | .error _ =>
                match Reidemeister.r2RemoveLast g with
                | .ok g0 =>
                    match fuel with
                    | 0 =>
                        throw "bracketGraphML: fuel exhausted"
                    | Nat.succ fuel2 =>
                        bracketGraphMLAux fuel2 g0
                | .error _ =>
                -- General skein step on the last crossing.
                let n' := g.n - 1
                let (freeA, nbrA) := smoothLastCoreML g.freeLoops g.n g.arcNbr false
                let (freeB, nbrB) := smoothLastCoreML g.freeLoops g.n g.arcNbr true
                let gA : PDGraph := { freeLoops := freeA, n := n', arcNbr := nbrA }
                let gB : PDGraph := { freeLoops := freeB, n := n', arcNbr := nbrB }
                let a ← bracketGraphMLAux fuel gA
                let b ← bracketGraphMLAux fuel gB
                return (AML * a) + (AinvML * b)

noncomputable def bracketGraphML (g : PDGraph) : Except String PolyML :=
  bracketGraphMLAux g.n g

theorem bracketGraphMLAux_base
    (fuel freeLoops : Nat) :
    bracketGraphMLAux fuel { freeLoops := freeLoops, n := 0, arcNbr := (#[] : Array Nat) }
      =
    .ok (if freeLoops = 0 then (1 : PolyML) else dML ^ (freeLoops - 1)) := by
  cases fuel <;>
    simp [bracketGraphMLAux, PDGraph.validate, PDGraph.numHalfEdges, bracketBaseML_eq,
      Bind.bind, Except.bind, Pure.pure, Except.pure]

theorem bracketGraphMLAux_base_succ_mul_d
    (fuel freeLoops : Nat) (h : freeLoops ≠ 0) :
    bracketGraphMLAux fuel { freeLoops := freeLoops + 1, n := 0, arcNbr := (#[] : Array Nat) }
      =
    (do
      let p ← bracketGraphMLAux fuel { freeLoops := freeLoops, n := 0, arcNbr := (#[] : Array Nat) }
      return dML * p) := by
  -- Reduce to the explicit closed form from `bracketGraphMLAux_base`.
  cases freeLoops with
  | zero =>
      cases (h rfl)
  | succ k =>
      -- `d^(k+1) = d * d^k`.
      simp [bracketGraphMLAux_base, Bind.bind, Except.bind, Pure.pure, Except.pure, pow_succ, mul_comm]

private theorem bracketBaseML_addFreeLoops
    (freeLoops k : Nat) (h : freeLoops ≠ 0) :
    bracketBaseML (freeLoops + k) = (dML ^ k) * bracketBaseML freeLoops := by
  cases freeLoops with
  | zero =>
      cases (h rfl)
  | succ t =>
      -- `d^(t+k) = d^k * d^t`.
      calc
        bracketBaseML (Nat.succ t + k) = dML ^ (t + k) := by
          simp [bracketBaseML, Nat.succ_add]
        _ = dML ^ (k + t) := by
          simp [Nat.add_comm]
        _ = (dML ^ k) * (dML ^ t) := by
          simp [pow_add]
        _ = (dML ^ k) * bracketBaseML (Nat.succ t) := by
          simp [bracketBaseML]

private theorem bracketCoreML_addFreeLoops
    (freeLoops n k : Nat) (arcNbr : Array Nat) (h : freeLoops ≠ 0) :
    bracketCoreML (freeLoops + k) n arcNbr = (dML ^ k) * bracketCoreML freeLoops n arcNbr := by
  induction n generalizing freeLoops arcNbr with
  | zero =>
      -- Base case is exactly the unlink convention scaling (requires `freeLoops ≠ 0`).
      rw [bracketCoreML, bracketCoreML]
      simpa [bracketBaseML_eq, mul_comm] using bracketBaseML_addFreeLoops freeLoops k h
  | succ n ih =>
      -- One skein step preserves the multiplicative `dML^k` factor on both branches.
      cases hSA : smoothLastCoreML freeLoops (Nat.succ n) arcNbr false with
      | mk freeA nbrA =>
          cases hSB : smoothLastCoreML freeLoops (Nat.succ n) arcNbr true with
          | mk freeB nbrB =>
              have hSA1 : (smoothLastCoreML freeLoops (Nat.succ n) arcNbr false).1 = freeA := by
                simp [hSA]
              have hSA2 : (smoothLastCoreML freeLoops (Nat.succ n) arcNbr false).2 = nbrA := by
                simp [hSA]
              have hSB1 : (smoothLastCoreML freeLoops (Nat.succ n) arcNbr true).1 = freeB := by
                simp [hSB]
              have hSB2 : (smoothLastCoreML freeLoops (Nat.succ n) arcNbr true).2 = nbrB := by
                simp [hSB]
              have hSAk :
                  smoothLastCoreML (freeLoops + k) (Nat.succ n) arcNbr false = (freeA + k, nbrA) := by
                calc
                  smoothLastCoreML (freeLoops + k) (Nat.succ n) arcNbr false
                      = ((smoothLastCoreML freeLoops (Nat.succ n) arcNbr false).1 + k,
                          (smoothLastCoreML freeLoops (Nat.succ n) arcNbr false).2) := by
                          simp [smoothLastCoreML, Nat.add_assoc, Nat.add_comm]
                  _ = (freeA + k, nbrA) := by simp [hSA1, hSA2]
              have hSBk :
                  smoothLastCoreML (freeLoops + k) (Nat.succ n) arcNbr true = (freeB + k, nbrB) := by
                calc
                  smoothLastCoreML (freeLoops + k) (Nat.succ n) arcNbr true
                      = ((smoothLastCoreML freeLoops (Nat.succ n) arcNbr true).1 + k,
                          (smoothLastCoreML freeLoops (Nat.succ n) arcNbr true).2) := by
                          simp [smoothLastCoreML, Nat.add_assoc, Nat.add_comm]
                  _ = (freeB + k, nbrB) := by simp [hSB1, hSB2]
              have hApos : 0 < freeA := by
                have hpos : 0 < freeLoops := Nat.pos_of_ne_zero h
                have : 0 < (smoothLastCoreML freeLoops (Nat.succ n) arcNbr false).1 := by
                  simpa [smoothLastCoreML] using Nat.lt_of_lt_of_le hpos (Nat.le_add_right freeLoops _)
                simpa [hSA] using this
              have hBpos : 0 < freeB := by
                have hpos : 0 < freeLoops := Nat.pos_of_ne_zero h
                have : 0 < (smoothLastCoreML freeLoops (Nat.succ n) arcNbr true).1 := by
                  simpa [smoothLastCoreML] using Nat.lt_of_lt_of_le hpos (Nat.le_add_right freeLoops _)
                simpa [hSB] using this
              have hAne : freeA ≠ 0 := Nat.ne_of_gt hApos
              have hBne : freeB ≠ 0 := Nat.ne_of_gt hBpos
              simp [bracketCoreML, hSA, hSB, hSAk, hSBk]
              rw [ih freeA nbrA hAne, ih freeB nbrB hBne]
              ring
-- WIP(2026-01-24): A general lemma scaling `bracketGraphMLAux` by `dML^k` under
-- `PDGraph.addFreeLoops` is still pending (needed for the TL₃ bridge / Phase‑1 R3 theorem).
-- The foundational pieces above (`PDGraph.addFreeLoops`, `validate_addFreeLoops`,
-- `bracketBaseML_addFreeLoops`) are kept in-tree; see:
-- `WIP/kauffman_phase1_milestone3_tl3_bridge_2026-01-24/free_loops_dML_scaling_WIP.md`.

end

end Kauffman

end Knot
end Topology
end HeytingLean
