import Mathlib.Order.Heyting.Basic
import Mathlib.Order.Basic
import HeytingLean.Logics.Modal.Kripke
import HeytingLean.Logics.Modal.S4

/-!
# Leanstral API Smoke Test — Lean-verified proofs

These proofs were generated by `labs-leanstral-2603` (Mistral) on 2026-03-17
and verified against the Lean 4 kernel.
-/

namespace HeytingLean.Tests.LeanstralSmoke

open HeytingLean.Logics.Modal

-- Test 1: S4 reflexivity — □φ at w implies φ at w
theorem box_implies_self_of_refl {W : Type*} {Var : Type*}
    (M : Model W Var) (hrefl : ∀ w, M.rel w w)
    (w : W) (φ : Formula Var)
    (h : satisfies M w (.box φ)) : satisfies M w φ := by
  have h2 : ∀ v, M.rel w v → satisfies M v φ := by
    simpa using h
  have h3 : M.rel w w := hrefl w
  exact h2 w h3

-- Test 2: Gödel translation of bot is bot
open HeytingLean.Logics.Modal.S4 in
theorem goedel_bot {Var : Type*} : goedelTranslation (Var := Var) .bot = .bot := by
  rfl

-- Test 3: K axiom
theorem k_axiom {W : Type*} {Var : Type*}
    (M : Model W Var) (w : W) (φ ψ : Formula Var)
    (h1 : satisfies M w (.box (.imp φ ψ)))
    (h2 : satisfies M w (.box φ))
    : satisfies M w (.box ψ) := by
  intro v hrel
  have h3 : satisfies M v (.imp φ ψ) := h1 v hrel
  have h4 : satisfies M v φ := h2 v hrel
  exact h3 h4

-- Test 4: Axiom 4 — □φ → □□φ in transitive frames
theorem box_box_of_trans {W : Type*} {Var : Type*}
    (M : Model W Var) (htrans : ∀ u v w, M.rel u v → M.rel v w → M.rel u w)
    (w : W) (φ : Formula Var)
    (h : satisfies M w (.box φ))
    : satisfies M w (.box (.box φ)) := by
  unfold satisfies at h ⊢
  intro v hv
  intro x hx
  have h2 : M.rel w x := htrans w v x hv hx
  exact h x h2

-- Test 5: IPC forcing monotonicity (persistence lemma)
section IPCForcing

inductive IPCFormula where
  | top : IPCFormula
  | bot : IPCFormula
  | var : Nat → IPCFormula
  | and : IPCFormula → IPCFormula → IPCFormula
  | or  : IPCFormula → IPCFormula → IPCFormula
  | imp : IPCFormula → IPCFormula → IPCFormula

structure IPCModel (W : Type) [Preorder W] where
  val : W → Nat → Prop
  mono_val : ∀ {w v : W}, w ≤ v → ∀ n, val w n → val v n

def IPCForces {W : Type} [Preorder W] (M : IPCModel W) : W → IPCFormula → Prop
  | _, .top => True
  | _, .bot => False
  | w, .var n => M.val w n
  | w, .and φ ψ => IPCForces M w φ ∧ IPCForces M w ψ
  | w, .or φ ψ => IPCForces M w φ ∨ IPCForces M w ψ
  | w, .imp φ ψ => ∀ v, w ≤ v → IPCForces M v φ → IPCForces M v ψ

theorem ipc_forces_mono {W : Type} [Preorder W] (M : IPCModel W)
    (φ : IPCFormula) (w v : W) (hwv : w ≤ v) (h : IPCForces M w φ)
    : IPCForces M v φ := by
  induction φ generalizing w v with
  | top => simp [IPCForces]
  | bot => simp [IPCForces] at h
  | var n =>
    simp [IPCForces] at h ⊢
    exact M.mono_val hwv n h
  | and φ ψ ih1 ih2 =>
    simp [IPCForces] at h ⊢
    exact ⟨ih1 w v hwv h.1, ih2 w v hwv h.2⟩
  | or φ ψ ih1 ih2 =>
    simp [IPCForces] at h ⊢
    cases h with
    | inl h1 => left; exact ih1 w v hwv h1
    | inr h2 => right; exact ih2 w v hwv h2
  | imp φ ψ _ih =>
    simp [IPCForces] at h ⊢
    intro u huv h2
    exact h u (le_trans hwv huv) h2

end IPCForcing

end HeytingLean.Tests.LeanstralSmoke
