import HeytingLean.LambdaIR.Add1EndToEnd
import HeytingLean.LambdaIR.Add1MiniCProof
import HeytingLean.LambdaIR.Add2EndToEnd
import HeytingLean.LambdaIR.Add2MiniCProof
import HeytingLean.LambdaIR.Compile
import HeytingLean.LambdaIR.NatExamplesRegistry
import HeytingLean.LambdaIR.Nat2ExamplesRegistry
import HeytingLean.LambdaIR.NatCompileFrag
import HeytingLean.LambdaIR.Nat2CompileFrag
import HeytingLean.LambdaIR.ToMiniC
import HeytingLean.MiniC.ToWasmMini
import HeytingLean.WasmMini.EmitWAT
import HeytingLean.WasmMini.Semantics

open HeytingLean
open HeytingLean.LambdaIR
open HeytingLean.LambdaIR.CertifiedCompile
open HeytingLean.LambdaIR.Add1EndToEnd
open HeytingLean.LambdaIR.Add1MiniCProof
open HeytingLean.LambdaIR.Add2EndToEnd
open HeytingLean.LambdaIR.Add2MiniCProof
open HeytingLean.LambdaIR.NatExamplesRegistry
open HeytingLean.LambdaIR.Nat2ExamplesRegistry
open HeytingLean.LambdaIR.NatCompileFrag
open HeytingLean.LambdaIR.Nat2CompileFrag
open HeytingLean.LambdaIR.ToMiniC

namespace HeytingLean.Tests

private def repoRoot : IO System.FilePath := do
  let cwd ← IO.currentDir
  if cwd.fileName == some "lean" then
    return cwd.parent.getD cwd
  else
    return cwd

private def runCmd? (cmd : String) (args : List String) (cwd : Option System.FilePath := none) :
    IO (Option IO.Process.Output) := do
  try
    let out ← IO.Process.output { cmd := cmd, args := args.toArray, cwd := cwd }
    return some out
  catch _ =>
    return none

private def hasCmd (cmd : String) : IO Bool := do
  match ← runCmd? "bash" ["-lc", s!"command -v {cmd} >/dev/null 2>&1"] with
  | some out => pure (out.exitCode == 0)
  | none => pure false

private def toolchainBinDir : IO System.FilePath := do
  let root ← repoRoot
  return root / "tools" / "wasm_toolchain" / "bin"

private def findTool? (name : String) : IO (Option System.FilePath) := do
  let binDir ← toolchainBinDir
  let cand := binDir / name
  if (← cand.pathExists) then
    return some cand
  if (← hasCmd name) then
    return some (System.FilePath.mk name)
  return none

private def writeFile (path : System.FilePath) (contents : String) : IO Unit := do
  let some parent := path.parent
    | throw <| IO.userError s!"could not compute parent directory for {path}"
  IO.FS.createDirAll parent
  IO.FS.writeFile path contents

private def wastScript (moduleWat : String) (tests : List String) : String :=
  let header :=
    String.intercalate "\n"
      [ ";; Generated by HeytingLean (MiniC WASM backend test)"
      , ";; Run: wasmtime wast kernel.wast"
      , ""
      ]
  let body := String.intercalate "\n" (tests.map (fun t => s!"(assert_return {t})"))
  String.intercalate "\n" [header, moduleWat.trim, "", body, ""]

private def runWasmtimeWast (wastPath : System.FilePath) : IO (Except String Unit) := do
  match ← findTool? "wasmtime" with
  | none => return .error "missing tool: wasmtime"
  | some exe =>
      match ← runCmd? exe.toString ["wast", wastPath.toString] with
      | none => return .error "failed to spawn wasmtime"
      | some out =>
          if out.exitCode == 0 then
            return .ok ()
          else
            return .error s!"wasmtime failed rc={out.exitCode}\n{out.stderr.trim}"

private def checkWasmMiniAgainstLean : IO Unit := do
  let inputs : List Nat := [0, 1, 2, 5, 10, 41]

  for ex in NatExamplesRegistry.examples do
    match compileNatFun ex.funName ex.paramName ex.term with
    | Except.error msg =>
        throw <| IO.userError s!"LambdaIR→MiniC compile error for {ex.funName}: {msg}"
    | Except.ok fn => do
        let wasmFn := HeytingLean.MiniC.ToWasmMini.compileFun fn
        for n in inputs do
        let got := HeytingLean.WasmMini.runFun wasmFn [Int.ofNat n]
        let expected := Int.ofNat (ex.leanF n)
        if got = some expected then
          pure ()
        else
          throw <|
            IO.userError
              s!"MiniC→WasmMini mismatch for {ex.funName}({n}): expected {expected}, got {got}"

  for ex in Nat2ExamplesRegistry.examples do
    let fn := compileNat2FunFrag ex.funName ex.param1 ex.param2 ex.term
    let wasmFn := HeytingLean.MiniC.ToWasmMini.compileFun fn
    for x in inputs do
      for y in inputs do
        let got := HeytingLean.WasmMini.runFun wasmFn [Int.ofNat x, Int.ofNat y]
        let expected := Int.ofNat (ex.leanF x y)
        if got = some expected then
          pure ()
        else
          throw <|
            IO.userError
              s!"MiniC→WasmMini mismatch for {ex.funName}({x},{y}): expected {expected}, got {got}"

  -- Statement-level smoke: `if_` and `while` examples (beyond expression-only Nat fragments).
  let ifDemoMinic : HeytingLean.MiniC.Fun :=
    { name := "heyting_if_demo"
      params := ["x"]
      body :=
        HeytingLean.MiniC.Stmt.if_
          (HeytingLean.MiniC.Expr.le (.var "x") (.intLit 0))
          (.return (.intLit 111))
          (.return (.intLit 222)) }

  let whileSumMinic : HeytingLean.MiniC.Fun :=
    { name := "heyting_while_sum"
      params := ["x"]
      body :=
        .seq (.assign "i" (.intLit 0))
          (.seq (.assign "acc" (.intLit 0))
            (.seq
              (.while (.le (.var "i") (.var "x"))
                (.seq
                  (.assign "acc" (.add (.var "acc") (.var "i")))
                  (.assign "i" (.add (.var "i") (.intLit 1)))))
              (.return (.var "acc")))) }

  let sumUpTo (n : Nat) : Nat :=
    (List.range (n + 1)).foldl (fun acc k => acc + k) 0

  let wasmIf := HeytingLean.MiniC.ToWasmMini.compileFun ifDemoMinic
  let wasmWhile := HeytingLean.MiniC.ToWasmMini.compileFun whileSumMinic
  for n in inputs do
    let gotIf := HeytingLean.WasmMini.runFun wasmIf [Int.ofNat n]
    let expectedIf : Int := if n = 0 then 111 else 222
    if gotIf = some expectedIf then
      pure ()
    else
      throw <| IO.userError s!"MiniC→WasmMini mismatch for heyting_if_demo({n}): expected {expectedIf}, got {gotIf}"

    let gotWhile := HeytingLean.WasmMini.runFun wasmWhile [Int.ofNat n]
    let expectedWhile : Int := Int.ofNat (sumUpTo n)
    if gotWhile = some expectedWhile then
      pure ()
    else
      throw <|
        IO.userError s!"MiniC→WasmMini mismatch for heyting_while_sum({n}): expected {expectedWhile}, got {gotWhile}"

private def checkWasmtimeOracle : IO Unit := do
  let root ← repoRoot
  let outDir := root / "dist" / "test_minic_wasm_backend"
  let watPath := outDir / "kernel.wat"
  let wastPath := outDir / "kernel.wast"

  -- Keep the wasmtime check small and deterministic: a tiny module + a few asserts.
  let demo : List ((String × List Int) × Int) :=
    [ (("heyting_add1", [41]), 42)
    , (("heyting_add2", [20, 22]), 42)
    , (("heyting_if_demo", [0]), 111)
    , (("heyting_if_demo", [1]), 222)
    , (("heyting_while_sum", [5]), 15)
    , (("heyting_while_sum", [10]), 55)
    ]

  -- Compile the same kernels used by `minic_wasm_export` to avoid duplication.
  let add1Minic :=
    (compileNat1Fun (funName := "heyting_add1") (paramName := "x") (t := termAdd1IR) termAdd1_isNatFun).val
  let add2Minic :=
    (compileNat2Fun (funName := "heyting_add2") (t := termAdd2IR) termAdd2_isNat2Fun).val
  let ifDemoMinic : HeytingLean.MiniC.Fun :=
    { name := "heyting_if_demo"
      params := ["x"]
      body :=
        HeytingLean.MiniC.Stmt.if_
          (HeytingLean.MiniC.Expr.le (.var "x") (.intLit 0))
          (.return (.intLit 111))
          (.return (.intLit 222)) }
  let whileSumMinic : HeytingLean.MiniC.Fun :=
    { name := "heyting_while_sum"
      params := ["x"]
      body :=
        .seq (.assign "i" (.intLit 0))
          (.seq (.assign "acc" (.intLit 0))
            (.seq
              (.while (.le (.var "i") (.var "x"))
                (.seq
                  (.assign "acc" (.add (.var "acc") (.var "i")))
                  (.assign "i" (.add (.var "i") (.intLit 1)))))
              (.return (.var "acc")))) }
  let funsWasm : List HeytingLean.WasmMini.Fun :=
    [ HeytingLean.MiniC.ToWasmMini.compileFun add1Minic
    , HeytingLean.MiniC.ToWasmMini.compileFun add2Minic
    , HeytingLean.MiniC.ToWasmMini.compileFun ifDemoMinic
    , HeytingLean.MiniC.ToWasmMini.compileFun whileSumMinic
    ]

  let wat := HeytingLean.WasmMini.emitModule funsWasm
  writeFile watPath wat

  let tests : List String :=
    demo.map (fun ((name, args), expected) =>
      let argsStr := String.intercalate " " (args.map (fun a => s!"(i64.const {a})"))
      s!"(invoke \"{name}\" {argsStr}) (i64.const {expected})"
    )
  writeFile wastPath (wastScript wat tests)

  match ← runWasmtimeWast wastPath with
  | .ok () =>
      IO.println "wasmtime oracle check: ok"
  | .error err =>
      IO.eprintln s!"wasmtime oracle check: SKIP ({err})"

/-- Entry point for `lake exe test_minic_wasm_backend`. -/
def main (_args : List String) : IO UInt32 := do
  try
    checkWasmMiniAgainstLean
    IO.println "MiniC→WasmMini semantics check: ok"
    checkWasmtimeOracle
    IO.println "MiniC WASM backend test passed"
    pure 0
  catch e =>
    IO.eprintln e
    pure 1

end HeytingLean.Tests

/-- expose entry point for lake target. -/
def main (args : List String) : IO UInt32 :=
  HeytingLean.Tests.main args
