import Mathlib.Logic.Relation
import HeytingLean.ATheory.AssemblySpace

/-
# AssemblyGraph bridge

	This module provides a minimal bridge structure from the abstract assembly
	space `ASpace` to a generic "opens" operator on its vertex set. The goal is
	to establish a stable interface; later extensions can connect `toOpens` to a
	concrete Alexandroff-interior construction and to existing graph lenses.
	-/

namespace HeytingLean
namespace Bridges
namespace Assembly

open HeytingLean.ATheory

universe u

/-- Bridge from an assembly space to a generic opens-style operator on `Set G.V`.

Here `toOpens` behaves as an Alexandroff-style interior operator with the
basic deflationary law `toOpens U ⊆ U`. -/
structure AssemblyGraphBridge (α : Type u) where
  G       : ASpace α
  toOpens : Set G.V → Set G.V
  /-- Deflationary law: `toOpens U ⊆ U`. -/
  le_toOpens : ∀ U, toOpens U ⊆ U

namespace AssemblyGraphBridge

variable {α : Type u} (B : AssemblyGraphBridge α)

/-- A point lies in the "open" associated to `U` whenever it lies in one of
the sets `toOpens U`. This provides a minimal derived notion of coverage that
can be refined to actual Alexandroff opens later. -/
def covered (x : B.G.V) (U : Set B.G.V) : Prop :=
  x ∈ B.toOpens U

/-- Any element in `toOpens U` lies in `U` by deflationarity. -/
lemma covered_subset {x : B.G.V} {U : Set B.G.V}
    (hx : B.covered x U) : x ∈ U := by
  have hU : B.toOpens U ⊆ U := B.le_toOpens U
  exact hU hx

end AssemblyGraphBridge

/-- Canonical bridge where `toOpens` is given by a downward Alexandroff-style
interior built from the reachability relation generated by the assembly edge
relation `G.E`. -/
def ofASpace (α : Type u) (G : ASpace α) : AssemblyGraphBridge α where
  G := G
  toOpens U :=
    { t | ∀ u, Relation.ReflTransGen G.E t u → u ∈ U }
  le_toOpens U := by
    intro t ht
    -- Specialise the defining property with `u = t` and the reflexive step.
    exact ht t (Relation.ReflTransGen.refl)

end Assembly
end Bridges
end HeytingLean
