import HeytingLean.Integration.MagmaAsymptotic.NucleusPreserved
import HeytingLean.Integration.MagmaAsymptotic.RatchetExtension
import HeytingLean.Integration.MagmaAsymptotic.ScaleInvarianceUnification
import HeytingLean.Integration.MagmaAsymptotic.NucleusPartition
import HeytingLean.Integration.MagmaAsymptotic.IrreducibleCouplings
import HeytingLean.Integration.MagmaAsymptotic.ConstructiveExclusion
