import HeytingLean.Numbers.Surreal.StrategyOrder

/-!
# Surreal.SheafStrategies

SN-018 baseline: a lightweight sheaf-of-strategies view over sign-expansion trees.

We model:
- sign-expansion branches as finite sign lists (`plus`/`minus`),
- prefix cylinders as basic opens,
- local strategy sections on opens, and
- binary gluing with compatibility on overlaps.

This provides local-to-global composition lemmas for strategy sections.
-/

namespace HeytingLean
namespace Numbers
namespace Surreal
namespace SheafStrategies

/-- Signs used in finite sign-expansion branches. -/
inductive Sign where
  | plus
  | minus
  deriving Repr, DecidableEq

/-- Finite sign-expansion branch (tree node path). -/
abbrev Branch := List Sign

/-- Prefix relation on branches. -/
def Prefix (u v : Branch) : Prop := ∃ t, u ++ t = v

@[simp] theorem prefix_refl (u : Branch) : Prefix u u := by
  exact ⟨[], by simp⟩

theorem prefix_trans {u v w : Branch} (huv : Prefix u v) (hvw : Prefix v w) :
    Prefix u w := by
  rcases huv with ⟨t1, ht1⟩
  rcases hvw with ⟨t2, ht2⟩
  refine ⟨t1 ++ t2, ?_⟩
  calc
    u ++ (t1 ++ t2) = (u ++ t1) ++ t2 := by simp [List.append_assoc]
    _ = v ++ t2 := by simp [ht1]
    _ = w := ht2

/-- Basic open cylinder generated by a prefix. -/
def cylinder (u : Branch) : Set Branch := { v | Prefix u v }

/-- Prefix-topology style open sets: extension-closed under `Prefix`. -/
def IsOpen (U : Set Branch) : Prop :=
  ∀ ⦃u v : Branch⦄, u ∈ U → Prefix u v → v ∈ U

theorem isOpen_cylinder (u : Branch) : IsOpen (cylinder u) := by
  intro a b ha hab
  exact prefix_trans ha hab

theorem isOpen_union {U V : Set Branch} (hU : IsOpen U) (hV : IsOpen V) :
    IsOpen (U ∪ V) := by
  intro u v hu hv
  rcases hu with hu | hvu
  · exact Or.inl (hU hu hv)
  · exact Or.inr (hV hvu hv)

abbrev Strategy := StrategyOrder.Game

/-- Local strategy section on an open `U`. -/
abbrev LocalSection (U : Set Branch) := ∀ p : Branch, p ∈ U → Strategy

/-- Agreement on overlap (`U ∩ V`) for two local sections. -/
def Compatible {U V : Set Branch} (sU : LocalSection U) (sV : LocalSection V) : Prop :=
  ∀ p (hpU : p ∈ U) (hpV : p ∈ V), sU p hpU = sV p hpV

/-- Pointwise strategy sum on a common open. -/
def sumSection {U : Set Branch} (s t : LocalSection U) : LocalSection U :=
  fun p hp => StrategyOrder.sum (s p hp) (t p hp)

/-- Binary sheaf gluing: combine compatible local sections on `U ∪ V`. -/
noncomputable def glue {U V : Set Branch} (sU : LocalSection U) (sV : LocalSection V)
    (_hCompat : Compatible sU sV) : LocalSection (U ∪ V) :=
  fun p hp => by
    classical
    by_cases hU : p ∈ U
    · exact sU p hU
    · have hV : p ∈ V := by
        rcases hp with hpU | hpV
        · exact False.elim (hU hpU)
        · exact hpV
      exact sV p hV

theorem glue_restrict_left {U V : Set Branch}
    (sU : LocalSection U) (sV : LocalSection V)
    (hCompat : Compatible sU sV) {p : Branch} (hpU : p ∈ U) :
    glue sU sV hCompat p (Or.inl hpU) = sU p hpU := by
  classical
  unfold glue
  simp [hpU]

theorem glue_restrict_right {U V : Set Branch}
    (sU : LocalSection U) (sV : LocalSection V)
    (hCompat : Compatible sU sV) {p : Branch} (hpV : p ∈ V) :
    glue sU sV hCompat p (Or.inr hpV) = sV p hpV := by
  classical
  unfold glue
  by_cases hpU : p ∈ U
  · have hEq : sU p hpU = sV p hpV := hCompat p hpU hpV
    simp [hpU, hEq]
  · simp [hpU]

/-- Existence part of binary local-to-global sheaf gluing. -/
theorem exists_glue {U V : Set Branch}
    (sU : LocalSection U) (sV : LocalSection V)
    (hCompat : Compatible sU sV) :
    ∃ g : LocalSection (U ∪ V),
      (∀ p (hpU : p ∈ U), g p (Or.inl hpU) = sU p hpU) ∧
      (∀ p (hpV : p ∈ V), g p (Or.inr hpV) = sV p hpV) := by
  refine ⟨glue sU sV hCompat, ?_, ?_⟩
  · intro p hpU
    exact glue_restrict_left sU sV hCompat hpU
  · intro p hpV
    exact glue_restrict_right sU sV hCompat hpV

theorem compatible_sum {U V : Set Branch}
    {sU₁ sU₂ : LocalSection U} {sV₁ sV₂ : LocalSection V}
    (h₁ : Compatible sU₁ sV₁) (h₂ : Compatible sU₂ sV₂) :
    Compatible (sumSection sU₁ sU₂) (sumSection sV₁ sV₂) := by
  intro p hpU hpV
  simp [sumSection, h₁ p hpU hpV, h₂ p hpU hpV]

/-- Local-to-global composition: gluing commutes with pointwise strategy sum. -/
theorem glue_sum {U V : Set Branch}
    (sU₁ sU₂ : LocalSection U) (sV₁ sV₂ : LocalSection V)
    (h₁ : Compatible sU₁ sV₁) (h₂ : Compatible sU₂ sV₂)
    {p : Branch} (hp : p ∈ U ∪ V) :
    glue (sumSection sU₁ sU₂) (sumSection sV₁ sV₂) (compatible_sum h₁ h₂) p hp =
      StrategyOrder.sum
        (glue sU₁ sV₁ h₁ p hp)
        (glue sU₂ sV₂ h₂ p hp) := by
  by_cases hpU : p ∈ U
  · have hp0 :
        glue (sumSection sU₁ sU₂) (sumSection sV₁ sV₂) (compatible_sum h₁ h₂) p hp =
          sumSection sU₁ sU₂ p hpU := by
      exact glue_restrict_left (sumSection sU₁ sU₂) (sumSection sV₁ sV₂)
        (compatible_sum h₁ h₂) hpU
    have hp1 : glue sU₁ sV₁ h₁ p hp = sU₁ p hpU := by
      exact glue_restrict_left sU₁ sV₁ h₁ hpU
    have hp2 : glue sU₂ sV₂ h₂ p hp = sU₂ p hpU := by
      exact glue_restrict_left sU₂ sV₂ h₂ hpU
    rw [hp0, hp1, hp2]
    rfl
  · have hpV : p ∈ V := by
      rcases hp with hpU' | hpV
      · exact False.elim (hpU hpU')
      · exact hpV
    have hp0 :
        glue (sumSection sU₁ sU₂) (sumSection sV₁ sV₂) (compatible_sum h₁ h₂) p hp =
          sumSection sV₁ sV₂ p hpV := by
      exact glue_restrict_right (sumSection sU₁ sU₂) (sumSection sV₁ sV₂)
        (compatible_sum h₁ h₂) hpV
    have hp1 : glue sU₁ sV₁ h₁ p hp = sV₁ p hpV := by
      exact glue_restrict_right sU₁ sV₁ h₁ hpV
    have hp2 : glue sU₂ sV₂ h₂ p hp = sV₂ p hpV := by
      exact glue_restrict_right sU₂ sV₂ h₂ hpV
    rw [hp0, hp1, hp2]
    rfl

end SheafStrategies
end Surreal
end Numbers
end HeytingLean
