import HeytingLean.Magma.Atoms
import Mathlib.Data.SetLike.Basic

namespace HeytingLean.Magma

variable {A : Type*} [MagmaticAtoms A]

/-- Lower-open, nonempty subsets of the atom preorder. -/
structure LowerOpen (A : Type*) [MagmaticAtoms A] where
  carrier : Set A
  nonempty : carrier.Nonempty
  lower_closed : ∀ ⦃a b : A⦄, a ∈ carrier → b ≤ a → b ∈ carrier

instance : SetLike (LowerOpen A) A where
  coe x := x.carrier
  coe_injective' := by
    intro x y h
    cases x
    cases y
    cases h
    rfl

@[ext] theorem LowerOpen.ext {x y : LowerOpen A}
    (h : (x : Set A) = (y : Set A)) : x = y :=
  SetLike.ext' h

instance : PartialOrder (LowerOpen A) where
  le x y := (x : Set A) ⊆ (y : Set A)
  le_refl _ := by intro _ h; exact h
  le_trans _ _ _ hxy hyz := by intro _ h; exact hyz (hxy h)
  le_antisymm x y hxy hyx := by
    apply SetLike.ext'
    ext a
    exact ⟨fun ha => hxy ha, fun ha => hyx ha⟩

instance : Max (LowerOpen A) where
  max x y :=
    { carrier := (x : Set A) ∪ (y : Set A)
      nonempty := by
        rcases x.nonempty with ⟨a, ha⟩
        exact ⟨a, Or.inl ha⟩
      lower_closed := by
        intro a b ha hab
        cases ha with
        | inl hax => exact Or.inl (x.lower_closed hax hab)
        | inr hay => exact Or.inr (y.lower_closed hay hab) }

theorem mem_sup {x y : LowerOpen A} {a : A} :
    a ∈ x ⊔ y ↔ a ∈ x ∨ a ∈ y :=
  Iff.rfl

/-- The principal lower-open magma generated by an atom. -/
def principal (a : A) : LowerOpen A where
  carrier := predecessors a
  nonempty := ⟨a, le_rfl⟩
  lower_closed := by
    intro x y hx hy
    exact le_trans hy hx

@[simp] theorem mem_principal {a b : A} :
    b ∈ principal a ↔ b ≤ a :=
  Iff.rfl

theorem principal_mono {a b : A} (h : a ≤ b) :
    principal a ≤ principal b := by
  intro x hx
  exact le_trans hx h

theorem principal_le_iff {a : A} {m : LowerOpen A} :
    principal a ≤ m ↔ a ∈ m := by
  constructor
  · intro h
    exact h (show a ∈ (principal a : Set A) by simp)
  · intro ha x hx
    exact m.lower_closed ha hx

theorem principal_subset_iff {a b : A} :
    principal a ≤ principal b ↔ a ≤ b := by
  constructor
  · intro h
    simpa [mem_principal] using h (show a ∈ (principal a : Set A) by simp)
  · intro h
    exact principal_mono h

theorem lowerOpen_infinite (m : LowerOpen A) : Set.Infinite (m : Set A) := by
  rcases m.nonempty with ⟨a, ha⟩
  have hsub : predecessors a ⊆ (m : Set A) := by
    intro b hb
    exact m.lower_closed ha hb
  exact (predecessors_infinite a).mono hsub

theorem no_minimal_magma (m : LowerOpen A) :
    ∃ m' : LowerOpen A, m' < m := by
  rcases m.nonempty with ⟨a, ha⟩
  rcases MagmaticAtoms.no_minimal a with ⟨b, hba, hnot⟩
  refine ⟨principal b, ?_, ?_⟩
  · intro x hx
    exact m.lower_closed ha (le_trans hx hba)
  · intro hm
    have ha' : a ∈ (principal b : Set A) := hm ha
    exact hnot ((mem_principal).1 ha')

end HeytingLean.Magma
