import Mathlib.Control.LawfulFix
import HeytingLean.LoF.Combinators.SKY
import HeytingLean.LoF.MRSystems.Coalgebra

/-!
# A scoped fixed-point bridge: (M,R), `LawfulFix`, and SKY `Y`

This module records a minimal, provable common core between three “fixed-point” interfaces:

* Rosen-style closure: equality fixed points `f (M a) = M a`;
* domain-theoretic lawfulness: `Fix.fix f` is a fixed point for ωScottContinuous `f`;
* SKY syntax: `Y` gives a one-step reduction `Y f ↦ f (Y f)`.

Objective boundary:
* We do **not** yet implement an encoding of (M,R) dynamics into SKY terms, so we do not claim a
  simulation theorem. We only expose the shared fixed-point shape.
-/

namespace HeytingLean
namespace LoF

open OmegaCompletePartialOrder

universe u v

namespace MRSystems

/-! ## Lawful fixed points as `Function.IsFixedPt` -/

theorem fix_isFixedPt_of_ωScottContinuous {α : Type u} [OmegaCompletePartialOrder α] [LawfulFix α]
    {f : α → α} (hf : ωScottContinuous f) :
    Function.IsFixedPt f (Fix.fix f) := by
  -- `LawfulFix.fix_eq` gives `Fix.fix f = f (Fix.fix f)`.
  simpa [Function.IsFixedPt] using (LawfulFix.fix_eq (α := α) (f := f) hf).symm

/-! ## A derived closure map from `LawfulFix` (scoped) -/

namespace MRCore

section

variable (m : MRCore)
variable [OmegaCompletePartialOrder m.B] [LawfulFix m.B]

/-- The “metabolism” map generated by taking the lawful fixpoint of `b ↦ R b a` for each input `a`. -/
noncomputable def fixM : m.A → m.B :=
  fun a => Fix.fix (fun b : m.B => m.R b a)

/-- Replace `M` by `fixM` (leaving `R` unchanged). -/
noncomputable def withFixM : MRCore :=
  { A := m.A, B := m.B, M := fixM m, R := m.R }

theorem fixM_isFixedPt (a : m.A) (hR : ωScottContinuous (fun b : m.B => m.R b a)) :
    Function.IsFixedPt (fun b : m.B => m.R b a) (fixM m a) := by
  -- Expand the definition and use lawfulness.
  simpa [fixM] using
    (fix_isFixedPt_of_ωScottContinuous (α := m.B) (f := fun b : m.B => m.R b a) hR)

theorem withFixM_closedDiag (hR : ∀ a : m.A, ωScottContinuous (fun b : m.B => m.R b a)) :
    (withFixM m).ClosedDiag := by
  intro a
  have hf := fixM_isFixedPt (m := m) a (hR a)
  -- `IsFixedPt` expands to the closure equation.
  simpa [MRCore.ClosedDiag, withFixM, fixM, Function.IsFixedPt] using hf

end

/-! ### Closure as a fixed point of a higher-order operator (scoped) -/

section

variable (m : MRCore)

/-- The higher-order “closure operator” on metabolism maps induced by `R`:

`T(M)(a) := R (M a) a`. -/
def closureOp (m : MRCore) : (m.A → m.B) → (m.A → m.B) :=
  fun M a => m.R (M a) a

theorem closedDiag_iff_isFixedPt_closureOp (m : MRCore) :
    m.ClosedDiag ↔ Function.IsFixedPt (closureOp m) m.M := by
  constructor
  · intro h
    -- `ClosedDiag` is exactly the pointwise fixed-point equation for `closureOp`.
    funext a
    simpa [MRCore.ClosedDiag, closureOp] using h a
  · intro h a
    -- Extract the pointwise equation from the function equality.
    have ha := congrArg (fun M : m.A → m.B => M a) h
    simpa [MRCore.ClosedDiag, closureOp, Function.IsFixedPt] using ha

end

section

variable (m : MRCore)
variable [OmegaCompletePartialOrder (m.A → m.B)] [LawfulFix (m.A → m.B)]

/-- The metabolism map obtained as the lawful fixpoint of `closureOp`. -/
noncomputable def fixMetabolism : m.A → m.B :=
  Fix.fix (closureOp m)

/-- Replace `M` by `fixMetabolism` (leaving `R` unchanged). -/
noncomputable def withFixMetabolism : MRCore :=
  { A := m.A, B := m.B, M := fixMetabolism m, R := m.R }

theorem withFixMetabolism_closedDiag (h : ωScottContinuous (closureOp m)) :
    (withFixMetabolism m).ClosedDiag := by
  intro a
  have hf : Function.IsFixedPt (closureOp m) (Fix.fix (closureOp m)) :=
    fix_isFixedPt_of_ωScottContinuous (α := m.A → m.B) (f := closureOp m) h
  have hf_a := congrArg (fun M => M a) hf
  simpa [MRCore.ClosedDiag, closureOp, fixMetabolism, withFixMetabolism, Function.IsFixedPt] using hf_a

end

end MRCore

end MRSystems

/-! ## SKY: rewrite fixed points provided by `Y` -/

namespace Comb

/-- A one-step SKY fixed point witness for `f` at `x`: `x ↦ f x`. -/
def IsStepFixedPt (f x : Comb) : Prop :=
  Step x (Comb.app f x)

/-- A multi-step SKY fixed point witness for `f` at `x`: `x →* f x`. -/
def IsStepsFixedPt (f x : Comb) : Prop :=
  Steps x (Comb.app f x)

theorem isStepFixedPt_Y (f : Comb) : IsStepFixedPt f (Comb.app .Y f) := by
  simpa [IsStepFixedPt] using Step.Y_rule f

theorem isStepsFixedPt_Y (f : Comb) : IsStepsFixedPt f (Comb.app .Y f) := by
  simpa [IsStepsFixedPt] using Steps.trans (Step.Y_rule f) (Steps.refl _)

end Comb

end LoF
end HeytingLean
