import Mathlib.Logic.Relation
import HeytingLean.Physics.String.Modular

/-!
# ModularNucleusLaws (Track A)

Formal nucleus laws for “modular closure” expressed as a closure operator on predicates.

We intentionally avoid claiming that the *finite* orbit enumeration routines in `Modular.lean`
are idempotent. Instead, we capture the *mathematical* closure mechanism:

- one-step relation: `p ↦ sTransform p` or `p ↦ tTransform p`
- reflexive-transitive closure (`ReflTransGen`)
- nucleus: `P ↦ { q | ∃ p, P p ∧ Reachable p q }`

This nucleus is monotone, inflationary, and idempotent by construction, and is a stable target
for later executable refinements (bounded reachability, finite canonicalization, etc.).
-/

namespace HeytingLean
namespace Physics
namespace String

namespace ModularNucleus

/-- One-step modular move. -/
def Step (p q : Partition) : Prop :=
  q = sTransform p ∨ q = tTransform p

/-- Reachability generated by modular S/T steps. -/
abbrev Reachable (p q : Partition) : Prop :=
  Relation.ReflTransGen Step p q

/-- Closure operator induced by `Reachable`: image of a predicate under reachability. -/
def close (P : Partition → Prop) : Partition → Prop :=
  fun q => ∃ p, P p ∧ Reachable p q

theorem close_mono {P Q : Partition → Prop} (h : ∀ p, P p → Q p) :
    ∀ q, close P q → close Q q := by
  intro q hq
  rcases hq with ⟨p, hp, hpq⟩
  exact ⟨p, h p hp, hpq⟩

theorem close_inflationary (P : Partition → Prop) :
    ∀ p, P p → close P p := by
  intro p hp
  exact ⟨p, hp, Relation.ReflTransGen.refl⟩

theorem close_idempotent (P : Partition → Prop) :
    ∀ q, close (close P) q → close P q := by
  intro q hq
  rcases hq with ⟨mid, ⟨p, hp, hpmid⟩, hmidq⟩
  exact ⟨p, hp, Relation.ReflTransGen.trans hpmid hmidq⟩

/-- The nucleus law `close (close P) = close P`. -/
theorem close_close (P : Partition → Prop) : close (close P) = close P := by
  funext q
  apply propext
  constructor
  · exact close_idempotent (P := P) (q := q)
  · intro hq
    -- Inflationary: `close P ⊆ close (close P)`.
    rcases hq with ⟨p, hp, hpq⟩
    exact ⟨p, ⟨p, hp, Relation.ReflTransGen.refl⟩, hpq⟩

end ModularNucleus

end String
end Physics
end HeytingLean
