import HeytingLean.Probability.Discrete

/-!
Small-step relation on finite distributions generated by map/bind.
-/

namespace HeytingLean
namespace Probability

open Probability

universe u v

variable {α β : Type u}
variable [Inhabited α]

inductive Step : Dist α → Dist α → Prop
| map_step (d : Dist α) (f : α → α) : Step d (Dist.map f d)
| bind_step (d : Dist α) (k : α → Dist α) : Step d (Dist.bind d k)

infix:50 " ↦ " => Step

inductive StepStar : Dist α → Dist α → Prop
| refl (d) : StepStar d d
| step {d e f} : Step d e → StepStar e f → StepStar d f

infix:50 " ↦* " => StepStar

namespace StepStar
theorem trans {d e f : Dist α} : (d ↦* e) → (e ↦* f) → (d ↦* f) := by
  intro hde hef; induction hde with
  | refl d => simpa using hef
  | step h hdf ih => exact StepStar.step h (ih hef)
end StepStar

end Probability
end HeytingLean
