import HeytingLean.IteratedVirtual.Spiral
import HeytingLean.IteratedVirtual.SpiralEnergy
import HeytingLean.Meta.LeanTT0.ExportCAB
import HeytingLean.CLI.Args

/-!
# `spiral_export` - Export the IteratedVirtual spiral embedding to C/Python with CAB

This export is meant to mirror the “verified → executable artifact” bridge used elsewhere in
the repo (e.g. `lens_export`):

- **Executable spiral embedding**: `HeytingLean.IteratedVirtual.Spiral` is computable (uses `Float`).
- **Analytical theorem**: `HeytingLean.IteratedVirtual.SpiralEnergy` proves an energy-minimization
  statement over `ℝ` for the helix constraints.

Important limitation (by design of Lean compilation):
- Proof terms are erased in compiled artifacts; the C output is *generated from* the Lean source
  definitions, and the CAB certificate binds the bundle to the Lean provenance (modules/theorems).

Usage:

```bash
lake exe spiral_export --out dist/spiral
lake exe spiral_export --out dist/spiral --no-python
lake exe spiral_export --out dist/spiral --no-cab
```
-/

namespace HeytingLean.CLI.SpiralExport

open Lean
open HeytingLean.Meta.LeanTT0.ExportCAB

structure Config where
  outDir : String := "dist"
  generatePython : Bool := true
  generateCAB : Bool := true
deriving Repr

private def usage : String :=
  String.intercalate "\n"
    [ "spiral_export - Export IteratedVirtual spiral embedding"
    , ""
    , "Writes a small, auditable C library for the helix embedding (and an optional Python wrapper)"
    , "together with a CAB certificate binding the artifacts to Lean provenance."
    , ""
    , "Usage:"
    , "  lake exe spiral_export --out <dir>"
    , ""
    , "Flags:"
    , "  --out <dir>     Output directory (default: dist)"
    , "  --python        Generate Python wrapper (default: yes)"
    , "  --no-python     Skip Python wrapper"
    , "  --cab           Generate CAB certificate (default: yes)"
    , "  --no-cab        Skip CAB certificate"
    , "  --help          Show this message"
    ]

private partial def parseArgs (args : List String) (cfg : Config := {}) : IO (Config × Bool) :=
  match args with
  | [] => pure (cfg, false)
  | "--" :: rest => parseArgs rest cfg
  | "--help" :: _ => pure (cfg, true)
  | "--out" :: dir :: rest => parseArgs rest { cfg with outDir := dir }
  | "--python" :: rest => parseArgs rest { cfg with generatePython := true }
  | "--no-python" :: rest => parseArgs rest { cfg with generatePython := false }
  | "--cab" :: rest => parseArgs rest { cfg with generateCAB := true }
  | "--no-cab" :: rest => parseArgs rest { cfg with generateCAB := false }
  | x :: _ => throw <| IO.userError s!"unknown flag: {x} (try --help)"

private def resolveOutDir (dir : String) : IO System.FilePath := do
  if dir.startsWith "/" then
    return System.FilePath.mk dir
  let cwd ← IO.currentDir
  let base :=
    if cwd.fileName == some "lean" then
      cwd.parent.getD cwd
    else
      cwd
  return base / dir

private def writeFile (path : System.FilePath) (contents : String) : IO Unit := do
  let some parent := path.parent
    | throw <| IO.userError s!"could not compute parent directory for {path}"
  IO.FS.createDirAll parent
  IO.FS.writeFile path contents

private def cHeader : String :=
  String.intercalate "\n"
    [ "/*"
    , " * spiral.h"
    , " *"
    , " * Generated by HeytingLean (spiral_export)."
    , " *"
    , " * This implements the IteratedVirtual helix embedding:"
    , " *   (cos t, sin t, pitch * t)"
    , " */"
    , ""
    , "#ifndef HEYTINGLEAN_SPIRAL_H"
    , "#define HEYTINGLEAN_SPIRAL_H"
    , ""
    , "#ifdef __cplusplus"
    , "extern \"C\" {"
    , "#endif"
    , ""
    , "typedef struct {"
    , "  double x;"
    , "  double y;"
    , "  double z;"
    , "} hl_point3;"
    , ""
    , "hl_point3 hl_helix(double t, double pitch);"
    , "double hl_tension_energy_at(double t, double pitch, hl_point3 p);"
    , "void hl_embed_steps(int count, double step, double pitch, hl_point3* out_points);"
    , ""
    , "#ifdef __cplusplus"
    , "}"
    , "#endif"
    , ""
    , "#endif /* HEYTINGLEAN_SPIRAL_H */"
    , ""
    ]

private def cSource : String :=
  String.intercalate "\n"
    [ "/*"
    , " * spiral.c"
    , " *"
    , " * Generated by HeytingLean (spiral_export)."
    , " */"
    , ""
    , "#include \"spiral.h\""
    , ""
    , "#include <math.h>"
    , ""
    , "hl_point3 hl_helix(double t, double pitch) {"
    , "  hl_point3 p;"
    , "  p.x = cos(t);"
    , "  p.y = sin(t);"
    , "  p.z = pitch * t;"
    , "  return p;"
    , "}"
    , ""
    , "double hl_tension_energy_at(double t, double pitch, hl_point3 p) {"
    , "  double r_err = (p.x * p.x + p.y * p.y - 1.0);"
    , "  double z_err = (p.z - pitch * t);"
    , "  return r_err * r_err + z_err * z_err;"
    , "}"
    , ""
    , "void hl_embed_steps(int count, double step, double pitch, hl_point3* out_points) {"
    , "  /* out_points must have length (count + 1) */"
    , "  for (int k = 0; k <= count; ++k) {"
    , "    double t = step * (double)k;"
    , "    out_points[k] = hl_helix(t, pitch);"
    , "  }"
    , "}"
    , ""
    ]

private def cDriver : String :=
  String.intercalate "\n"
    [ "/*"
    , " * spiral_driver.c"
    , " *"
    , " * Generated by HeytingLean (spiral_export)."
    , " *"
    , " * Default behavior: run a small numeric self-check and exit 0."
    , " * Use --json to print the helix points as a JSON array."
    , " */"
    , ""
    , "#include \"spiral.h\""
    , ""
    , "#include <math.h>"
    , "#include <stdbool.h>"
    , "#include <stdio.h>"
    , "#include <stdlib.h>"
    , "#include <string.h>"
    , ""
    , "static bool has_flag(int argc, char** argv, const char* flag) {"
    , "  for (int i = 1; i < argc; ++i) {"
    , "    if (strcmp(argv[i], flag) == 0) return true;"
    , "  }"
    , "  return false;"
    , "}"
    , ""
    , "static int parse_int_flag(int argc, char** argv, const char* flag, int defv) {"
    , "  for (int i = 1; i + 1 < argc; ++i) {"
    , "    if (strcmp(argv[i], flag) == 0) return atoi(argv[i + 1]);"
    , "  }"
    , "  return defv;"
    , "}"
    , ""
    , "static double parse_double_flag(int argc, char** argv, const char* flag, double defv) {"
    , "  for (int i = 1; i + 1 < argc; ++i) {"
    , "    if (strcmp(argv[i], flag) == 0) return atof(argv[i + 1]);"
    , "  }"
    , "  return defv;"
    , "}"
    , ""
    , "static void print_usage(void) {"
    , "  printf(\"spiral_driver\\n\\n\");"
    , "  printf(\"Options:\\n\");"
    , "  printf(\"  --n <int>       number of steps (default: 32)\\n\");"
    , "  printf(\"  --step <float>  angular step (default: 0.35)\\n\");"
    , "  printf(\"  --pitch <float> z pitch per radian (default: 0.15)\\n\");"
    , "  printf(\"  --json          print points as JSON\\n\");"
    , "  printf(\"  --help          show this message\\n\");"
    , "}"
    , ""
    , "static void print_json(int n, const hl_point3* pts) {"
    , "  printf(\"[\");"
    , "  for (int i = 0; i <= n; ++i) {"
    , "    if (i) printf(\",\");"
    , "    printf(\"{\\\"x\\\":%.17g,\\\"y\\\":%.17g,\\\"z\\\":%.17g}\", pts[i].x, pts[i].y, pts[i].z);"
    , "  }"
    , "  printf(\"]\\n\");"
    , "}"
    , ""
    , "int main(int argc, char** argv) {"
    , "  if (has_flag(argc, argv, \"--help\")) {"
    , "    print_usage();"
    , "    return 0;"
    , "  }"
    , ""
    , "  int n = parse_int_flag(argc, argv, \"--n\", 32);"
    , "  double step = parse_double_flag(argc, argv, \"--step\", 0.35);"
    , "  double pitch = parse_double_flag(argc, argv, \"--pitch\", 0.15);"
    , ""
    , "  if (n < 0) {"
    , "    fprintf(stderr, \"n must be nonnegative\\n\");"
    , "    return 2;"
    , "  }"
    , ""
    , "  hl_point3* pts = (hl_point3*)calloc((size_t)(n + 1), sizeof(hl_point3));"
    , "  if (!pts) {"
    , "    fprintf(stderr, \"out of memory\\n\");"
    , "    return 3;"
    , "  }"
    , ""
    , "  hl_embed_steps(n, step, pitch, pts);"
    , ""
    , "  /* Numeric self-check (tolerances are loose by design; trig is inexact). */"
    , "  const double eps_energy = 1e-10;"
    , "  for (int k = 0; k <= n; ++k) {"
    , "    double t = step * (double)k;"
    , "    double e = hl_tension_energy_at(t, pitch, pts[k]);"
    , "    if (!(e >= 0.0 && e <= eps_energy)) {"
    , "      fprintf(stderr, \"self-check failed at k=%d: energy=%.17g (eps=%.17g)\\n\", k, e, eps_energy);"
    , "      free(pts);"
    , "      return 1;"
    , "    }"
    , "  }"
    , ""
    , "  if (has_flag(argc, argv, \"--json\")) {"
    , "    print_json(n, pts);"
    , "  } else {"
    , "    printf(\"=== HeytingLean spiral export self-check ===\\n\");"
    , "    printf(\"n=%d step=%.17g pitch=%.17g\\n\", n, step, pitch);"
    , "    printf(\"=== All tests passed ===\\n\");"
    , "  }"
    , ""
    , "  free(pts);"
    , "  return 0;"
    , "}"
    , ""
    ]

private def pythonWrapper : String :=
  String.intercalate "\n"
    [ "# spiral_wrapper.py"
    , "#"
    , "# Generated by HeytingLean (spiral_export)."
    , "# Minimal ctypes wrapper for libspiral.so"
    , ""
    , "import ctypes"
    , "import os"
    , "import subprocess"
    , "import sys"
    , ""
    , "HERE = os.path.dirname(os.path.abspath(__file__))"
    , "LIB = os.path.join(HERE, \"libspiral.so\")"
    , ""
    , ""
    , "class Point3(ctypes.Structure):"
    , "    _fields_ = [(\"x\", ctypes.c_double), (\"y\", ctypes.c_double), (\"z\", ctypes.c_double)]"
    , ""
    , ""
    , "def _ensure_built():"
    , "    if os.path.exists(LIB):"
    , "        return"
    , "    c = os.path.join(HERE, \"spiral.c\")"
    , "    subprocess.check_call([\"cc\", \"-shared\", \"-fPIC\", \"-o\", LIB, c, \"-lm\"])"
    , ""
    , ""
    , "def load():"
    , "    _ensure_built()"
    , "    lib = ctypes.CDLL(LIB)"
    , "    lib.hl_embed_steps.argtypes = [ctypes.c_int, ctypes.c_double, ctypes.c_double, ctypes.POINTER(Point3)]"
    , "    lib.hl_embed_steps.restype = None"
    , "    return lib"
    , ""
    , ""
    , "def embed_steps(n: int = 32, step: float = 0.35, pitch: float = 0.15):"
    , "    lib = load()"
    , "    arr = (Point3 * (n + 1))()"
    , "    lib.hl_embed_steps(int(n), float(step), float(pitch), arr)"
    , "    return [(arr[i].x, arr[i].y, arr[i].z) for i in range(n + 1)]"
    , ""
    , ""
    , "def main(argv):"
    , "    n = 32"
    , "    if len(argv) >= 2:"
    , "        n = int(argv[1])"
    , "    pts = embed_steps(n=n)"
    , "    print(f\"points: {len(pts)}\")"
    , "    print(\"first:\", pts[0])"
    , "    print(\"last:\", pts[-1])"
    , "    return 0"
    , ""
    , ""
    , "if __name__ == \"__main__\":"
    , "    raise SystemExit(main(sys.argv))"
    , ""
    ]

private def provenanceJson : Json :=
  Json.mkObj
    [ ("bundle_id", Json.str "iterated_virtual_spiral")
    , ("description", Json.str "IteratedVirtual helix/spiral embedding export to C/Python with CAB certificate.")
    , ("lean_modules",
        Json.arr #[
          Json.str "HeytingLean.IteratedVirtual.Spiral",
          Json.str "HeytingLean.IteratedVirtual.SpiralEnergy",
          Json.str "HeytingLean.Meta.LeanTT0.ExportCAB"
        ])
    , ("lean_defs",
        Json.arr #[
          Json.str "HeytingLean.IteratedVirtual.helix",
          Json.str "HeytingLean.IteratedVirtual.embedSteps"
        ])
    , ("lean_theorems",
        Json.arr #[
          Json.str "HeytingLean.IteratedVirtual.Point3R.tensionEnergyAt_helix",
          Json.str "HeytingLean.IteratedVirtual.Point3R.helix_minimizes_pointwise",
          Json.str "HeytingLean.IteratedVirtual.Point3R.helix_minimizes_list",
          Json.str "HeytingLean.IteratedVirtual.Point3R.tendsto_tensionEnergyAt_helix_atTop"
        ])
    , ("c_api",
        Json.arr #[
          Json.str "hl_helix(t, pitch) -> (x,y,z)",
          Json.str "hl_tension_energy_at(t, pitch, p) -> nonnegative",
          Json.str "hl_embed_steps(count, step, pitch, out_points)"
        ])
    , ("notes",
        Json.arr #[
          Json.str "C artifacts implement the computable Float helix from HeytingLean.IteratedVirtual.Spiral (mapped to C double).",
          Json.str "SpiralEnergy proves an exact (ℝ) tension-minimization property; this is referenced in the CAB provenance but not re-proved inside the C runtime."
        ])
    ]

def main (argv : List String) : IO UInt32 := do
  let args := HeytingLean.CLI.stripLakeArgs argv
  try
    let (cfg, showHelp) ←
      if args.isEmpty then
        pure ({}, false)
      else
        parseArgs args
    if showHelp then
      IO.println usage
      return (0 : UInt32)

    let baseDir ← resolveOutDir cfg.outDir
    let outDir := baseDir / "iterated_virtual_spiral"

    let headerPath := outDir / "spiral.h"
    let sourcePath := outDir / "spiral.c"
    let driverPath := outDir / "spiral_driver.c"
    let provenancePath := outDir / "provenance.json"

    writeFile headerPath cHeader
    writeFile sourcePath cSource
    writeFile driverPath cDriver
    writeFile provenancePath (Json.pretty provenanceJson)

    IO.println s!"[spiral_export] wrote {headerPath}"
    IO.println s!"[spiral_export] wrote {sourcePath}"
    IO.println s!"[spiral_export] wrote {driverPath}"
    IO.println s!"[spiral_export] wrote {provenancePath}"

    let mut artifacts : List Artifact := [
      { name := "spiral.h", content := cHeader },
      { name := "spiral.c", content := cSource },
      { name := "spiral_driver.c", content := cDriver },
      { name := "provenance.json", content := (Json.pretty provenanceJson) }
    ]

    if cfg.generatePython then
      let pythonPath := outDir / "spiral_wrapper.py"
      writeFile pythonPath pythonWrapper
      IO.println s!"[spiral_export] wrote {pythonPath}"
      artifacts := artifacts ++ [{ name := "spiral_wrapper.py", content := pythonWrapper }]

    if cfg.generateCAB then
      let certificate := generateCertificate
        "iterated_virtual_spiral"
        artifacts
        [ "HeytingLean.IteratedVirtual.Point3R.tensionEnergyAt_helix"
        , "HeytingLean.IteratedVirtual.Point3R.helix_minimizes_pointwise"
        , "HeytingLean.IteratedVirtual.Point3R.helix_minimizes_list"
        , "HeytingLean.IteratedVirtual.Point3R.tendsto_tensionEnergyAt_helix_atTop"
        ]
        [ "HeytingLean.IteratedVirtual.Spiral"
        , "HeytingLean.IteratedVirtual.SpiralEnergy"
        ]
        "IteratedVirtual spiral embedding (helix) export bundle."

      let certPath := outDir / "certificate.json"
      writeFile certPath (Json.pretty certificate)
      IO.println s!"[spiral_export] wrote {certPath}"

    IO.println ""
    IO.println "To build and test:"
    IO.println s!"  cd {outDir}"
    IO.println "  cc -O2 -o spiral_driver spiral_driver.c spiral.c -lm"
    IO.println "  ./spiral_driver"
    IO.println "  ./spiral_driver --json | head"
    if cfg.generatePython then
      IO.println "  python3 spiral_wrapper.py"
    if cfg.generateCAB then
      IO.println ""
      IO.println "To verify CAB certificate:"
      IO.println s!"  lake exe cab_verify_export {outDir}/certificate.json"

    return (0 : UInt32)
  catch e =>
    IO.eprintln s!"[spiral_export] error: {e}"
    return (1 : UInt32)

end HeytingLean.CLI.SpiralExport

def main (argv : List String) : IO UInt32 :=
  HeytingLean.CLI.SpiralExport.main argv
