import HeytingLean.Noneism.Intentionality

/-!
# Noneism.Sosein

Sosein (“being-so”) scaffolding: properties attributed to an object, independent of existence.
-/

namespace HeytingLean
namespace Noneism

/-- A sosein record: a (finite) bundle of formulas treated as properties of a term. -/
structure Sosein (σ : Type) where
  subject : Term
  properties : List (Formula σ)

/-- Extract the “witness requirement” generated by a sosein claim. -/
def Sosein.witnessRequirement {σ : Type} (s : Sosein σ) : WitnessedFormula σ :=
  { term := s.subject, formula := Formula.top }

end Noneism
end HeytingLean

