import HeytingLean.Coalgebra.Universal.Bisimulation

/-!
# Universal coalgebra examples: Mealy-style functor

We define the Mealy endofunctor

`F(X) = A → (B × X)`

and provide a `Relator` instance.

We also define a **one-state** Mealy coalgebra generated by a function `f : A → B`,
and show that (on the unique state) bisimilarity is equivalent to extensional equality
of the output function.
-/

namespace HeytingLean
namespace Coalgebra
namespace Universal
namespace Examples

open CategoryTheory

universe u

variable {A B : Type u}

/-- Mealy endofunctor: `X ↦ A → (B × X)`. -/
def MealyF (A B : Type u) : Type u ⥤ Type u where
  obj X := A → (B × X)
  map {X Y} (f : X → Y) := fun g a => ((g a).1, f (g a).2)
  map_id := by
    intro X
    funext g a
    rfl
  map_comp := by
    intro X Y Z f g
    funext h a
    rfl

instance : Relator (MealyF A B) where
  LiftR {α β} R x y := ∀ a, (x a).1 = (y a).1 ∧ R (x a).2 (y a).2
  mono := by
    intro α β R S h x y hxy
    intro a
    refine ⟨(hxy a).1, ?_⟩
    exact h _ _ (hxy a).2

/-- One-state Mealy coalgebra generated by `f : A → B`. -/
def oneStateMealy (f : A → B) : Universal.Coalg (F := MealyF A B) :=
  Universal.Coalg.mk (F := MealyF A B) (ULift.{u} Unit) (fun _u => fun a => (f a, ULift.up ()))

namespace oneStateMealy

open RelBisim

variable (f g : A → B)

theorem bisimilar_iff (u v : ULift.{u} Unit) :
    Bisimilar (F := MealyF A B) (oneStateMealy (A := A) (B := B) f)
        (oneStateMealy (A := A) (B := B) g) u v ↔ f = g := by
  constructor
  · intro h
    -- Use that bisimilarity is a bisimulation (post-fixed), hence forces output equality.
    have hpost := bisimilar_isBisimulation (F := MealyF A B)
      (S := oneStateMealy (A := A) (B := B) f)
      (T := oneStateMealy (A := A) (B := B) g)
    have hstep := hpost u v h
    -- Unfold `LiftR` for MealyF at `()`.
    funext a
    simpa [oneStateMealy, MealyF] using (hstep a).1
  · intro hfg
    -- Show `f=g` implies bisimilarity by exhibiting the total relation as a bisimulation.
    subst hfg
    -- Use `R := fun _ _ => True`.
    have hR : IsBisimulation (F := MealyF A B)
        (oneStateMealy (A := A) (B := B) f)
        (oneStateMealy (A := A) (B := B) f)
        (fun _ _ => True) := by
      intro u v _
      intro a
      -- outputs match by rfl, and relation holds trivially on next-state.
      exact ⟨rfl, trivial⟩
    have hle := coinduction (F := MealyF A B) (S := oneStateMealy (A := A) (B := B) f)
        (T := oneStateMealy (A := A) (B := B) f) (R := fun _ _ => True) hR
    exact hle u v trivial

end oneStateMealy

end Examples
end Universal
end Coalgebra
end HeytingLean
