import HeytingLean.LoF.ComparisonNucleus.RTTRI

/-
Basic confluence patterns for tiny rewrite systems, and a first
instantiation showing how RT-1 for the comparison nucleus yields a
local confluence property.
-/

namespace HeytingLean
namespace LoF
namespace HoTT

/-! ### Abstract two-branch rewrite system -/

/- A tiny rewrite relation generated by two functions `f` and `g` on a
type `α`. From any state `a`, we may step either to `f a` or to `g a`. -/
inductive StepFG {α : Type _} (f g : α → α) : α → α → Prop where
  | step_f : ∀ a, StepFG f g a (f a)
  | step_g : ∀ a, StepFG f g a (g a)

namespace StepFG

variable {α : Type _} {f g : α → α}

/-- If `f = g`, then every one-step rewrite from `a` has the same
target `f a`. This makes the relation locally deterministic at `a`. -/
lemma target_eq_of_eq (hfg : f = g) {a b} (h : StepFG f g a b) :
    b = f a := by
  cases h <;> simp [hfg]

/-- If `f = g`, any two one-step rewrites from the same source `a`
have equal targets. This is a simple form of local confluence. -/
lemma peak_equal (hfg : f = g) {a b₁ b₂}
    (h₁ : StepFG f g a b₁) (h₂ : StepFG f g a b₂) :
    b₁ = b₂ := by
  have hb₁ : b₁ = f a := target_eq_of_eq (f := f) (g := g) hfg h₁
  have hb₂ : b₂ = f a := target_eq_of_eq (f := f) (g := g) hfg h₂
  exact hb₁.trans hb₂.symm

end StepFG

/-! ### Instantiation: comparison nucleus RT-1 -/

open Comparison

universe u v

variable {L : Type u} {Ω : Type v}
variable [CompleteLattice L] [CompleteLattice Ω]

/-- For a comparison nucleus `CompSpec L Ω`, view the two functions
`dec ∘ enc` and `id` as generators of a tiny two-branch rewrite system
on the fixed-point core `ΩR S`. -/
def stepComparison (S : CompSpec L Ω) :
    ΩR S → ΩR S → Prop :=
  StepFG (fun a => dec S (enc S a)) (fun a => a)

/-- Any one-step move in the comparison system actually lands back at
the source state, using RT-1 to identify the two branches. -/
lemma stepComparison_target_eq (S : CompSpec L Ω)
    {a b : ΩR S}
    (h : stepComparison (S := S) a b) :
    b = a := by
  have hpoint : dec S (enc S a) = a := by
    -- RT-1 specializes to `dec (enc a) = a`.
    have hRT := congrArg (fun f => f a) (RT1 (S := S))
    simpa using hRT
  cases h with
  | step_f =>
      -- In the `step_f` branch the target is `dec (enc a)`.
      exact hpoint
  | step_g =>
      -- In the `step_g` branch the target is definitionally `a`.
      rfl

/-- RT-1 (`dec ∘ enc = id`) implies that this two-branch rewrite system
on `ΩR S` is locally confluent in the sense that any peak has equal
targets. -/
lemma comparison_peak_equal (S : CompSpec L Ω)
    {a b₁ b₂ : ΩR S}
    (h₁ : stepComparison (S := S) a b₁)
    (h₂ : stepComparison (S := S) a b₂) :
    b₁ = b₂ := by
  -- `RT1` is exactly the equality of the two branch functions.
  have hfg : (fun a : ΩR S => dec S (enc S a)) =
             (fun a : ΩR S => a) := RT1 (S := S)
  -- Apply the abstract peak lemma.
  exact StepFG.peak_equal (f := fun a => dec S (enc S a))
                          (g := fun a => a)
                          hfg h₁ h₂

end HoTT
end LoF
end HeytingLean
