import HeytingLean.LoF.HoTT.Identity
import HeytingLean.LoF.HoTT.Confluence
import HeytingLean.LoF.HoTT.DimLens

/-
Higher-level HoTT / Glue view of the comparison nucleus and dimensional
lens layer.

This module packages a couple of small lemmas that rephrase the RT-1
two-branch relation on Ωᴿ in terms of the HoTT-style identity alias
`Id`, and specializes the generic local confluence lemma
`comparison_peak_equal` to dimensional lenses.  It is a first step
towards the Glue-based narrative described in the Dimensional
Correspondence design documents, without introducing any new axioms or
non-kernel-safe features.
-/

namespace HeytingLean
namespace LoF
namespace HoTT

open Comparison

universe u v

variable {L : Type u} {Ω : Type v}
variable [CompleteLattice L] [CompleteLattice Ω]

/-- RT-1 seen as a HoTT-style identity path on the fixed-point core.

The abstract two-branch relation `stepComparison` is generated by the
maps `dec ∘ enc` and `id`.  RT-1 identifies these maps, so every
one-step move from `a` actually lands back at `a`, which we rephrase
here as an `Id`-path. -/
theorem stepComparison_Id (S : CompSpec L Ω)
    {a b : ΩR S}
    (h : stepComparison (S := S) a b) :
    Id a b := by
  -- From `stepComparison_target_eq` we know `b = a`, so `a = b`.
  have hb : b = a := stepComparison_target_eq (S := S) h
  exact hb.symm

/-- For any dimensional lens, every RT-1 peak at `a` admits both
combinatorial and HoTT-style identity joins.

The `DimLens.join` field provides a SKY combinatorial join for the
encoded targets, while `comparison_peak_equal` shows that the targets
in Ωᴿ themselves are connected by an `Id`-path. -/
theorem DimLens.peak_Id (lens : DimLens L Ω)
    {a b₁ b₂ : ΩR lens.S}
    (h₁ : stepComparison (S := lens.S) a b₁)
    (h₂ : stepComparison (S := lens.S) a b₂) :
    Id b₁ b₂ := by
  -- Specialize the abstract RT-1 peak lemma to `lens.S`.
  have hb : b₁ = b₂ :=
    comparison_peak_equal (S := lens.S) h₁ h₂
  exact hb

end HoTT
end LoF
end HeytingLean

