import HeytingLean.Bridge.AlMayahi.TauEpoch.Stats
import HeytingLean.Bridge.AlMayahi.TauEpoch.ProjectionOperator
import HeytingLean.Bridge.AlMayahi.TauEpoch.TauProxy
import HeytingLean.Bridge.AlMayahi.TauEpoch.DomainData
import HeytingLean.Bridge.AlMayahi.TauEpoch.ProjectionLaw
import HeytingLean.Bridge.AlMayahi.TauEpoch.AlphaBridge
import HeytingLean.Bridge.AlMayahi.TauEpoch.BetaSpectrum
import HeytingLean.Bridge.AlMayahi.TauEpoch.Predictions
import HeytingLean.Bridge.AlMayahi.TauEpoch.NecessityTheorem
