import HeytingLean.PerspectivalPlenum.ATPTargets

namespace HeytingLean
namespace Tests
namespace PerspectivalPlenum

#check HeytingLean.PerspectivalPlenum.ATP.target_ratchet_iterate_zero
#check HeytingLean.PerspectivalPlenum.ATP.target_paraconsistent_allows
#check HeytingLean.PerspectivalPlenum.ATP.target_triangle_local_global
#check HeytingLean.PerspectivalPlenum.ATP.target_squareCircle_lens_relative
#check HeytingLean.PerspectivalPlenum.ATP.target_triangle_physImpossible
#check HeytingLean.PerspectivalPlenum.ATP.target_euclideanSingleton_glues
#check HeytingLean.PerspectivalPlenum.ATP.target_virtual_life_obstruction_class
#check HeytingLean.PerspectivalPlenum.ATP.target_virtual_knot_r1_class
#check HeytingLean.PerspectivalPlenum.ATP.target_virtual_knot_r2_class
#check HeytingLean.PerspectivalPlenum.ATP.target_virtual_knot_r3_left_class
#check HeytingLean.PerspectivalPlenum.ATP.target_virtual_knot_r3_right_class
#check HeytingLean.PerspectivalPlenum.ATP.target_virtual_knot_r3_pair_class
#check HeytingLean.PerspectivalPlenum.ATP.target_virtual_knot_r3_bracket_signature_of_skeinStep_eq
#check HeytingLean.PerspectivalPlenum.ATP.target_virtual_knot_r3_bracket_signature_of_tl3_bridge_endpoints
#check HeytingLean.PerspectivalPlenum.ATP.target_virtual_knot_r3_bridge_witness_of_two_level_bridge_witness
#check HeytingLean.PerspectivalPlenum.ATP.target_virtual_knot_r3_skeinStep_eq_of_two_level_bridge_witness
#check HeytingLean.PerspectivalPlenum.ATP.target_virtual_knot_r3_bracket_signature_of_two_level_bridge_witness
#check HeytingLean.PerspectivalPlenum.ATP.target_virtual_knot_r3_bracket_signature_of_bridge_witness
#check HeytingLean.PerspectivalPlenum.ATP.target_virtual_knot_r2_bracket_signature
#check HeytingLean.PerspectivalPlenum.ATP.target_constructive_disallows
#check HeytingLean.PerspectivalPlenum.ATP.target_booleanStrict_disallows

end PerspectivalPlenum
end Tests
end HeytingLean
