import Mathlib.Order.Nucleus
import Mathlib.Data.Set.Lattice

namespace HeytingLean
namespace Crypto
namespace NECP

open Set

universe u

/-- Upward Alexandrov opens of a preorder, with inclusion order and intersection as meet. -/
structure AlexandrovOpen (α : Type u) [LE α] where
  carrier : Set α
  upper' : IsUpperSet carrier

namespace AlexandrovOpen

section Basic

variable {α : Type u} [Preorder α]

instance : SetLike (AlexandrovOpen α) α where
  coe U := U.carrier
  coe_injective' := by
    intro U V h
    cases U
    cases V
    cases h
    rfl

instance : Membership α (AlexandrovOpen α) := ⟨fun U a => ((U : Set α) a)⟩

@[ext] theorem ext {U V : AlexandrovOpen α} (h : (U : Set α) = (V : Set α)) : U = V :=
  SetLike.ext' h

@[simp] theorem mem_mk {s : Set α} (hs) {a : α} :
    a ∈ (⟨s, hs⟩ : AlexandrovOpen α) ↔ a ∈ s :=
  Iff.rfl

@[simp] theorem upper (U : AlexandrovOpen α) : IsUpperSet (U : Set α) :=
  U.upper'

/-- The principal Alexandrov open generated by `x`. -/
def principalOpen (x : α) : AlexandrovOpen α :=
  ⟨{y | x ≤ y}, by
    intro a b hab ha
    exact le_trans ha hab⟩

@[simp] theorem mem_principalOpen {x y : α} :
    y ∈ principalOpen x ↔ x ≤ y :=
  Iff.rfl

instance : LE (AlexandrovOpen α) where
  le U V := (U : Set α) ⊆ V

@[simp] theorem le_def {U V : AlexandrovOpen α} :
    U ≤ V ↔ (U : Set α) ⊆ V :=
  Iff.rfl

instance : PartialOrder (AlexandrovOpen α) where
  le := (· ≤ ·)
  le_refl _ := by intro _ hx; exact hx
  le_trans _ _ _ hUV hVW := by intro x hx; exact hVW (hUV hx)
  le_antisymm U V hUV hVU := by
    ext x
    exact ⟨fun hx => hUV hx, fun hx => hVU hx⟩

instance : Min (AlexandrovOpen α) where
  min U V :=
    ⟨(U : Set α) ∩ V, by
      intro a b hab ha
      exact ⟨U.upper hab ha.1, V.upper hab ha.2⟩⟩

instance : Max (AlexandrovOpen α) where
  max U V :=
    ⟨(U : Set α) ∪ V, by
      intro a b hab ha
      rcases ha with ha | ha
      · exact Or.inl (U.upper hab ha)
      · exact Or.inr (V.upper hab ha)⟩

instance : Top (AlexandrovOpen α) :=
  ⟨⟨univ, by
    intro a b _ ha
    trivial⟩⟩

instance : Bot (AlexandrovOpen α) :=
  ⟨⟨∅, by
    intro a b _ ha
    cases ha⟩⟩

instance : SupSet (AlexandrovOpen α) :=
  ⟨fun S => ⟨⋃ U ∈ S, (U : Set α), by
    intro a b hab ha
    rcases mem_iUnion₂.mp ha with ⟨U, hU, haU⟩
    exact mem_iUnion₂.mpr ⟨U, hU, U.upper hab haU⟩⟩⟩

instance : InfSet (AlexandrovOpen α) :=
  ⟨fun S => ⟨⋂ U ∈ S, (U : Set α), by
    intro a b hab ha
    exact mem_iInter₂.mpr (fun U hU => U.upper hab (mem_iInter₂.mp ha U hU))⟩⟩

@[simp] theorem mem_inf {U V : AlexandrovOpen α} {a : α} :
    a ∈ U ⊓ V ↔ a ∈ U ∧ a ∈ V :=
  Iff.rfl

instance : SemilatticeInf (AlexandrovOpen α) where
  inf := (· ⊓ ·)
  inf_le_left _ _ := by intro x hx; exact hx.1
  inf_le_right _ _ := by intro x hx; exact hx.2
  le_inf _ _ _ hUV hUW := by
    intro x hx
    exact ⟨hUV hx, hUW hx⟩

instance : CompleteLattice (AlexandrovOpen α) :=
  SetLike.coe_injective.completeLattice _ (fun _ _ => rfl) (fun _ _ => rfl) (fun _ => rfl)
    (fun _ => rfl) rfl rfl

@[simp, norm_cast] theorem coe_top : ((⊤ : AlexandrovOpen α) : Set α) = univ := rfl
@[simp, norm_cast] theorem coe_bot : ((⊥ : AlexandrovOpen α) : Set α) = ∅ := rfl
@[simp, norm_cast] theorem coe_sup (U V : AlexandrovOpen α) :
    ((U ⊔ V : AlexandrovOpen α) : Set α) = (U : Set α) ∪ V := rfl
@[simp, norm_cast] theorem coe_inf (U V : AlexandrovOpen α) :
    ((U ⊓ V : AlexandrovOpen α) : Set α) = (U : Set α) ∩ V := rfl
@[simp, norm_cast] theorem coe_sSup (S : Set (AlexandrovOpen α)) :
    ((sSup S : AlexandrovOpen α) : Set α) = ⋃ U ∈ S, (U : Set α) := rfl
@[simp, norm_cast] theorem coe_sInf (S : Set (AlexandrovOpen α)) :
    ((sInf S : AlexandrovOpen α) : Set α) = ⋂ U ∈ S, (U : Set α) := rfl

instance : CompletelyDistribLattice (AlexandrovOpen α) :=
  .ofMinimalAxioms <|
    SetLike.coe_injective.completelyDistribLatticeMinimalAxioms .of _
      (fun _ _ => rfl) (fun _ _ => rfl) (fun _ => rfl) (fun _ => rfl) rfl rfl

instance : Order.Frame (AlexandrovOpen α) := inferInstance

end Basic

section Repair

variable {α : Type u} [Preorder α]

/-- A monotone endomap on the base poset acts on Alexandrov opens by inverse image. -/
def inducedOpenMap (j : α → α) (hj_mono : Monotone j) (U : AlexandrovOpen α) :
    AlexandrovOpen α :=
  ⟨{x | j x ∈ U}, by
    intro a b hab ha
    exact U.upper (hj_mono hab) ha⟩

@[simp] theorem mem_inducedOpenMap {j : α → α} {hj_mono : Monotone j}
    {U : AlexandrovOpen α} {x : α} :
    x ∈ inducedOpenMap j hj_mono U ↔ j x ∈ U :=
  Iff.rfl

theorem inducedOpenMap_extensive {j : α → α} {hj_mono : Monotone j}
    (hj_ext : ∀ x, x ≤ j x) (U : AlexandrovOpen α) :
    U ≤ inducedOpenMap j hj_mono U := by
  intro x hx
  exact U.upper (hj_ext x) hx

theorem inducedOpenMap_idempotent {j : α → α} {hj_mono : Monotone j}
    (hj_idem : ∀ x, j (j x) = j x) (U : AlexandrovOpen α) :
    inducedOpenMap j hj_mono (inducedOpenMap j hj_mono U) = inducedOpenMap j hj_mono U := by
  ext x
  constructor <;> intro hx <;> simpa [inducedOpenMap, hj_idem x] using hx

theorem inducedOpenMap_inf {j : α → α} {hj_mono : Monotone j}
    (U V : AlexandrovOpen α) :
    inducedOpenMap j hj_mono (U ⊓ V) =
      inducedOpenMap j hj_mono U ⊓ inducedOpenMap j hj_mono V := by
  ext x
  constructor <;> intro hx
  · exact ⟨hx.1, hx.2⟩
  · exact ⟨hx.1, hx.2⟩

/-- The Alexandrov repair on the meet-semilattice of upward opens. -/
def inducedOpenNucleus (j : α → α) (hj_mono : Monotone j)
    (hj_ext : ∀ x, x ≤ j x) (hj_idem : ∀ x, j (j x) = j x) :
    Nucleus (AlexandrovOpen α) where
  toFun := inducedOpenMap j hj_mono
  map_inf' := inducedOpenMap_inf (j := j) (hj_mono := hj_mono)
  idempotent' U := by
    rw [inducedOpenMap_idempotent (j := j) (hj_mono := hj_mono) hj_idem U]
  le_apply' := inducedOpenMap_extensive (j := j) (hj_mono := hj_mono) hj_ext

@[simp] theorem inducedOpenNucleus_apply {j : α → α} {hj_mono : Monotone j}
    {hj_ext : ∀ x, x ≤ j x} {hj_idem : ∀ x, j (j x) = j x} (U : AlexandrovOpen α) :
    inducedOpenNucleus j hj_mono hj_ext hj_idem U = inducedOpenMap j hj_mono U :=
  rfl

end Repair

end AlexandrovOpen

end NECP
end Crypto
end HeytingLean
