import HeytingLean.Crypto.NECP.AlexandrovRepair
import HeytingLean.Crypto.NECP.PrincipalNucleus

namespace HeytingLean
namespace Crypto
namespace NECP

open Set

universe u

namespace AlexandrovOpen

section Packet

variable {α : Type u} [Preorder α]

/-- A legitimate Alexandrov transmission packet is a pair of Alexandrov opens. -/
abbrev Packet (α : Type u) [Preorder α] := AlexandrovOpen α × AlexandrovOpen α

/-- The smallest Alexandrov open containing an arbitrary subset. -/
def openHull (s : Set α) : AlexandrovOpen α :=
  ⟨{x | ∃ y ∈ s, y ≤ x}, by
    intro a b hab ha
    rcases ha with ⟨y, hy, hya⟩
    exact ⟨y, hy, le_trans hya hab⟩⟩

@[simp] theorem mem_openHull {s : Set α} {x : α} :
    x ∈ openHull s ↔ ∃ y ∈ s, y ≤ x := by
  rfl

/-- The positive gap left after observing the public closure. -/
def gapSet (n : NuclearFrame (AlexandrovOpen α)) (U : AlexandrovOpen α) : Set α :=
  {x | x ∈ n U ∧ x ∉ U}

/-- Maximal elements of a subset of the base preorder. -/
def maximalIn (s : Set α) (x : α) : Prop :=
  x ∈ s ∧ ∀ ⦃y : α⦄, x ≤ y → y ∈ s → y = x

/-- The frontier of maximal points lost between `U` and its public closure. -/
def frontierSet (n : NuclearFrame (AlexandrovOpen α)) (U : AlexandrovOpen α) : Set α :=
  {x | maximalIn (gapSet n U) x}

/-- Alexandrov-open packet component generated by the maximal missing frontier. -/
def frontierOpen (n : NuclearFrame (AlexandrovOpen α)) (U : AlexandrovOpen α) :
    AlexandrovOpen α :=
  openHull (frontierSet n U)

/-- The full legitimate transmission packet: public closure plus frontier side information. -/
def frontierPacket (n : NuclearFrame (AlexandrovOpen α)) (U : AlexandrovOpen α) :
    Packet α :=
  (n U, frontierOpen n U)

/-- The public observation exposed to an adversary is the first projection. -/
def publicObservation (packet : Packet α) : AlexandrovOpen α :=
  packet.1

/-- Evolve the current nucleus by adjoining the principal nucleus of the public observation. -/
def evolveWithObservation (n : NuclearFrame (AlexandrovOpen α)) (packet : Packet α) :
    NuclearFrame (AlexandrovOpen α) :=
  n ⊔ principalNucleus (publicObservation packet)

@[simp] theorem publicObservation_mk (published frontier : AlexandrovOpen α) :
    publicObservation (published, frontier) = published :=
  rfl

@[simp] theorem frontierPacket_publicObservation (n : NuclearFrame (AlexandrovOpen α))
    (U : AlexandrovOpen α) :
    publicObservation (frontierPacket n U) = n U :=
  rfl

@[simp] theorem evolveWithObservation_frontierPacket (n : NuclearFrame (AlexandrovOpen α))
    (U : AlexandrovOpen α) :
    evolveWithObservation n (frontierPacket n U) = n ⊔ principalNucleus (n U) :=
  rfl

@[simp] theorem gapSet_subset_apply (n : NuclearFrame (AlexandrovOpen α)) (U : AlexandrovOpen α) :
    gapSet n U ⊆ n U := by
  intro x hx
  exact hx.1

theorem le_publicObservation_frontierPacket (n : NuclearFrame (AlexandrovOpen α))
    (U : AlexandrovOpen α) :
    U ≤ publicObservation (frontierPacket n U) := by
  intro x hx
  exact (Nucleus.le_apply (n := n) (x := U)) hx

end Packet

end AlexandrovOpen

end NECP
end Crypto
end HeytingLean
