import HeytingLean.Crypto.NECP.NucleusFrame

namespace HeytingLean
namespace Crypto
namespace NECP

universe u

section

variable {F : Type u} [Order.Frame F]

/-- The principal nucleus generated by `c`, implemented as join with `c`. -/
def principalNucleus (c : F) : NuclearFrame F where
  toFun x := c ⊔ x
  map_inf' x y := by
    rw [sup_inf_left]
  idempotent' x := by
    simp
  le_apply' x := by
    exact le_sup_right

@[simp] theorem principalNucleus_apply (c x : F) :
    principalNucleus c x = c ⊔ x :=
  rfl

@[simp] theorem principalNucleus_fixed_iff {c x : F} :
    principalNucleus c x = x ↔ c ≤ x := by
  simp [principalNucleus, sup_eq_right]

@[simp] theorem principalNucleus_mem_fixedPoints_iff {c x : F} :
    x ∈ fixedPoints (principalNucleus c) ↔ c ≤ x := by
  simp [fixedPoints]

@[simp] theorem principalNucleus_idempotent (c : F) (x : F) :
    principalNucleus c (principalNucleus c x) = principalNucleus c x := by
  simp [principalNucleus]

end

end NECP
end Crypto
end HeytingLean
