import HeytingLean.Compilation.LambdaIR.Layout
import Mathlib.Data.List.Basic

/-!
# Plain C code generation for layouts (scaffold)

This module emits *text* for layout-related C helpers:
- `#define` shape/stride macros for static layouts,
- `static inline` offset functions,
- a runtime layout struct + dynamic offset function template.

The output is deterministic and total (`String`), suitable for later file emission.
-/

namespace HeytingLean
namespace Compilation
namespace CBackend

open HeytingLean.Compilation.LambdaIR

private def intercalateLines (xs : List String) : String :=
  String.intercalate "\n" xs

/-- Generate C `#define`s for a static layout. -/
def genLayoutMacros (name : String) (layout : LayoutAnnotation) : String :=
  let shapeDefs :=
    (List.zip (List.range layout.shape.length) layout.shape).map
      (fun (i, s) => s!"#define {name}_SHAPE_{i} {s}")
  let strideDefs :=
    (List.zip (List.range layout.stride.length) layout.stride).map
      (fun (i, d) => s!"#define {name}_STRIDE_{i} {d}")
  let sizeDef := s!"#define {name}_SIZE {layout.size}"
  intercalateLines (shapeDefs ++ strideDefs ++ [sizeDef])

/-- Generate a C inline offset function for a static layout (expects macros already emitted). -/
def genIndexFunction (name : String) (layout : LayoutAnnotation) : String :=
  let rank := layout.rank
  let params :=
    match rank with
    | 0 => "void"
    | _ =>
        (List.range rank).map (fun k => s!"int i{k}") |> String.intercalate ", "
  let body :=
    match rank with
    | 0 => "0"
    | _ =>
        (List.range rank).map (fun k => s!"i{k} * {name}_STRIDE_{k}")
          |> String.intercalate " + "
  s!"static inline int {name}_offset({params}) " ++ "{\n  return " ++ body ++ ";\n}\n"

/-- Generate a runtime layout struct + dynamic offset function template. -/
def genRuntimeLayoutStruct (name : String) (rank : Nat) : String :=
  "typedef struct {\n" ++
    s!"  int shape[{rank}];\n" ++
    s!"  int stride[{rank}];\n" ++
    ("} " ++ name ++ "_Layout;\n\n") ++
  s!"static inline int {name}_offset_dynamic(const {name}_Layout* L, const int* idx) " ++ "{\n" ++
    "  int offset = 0;\n" ++
    s!"  for (int i = 0; i < {rank}; i++) " ++ "{\n" ++
    "    offset += idx[i] * L->stride[i];\n" ++
    "  }\n" ++
    "  return offset;\n" ++
    "}\n"

private def certComment (c : LayoutCertificate) : String :=
  s!"/* cert: op={c.operation}, hash={c.proofHash} */"

/-- Emit a `.h`-style C header containing all layout helpers for a module. -/
def genCFile (moduleName : String)
    (layouts : List (String × LayoutAnnotation))
    (certs : List LayoutCertificate) : String :=
  let preamble :=
    intercalateLines
      [s!"/* Generated by HeytingLean (Plain C) — module: {moduleName} */",
       "#pragma once",
       ""]
  let certsBlock :=
    match certs with
    | [] => ""
    | _ =>
        intercalateLines ("/* Certificates */" :: certs.map certComment) ++ "\n\n"
  let layoutBlocks :=
    layouts.map (fun (nm, l) =>
      if l.isStatic then
        intercalateLines
          [s!"/* Layout: {nm} (static) */",
           genLayoutMacros nm l,
           "",
           genIndexFunction nm l]
      else
        intercalateLines
          [s!"/* Layout: {nm} (runtime) */",
           genRuntimeLayoutStruct nm l.rank])
  preamble ++ certsBlock ++ String.intercalate "\n\n" layoutBlocks ++ "\n"

end CBackend
end Compilation
end HeytingLean
